
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var e,k;var l;l||(l=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa={},n;for(n in l)l.hasOwnProperty(n)&&(aa[n]=l[n]);l.arguments=[];l.thisProgram="./this.program";l.quit=function(a,b){throw b;};l.preRun=[];l.postRun=[];var ba=!1,r=!1,t=!1,ca=!1;ba="object"===typeof window;r="function"===typeof importScripts;t="object"===typeof process&&"function"===typeof require&&!ba&&!r;ca=!ba&&!t&&!r;var v="";
if(t){v=__dirname+"/";var da,ea;l.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};l.readBinary=function(a){a=l.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(l.thisProgram=process.argv[1].replace(/\\/g,"/"));l.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",w);l.quit=function(a){process.exit(a)};
l.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(l.read=function(a){return read(a)}),l.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?l.arguments=scriptArgs:"undefined"!=typeof arguments&&(l.arguments=arguments),"function"===typeof quit&&(l.quit=function(a){quit(a)});else if(ba||r)r?v=self.location.href:document.currentScript&&
(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="",l.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(l.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),l.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},l.setWindowTitle=function(a){document.title=a};var ha=l.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=l.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(n in aa)aa.hasOwnProperty(n)&&(l[n]=aa[n]);aa=void 0;function ia(a){var b=A[ja>>2];a=b+a+15&-16;if(a<=ka())A[ja>>2]=a;else if(!la(a))return 0;return b}
var ma={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&z("no native wasm support detected");var na,oa=!1;function assert(a,b){a||w("Assertion failed: "+b)}function pa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=ra(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)A[a>>2]=0;for(b=d+c;a<b;)C[a++>>0]=0;return d}a.subarray||a.slice?D.set(a,d):D.set(new Uint8Array(a),d);return d}
var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function ua(a){return a?ta(D,a,void 0):""}
function va(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function xa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,C,D,ya,za,A,F,Aa,Ba;
function Ca(){l.HEAP8=C=new Int8Array(buffer);l.HEAP16=ya=new Int16Array(buffer);l.HEAP32=A=new Int32Array(buffer);l.HEAPU8=D=new Uint8Array(buffer);l.HEAPU16=za=new Uint16Array(buffer);l.HEAPU32=F=new Uint32Array(buffer);l.HEAPF32=Aa=new Float32Array(buffer);l.HEAPF64=Ba=new Float64Array(buffer)}var ja=3397344,Da=l.TOTAL_MEMORY||16777216;5242880>Da&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Da+"! (TOTAL_STACK=5242880)");
l.buffer?buffer=l.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(na=new WebAssembly.Memory({initial:Da/65536}),buffer=na.buffer):buffer=new ArrayBuffer(Da);Ca();A[ja>>2]=8640256;function Ea(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.xc;"number"===typeof c?void 0===b.bc?l.dynCall_v(c):l.dynCall_vi(c,b.bc):c(void 0===b.bc?null:b.bc)}}}var Fa=[],Ga=[],Ha=[],Ia=[],Ja=!1;function Ka(){var a=l.preRun.shift();Fa.unshift(a)}
var La=Math.abs,Ma=Math.ceil,Na=Math.floor,Oa=Math.min,Pa=Math.trunc,Qa=0,Ra=null,Sa=null;l.preloadedImages={};l.preloadedAudios={};function Ta(){var a=Ua;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ua="convert.wasm";if(!Ta()){var Va=Ua;Ua=l.locateFile?l.locateFile(Va,v):v+Va}
function Wa(){try{if(l.wasmBinary)return new Uint8Array(l.wasmBinary);if(l.readBinary)return l.readBinary(Ua);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}function Xa(){return l.wasmBinary||!ba&&!r||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
function Ya(a){function b(a){l.asm=a.exports;Qa--;l.monitorRunDependencies&&l.monitorRunDependencies(Qa);0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(a=Sa,Sa=null,a()))}function c(a){b(a.instance)}function d(a){Xa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);w(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ma};Qa++;l.monitorRunDependencies&&l.monitorRunDependencies(Qa);if(l.instantiateWasm)try{return l.instantiateWasm(f,
b)}catch(g){return z("Module.instantiateWasm callback failed with error: "+g),!1}l.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Ua,{credentials:"same-origin"}),f).then(c,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");d(c)});return{}}
l.asm=function(a,b){b.memory=na;b.table=new WebAssembly.Table({initial:5882,maximum:5882,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Ya(b)};Ga.push({xc:function(){Za()}});var G={};
function $a(a){if($a.Hb){var b=A[a>>2];var c=A[b>>2]}else $a.Hb=!0,G.USER=G.LOGNAME="web_user",G.PATH="/",G.PWD="/",G.HOME="/home/web_user",G.LANG="C.UTF-8",G._=l.thisProgram,c=Ja?ra(1024):ia(1024),b=Ja?ra(256):ia(256),A[b>>2]=c,A[a>>2]=b;a=[];var d=0,f;for(f in G)if("string"===typeof G[f]){var g=f+"="+G[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,m=0;m<d.length;++m)C[h++>>0]=d.charCodeAt(m);C[h>>0]=0;A[b+
4*f>>2]=c;c+=g.length+1}A[b+4*a.length>>2]=0}function ab(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function bb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ab(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function cb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function db(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function eb(){var a=Array.prototype.slice.call(arguments,0);return bb(a.join("/"))}function fb(a,b){return bb(a+"/"+b)}function gb(a){l.___errno_location&&(A[l.___errno_location()>>2]=a);return a}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ab(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function ib(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=hb(a).substr(1);b=hb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var jb=[];function kb(a,b){jb[a]={input:[],output:[],Vb:b};lb(a,mb)}
var mb={open:function(a){var b=jb[a.node.rdev];if(!b)throw new I(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.Vb.flush(a.tty)},flush:function(a){a.tty.Vb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Vb.pc)throw new I(6);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Vb.pc(a.tty)}catch(m){throw new I(5);}if(void 0===h&&0===f)throw new I(11);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Vb.dc)throw new I(6);
try{for(var f=0;f<d;f++)a.tty.Vb.dc(a.tty,b[c+f])}catch(g){throw new I(5);}d&&(a.node.timestamp=Date.now());return f}},ob={pc:function(a){if(!a.input.length){var b=null;if(t){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},dc:function(a,b){null===b||10===b?(ha(ta(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(ta(a.output,0)),a.output=[])}},pb={dc:function(a,b){null===b||10===b?(z(ta(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(z(ta(a.output,0)),a.output=[])}},J={Lb:null,Gb:function(){return J.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(1);J.Lb||(J.Lb={dir:{node:{Jb:J.Ab.Jb,Kb:J.Ab.Kb,lookup:J.Ab.lookup,Xb:J.Ab.Xb,rename:J.Ab.rename,unlink:J.Ab.unlink,rmdir:J.Ab.rmdir,readdir:J.Ab.readdir,symlink:J.Ab.symlink},stream:{Ob:J.Cb.Ob}},file:{node:{Jb:J.Ab.Jb,Kb:J.Ab.Kb},stream:{Ob:J.Cb.Ob,read:J.Cb.read,write:J.Cb.write,hc:J.Cb.hc,qc:J.Cb.qc,
sc:J.Cb.sc}},link:{node:{Jb:J.Ab.Jb,Kb:J.Ab.Kb,readlink:J.Ab.readlink},stream:{}},jc:{node:{Jb:J.Ab.Jb,Kb:J.Ab.Kb},stream:qb}});c=rb(a,b,c,d);K(c.mode)?(c.Ab=J.Lb.dir.node,c.Cb=J.Lb.dir.stream,c.Bb={}):32768===(c.mode&61440)?(c.Ab=J.Lb.file.node,c.Cb=J.Lb.file.stream,c.Eb=0,c.Bb=null):40960===(c.mode&61440)?(c.Ab=J.Lb.link.node,c.Cb=J.Lb.link.stream):8192===(c.mode&61440)&&(c.Ab=J.Lb.jc.node,c.Cb=J.Lb.jc.stream);c.timestamp=Date.now();a&&(a.Bb[b]=c);return c},Sc:function(a){if(a.Bb&&a.Bb.subarray){for(var b=
[],c=0;c<a.Eb;++c)b.push(a.Bb[c]);return b}return a.Bb},Tc:function(a){return a.Bb?a.Bb.subarray?a.Bb.subarray(0,a.Eb):new Uint8Array(a.Bb):new Uint8Array},kc:function(a,b){var c=a.Bb?a.Bb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Bb,a.Bb=new Uint8Array(b),0<a.Eb&&a.Bb.set(c.subarray(0,a.Eb),0))},Gc:function(a,b){if(a.Eb!=b)if(0==b)a.Bb=null,a.Eb=0;else{if(!a.Bb||a.Bb.subarray){var c=a.Bb;a.Bb=new Uint8Array(new ArrayBuffer(b));c&&a.Bb.set(c.subarray(0,Math.min(b,
a.Eb)))}else if(a.Bb||(a.Bb=[]),a.Bb.length>b)a.Bb.length=b;else for(;a.Bb.length<b;)a.Bb.push(0);a.Eb=b}},Ab:{Jb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Eb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Rb=4096;b.blocks=Math.ceil(b.size/b.Rb);return b},Kb:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.Gc(a,b.size)},lookup:function(){throw sb[2];},Xb:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=L(b,c)}catch(g){}if(d)for(var f in d.Bb)throw new I(39);}delete a.parent.Bb[a.name];a.name=c;b.Bb[c]=a;a.parent=b},unlink:function(a,b){delete a.Bb[b]},rmdir:function(a,b){var c=L(a,b),d;for(d in c.Bb)throw new I(39);delete a.Bb[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.Bb)a.Bb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(22);return a.link}},Cb:{read:function(a,b,c,d,f){var g=a.node.Bb;if(f>=a.node.Eb)return 0;a=Math.min(a.node.Eb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.Bb||a.Bb.subarray)){if(g)return a.Bb=b.subarray(c,c+d),a.Eb=d;if(0===a.Eb&&0===f)return a.Bb=new Uint8Array(b.subarray(c,c+d)),a.Eb=d;if(f+d<=a.Eb)return a.Bb.set(b.subarray(c,c+d),f),d}J.kc(a,f+d);if(a.Bb.subarray&&b.subarray)a.Bb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Bb[f+g]=b[c+g];a.Eb=Math.max(a.Eb,f+d);return d},Ob:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Eb);if(0>b)throw new I(22);return b},hc:function(a,b,c){J.kc(a.node,b+c);a.node.Eb=
Math.max(a.node.Eb,b+c)},qc:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new I(19);c=a.node.Bb;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Eb)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=ra(d);if(!d)throw new I(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{Wc:d,Rc:a}},sc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new I(19);if(f&2)return 0;J.Cb.write(a,b,0,d,c,!1);return 0}}},M={Zb:!1,Lc:function(){M.Zb=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);M.mc={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ic:function(a){return Buffer.Hb?Buffer.from(a):new Buffer(a)},Gb:function(a){assert(t);return M.createNode(null,"/",M.oc(a.cc.root),0)},createNode:function(a,b,c){if(!K(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(22);a=rb(a,b,c);a.Ab=M.Ab;a.Cb=M.Cb;return a},oc:function(a){try{var b=fs.lstatSync(a);M.Zb&&(b.mode=b.mode|(b.mode&
292)>>2)}catch(c){if(!c.code)throw c;throw new I(-c.Db);}return b.mode},Ib:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Gb.cc.root);b.reverse();return eb.apply(null,b)},wc:function(a){a&=-2656257;var b=0,c;for(c in M.mc)a&c&&(b|=M.mc[c],a^=c);if(a)throw new I(22);return b},Ab:{Jb:function(a){a=M.Ib(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.Db);}M.Zb&&!b.Rb&&(b.Rb=4096);M.Zb&&!b.blocks&&(b.blocks=(b.size+b.Rb-1)/b.Rb|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Rb:b.Rb,blocks:b.blocks}},Kb:function(a,b){var c=M.Ib(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new I(-d.Db);}},lookup:function(a,b){var c=fb(M.Ib(a),b);c=M.oc(c);return M.createNode(a,b,c)},Xb:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.Ib(a);try{K(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(-f.Db);}return a},rename:function(a,b,c){a=M.Ib(a);b=fb(M.Ib(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new I(-d.Db);}},unlink:function(a,b){a=fb(M.Ib(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.Db);}},rmdir:function(a,b){a=fb(M.Ib(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.Db);}},readdir:function(a){a=M.Ib(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new I(-b.Db);
}},symlink:function(a,b,c){a=fb(M.Ib(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new I(-d.Db);}},readlink:function(a){var b=M.Ib(a);try{return b=fs.readlinkSync(b),b=tb.relative(tb.resolve(a.Gb.cc.root),b)}catch(c){if(!c.code)throw c;throw new I(-c.Db);}}},Cb:{open:function(a){var b=M.Ib(a.node);try{32768===(a.node.mode&61440)&&(a.Yb=fs.openSync(b,M.wc(a.flags)))}catch(c){if(!c.code)throw c;throw new I(-c.Db);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Yb&&fs.closeSync(a.Yb)}catch(b){if(!b.code)throw b;
throw new I(-b.Db);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.Yb,M.ic(b.buffer),c,d,f)}catch(g){throw new I(-g.Db);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.Yb,M.ic(b.buffer),c,d,f)}catch(g){throw new I(-g.Db);}},Ob:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Yb).size}catch(d){throw new I(-d.Db);}if(0>b)throw new I(22);return b}}},ub=null,vb={},wb=[],xb=1,yb=null,zb=!0,N={},I=null,sb={};
function O(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={nc:!0,ec:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ec)throw new I(40);a=ab(a.split("/").filter(function(a){return!!a}),!1);var f=ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=L(f,a[d]);c=fb(c,a[d]);f.Pb&&(!g||g&&b.nc)&&(f=f.Pb.root);if(!g||b.Wb)for(g=0;40960===(f.mode&61440);)if(f=Ab(c),c=hb(cb(c),f),f=O(c,{ec:b.ec}).node,40<g++)throw new I(40);}return{path:c,node:f}}
function Bb(a){for(var b;;){if(a===a.parent)return a=a.Gb.rc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Cb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function Db(a){var b=Cb(a.parent.id,a.name);a.Ub=yb[b];yb[b]=a}function Eb(a){var b=Cb(a.parent.id,a.name);if(yb[b]===a)yb[b]=a.Ub;else for(b=yb[b];b;){if(b.Ub===a){b.Ub=a.Ub;break}b=b.Ub}}
function L(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.Ab.lookup?0:13)throw new I(c,a);for(c=yb[Cb(a.id,b)];c;c=c.Ub){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ab.lookup(a,b)}
function rb(a,b,c,d){Gb||(Gb=function(a,b,c,d){a||(a=this);this.parent=a;this.Gb=a.Gb;this.Pb=null;this.id=xb++;this.name=b;this.mode=c;this.Ab={};this.Cb={};this.rdev=d},Gb.prototype={},Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Gb(a,b,c,d);Db(a);return a}
function K(a){return 16384===(a&61440)}var Hb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(zb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Jb(a,b){try{return L(a,b),17}catch(c){}return Fb(a,"wx")}
function Kb(a,b,c){try{var d=L(a,b)}catch(f){return f.Db}if(a=Fb(a,"wx"))return a;if(c){if(!K(d.mode))return 20;if(d===d.parent||"/"===Bb(d))return 16}else if(K(d.mode))return 21;return 0}function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!wb[a])return a;throw new I(24);}
function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={},Object.defineProperties(Nb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return wb[b]=a}var qb={open:function(a){a.Cb=vb[a.node.rdev].Cb;a.Cb.open&&a.Cb.open(a)},Ob:function(){throw new I(29);}};function lb(a,b){vb[a]={Cb:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&ub)throw new I(16);if(!c&&!d){var f=O(b,{nc:!1});b=f.path;f=f.node;if(f.Pb)throw new I(16);if(!K(f.mode))throw new I(20);}b={type:a,cc:{},rc:b,Dc:[]};a=a.Gb(b);a.Gb=b;b.root=a;c?ub=a:f&&(f.Pb=b,f.Gb&&f.Gb.Dc.push(b))}function Pb(a,b,c){var d=O(a,{parent:!0}).node;a=db(a);if(!a||"."===a||".."===a)throw new I(22);var f=Jb(d,a);if(f)throw new I(f);if(!d.Ab.Xb)throw new I(1);return d.Ab.Xb(d,a,b,c)}function P(a){Pb(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Pb(a,b|8192,c)}function Rb(a,b){if(!hb(a))throw new I(2);var c=O(b,{parent:!0}).node;if(!c)throw new I(2);b=db(b);var d=Jb(c,b);if(d)throw new I(d);if(!c.Ab.symlink)throw new I(1);c.Ab.symlink(c,b,a)}function Ab(a){a=O(a).node;if(!a)throw new I(2);if(!a.Ab.readlink)throw new I(22);return hb(Bb(a.parent),a.Ab.readlink(a))}function Sb(a,b){a=O(a,{Wb:!b}).node;if(!a)throw new I(2);if(!a.Ab.Jb)throw new I(1);return a.Ab.Jb(a)}
function Tb(a){return Sb(a,!0)}
function Ub(a,b,c,d){if(""===a)throw new I(2);if("string"===typeof b){var f=Hb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=bb(a);try{g=O(a,{Wb:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new I(17);}else g=Pb(a,c,0),f=!0;if(!g)throw new I(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!K(g.mode))throw new I(20);if(!f&&(c=g?40960===(g.mode&61440)?40:K(g.mode)&&
("r"!==Ib(b)||b&512)?21:Fb(g,Ib(b)):2))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=O(c,{Wb:!0}).node:h=c;if(!h.Ab.Kb)throw new I(1);if(K(h.mode))throw new I(21);if(32768!==(h.mode&61440))throw new I(22);if(c=Fb(h,"w"))throw new I(c);h.Ab.Kb(h,{size:0,timestamp:Date.now()})}b&=-641;d=Mb({node:g,path:Bb(g),flags:b,seekable:!0,position:0,Cb:g.Cb,Qc:[],error:!1},d);d.Cb.open&&d.Cb.open(d);!l.logReadFiles||b&1||(Vb||(Vb={}),a in Vb||(Vb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{N.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),N.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Wb(a,b,c){if(null===a.fd)throw new I(9);if(!a.seekable||!a.Cb.Ob)throw new I(29);if(0!=c&&1!=c&&2!=c)throw new I(22);a.position=a.Cb.Ob(a,b,c);a.Qc=[];return a.position}
function Xb(a,b,c,d){var f=C;if(0>c||0>d)throw new I(22);if(null===a.fd)throw new I(9);if(1===(a.flags&2097155))throw new I(9);if(K(a.node.mode))throw new I(21);if(!a.Cb.read)throw new I(22);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new I(29);b=a.Cb.read(a,f,b,c,d);g||(a.position+=b);return b}
function Yb(a,b,c,d){var f=C;if(0>c||0>d)throw new I(22);if(null===a.fd)throw new I(9);if(0===(a.flags&2097155))throw new I(9);if(K(a.node.mode))throw new I(21);if(!a.Cb.write)throw new I(22);a.flags&1024&&Wb(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new I(29);b=a.Cb.write(a,f,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&N.onWriteToFile)N.onWriteToFile(a.path)}catch(h){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+h.message)}return b}
function Zb(){I||(I=function(a,b){this.node=b;this.Hc=function(a){this.Db=a};this.Hc(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},I.prototype=Error(),I.prototype.constructor=I,[2].forEach(function(a){sb[a]=new I(a);sb[a].stack="<generic error, no stack>"}))}var $b;function ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function bc(a,b,c){a=fb("/dev",a);var d=ac(!!b,!!c);cc||(cc=64);var f=cc++<<8|0;lb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,h=0;h<f;h++){try{var m=b()}catch(E){throw new I(5);}if(void 0===m&&0===g)throw new I(11);if(null===m||void 0===m)break;g++;c[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(u){throw new I(5);}f&&(a.node.timestamp=Date.now());return g}});
Qb(a,d,f)}var cc,Q={},Gb,Nb,Vb;
function dc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&bb(b)!==bb(Bb(f.node)))return-20;throw f;}A[c>>2]=d.dev;A[c+4>>2]=0;A[c+8>>2]=d.ino;A[c+12>>2]=d.mode;A[c+16>>2]=d.nlink;A[c+20>>2]=d.uid;A[c+24>>2]=d.gid;A[c+28>>2]=d.rdev;A[c+32>>2]=0;e=[d.size>>>0,(k=d.size,1<=+La(k)?0<k?(Oa(+Na(k/4294967296),4294967295)|0)>>>0:~~+Ma((k-+(~~k>>>0))/4294967296)>>>0:0)];A[c+40>>2]=e[0];A[c+44>>2]=e[1];A[c+48>>2]=4096;A[c+52>>2]=d.blocks;A[c+56>>2]=d.atime.getTime()/1E3|0;A[c+60>>2]=0;A[c+64>>2]=d.mtime.getTime()/
1E3|0;A[c+68>>2]=0;A[c+72>>2]=d.ctime.getTime()/1E3|0;A[c+76>>2]=0;e=[d.ino>>>0,(k=d.ino,1<=+La(k)?0<k?(Oa(+Na(k/4294967296),4294967295)|0)>>>0:~~+Ma((k-+(~~k>>>0))/4294967296)>>>0:0)];A[c+80>>2]=e[0];A[c+84>>2]=e[1];return 0}var R=0;function S(){R+=4;return A[R-4>>2]}function ec(){return ua(S())}function T(){var a=wb[S()];if(!a)throw new I(9);return a}var fc={};function hc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function ic(a){return this.fromWireType(F[a>>2])}var jc={},kc={},lc={};
function mc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function nc(a,b){a=mc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function oc(a){var b=Error,c=nc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var pc=void 0;
function qc(a,b,c){function d(b){b=c(b);if(b.length!==a.length)throw new pc("Mismatched type converter count");for(var d=0;d<a.length;++d)U(a[d],b[d])}a.forEach(function(a){lc[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){kc.hasOwnProperty(a)?f[b]=kc[a]:(g.push(a),jc.hasOwnProperty(a)||(jc[a]=[]),jc[a].push(function(){f[b]=kc[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function rc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var sc=void 0;function V(a){for(var b="";D[a];)b+=sc[D[a++]];return b}var tc=void 0;function W(a){throw new tc(a);}
function U(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(kc.hasOwnProperty(a)){if(c.Bc)return;W("Cannot register type '"+d+"' twice")}kc[a]=b;delete lc[a];jc.hasOwnProperty(a)&&(b=jc[a],delete jc[a],b.forEach(function(a){a()}))}var uc=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function vc(a){4<a&&0===--Y[a].fc&&(Y[a]=void 0,uc.push(a))}function wc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=uc.length?uc.pop():Y.length;Y[b]={fc:1,value:a};return b}}function xc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function yc(a,b){switch(b){case 2:return function(a){return this.fromWireType(Aa[a>>2])};case 3:return function(a){return this.fromWireType(Ba[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function zc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=nc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Bc(a,b){var c=l;if(void 0===c[a].Mb){var d=c[a];c[a]=function(){c[a].Mb.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Mb+")!");return c[a].Mb[arguments.length].apply(this,arguments)};c[a].Mb=[];c[a].Mb[d.uc]=d}}
function Cc(a,b,c){l.hasOwnProperty(a)?((void 0===c||void 0!==l[a].Mb&&void 0!==l[a].Mb[c])&&W("Cannot register public name '"+a+"' twice"),Bc(a,a),l.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),l[a].Mb[c]=b):(l[a]=b,void 0!==c&&(l[a].Vc=c))}function Dc(a,b){for(var c=[],d=0;d<a;d++)c.push(A[(b>>2)+d]);return c}
function Ec(a,b){a=V(a);if(void 0!==l["FUNCTION_TABLE_"+a])var c=l["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=l["dynCall_"+a];void 0===c&&(c=l["dynCall_"+a.replace(/f/g,"d")],void 0===c&&W("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var Fc=void 0;function Gc(a){a=Hc(a);var b=V(a);Z(a);return b}function Ic(a,b){function c(a){f[a]||kc[a]||(lc[a]?lc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Fc(a+": "+d.map(Gc).join([", "]));}
function Jc(a,b,c){switch(b){case 0:return c?function(a){return C[a]}:function(a){return D[a]};case 1:return c?function(a){return ya[a>>1]}:function(a){return za[a>>1]};case 2:return c?function(a){return A[a>>2]}:function(a){return F[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Kc(){void 0===Kc.start&&(Kc.start=Date.now());return 1E3*(Date.now()-Kc.start)|0}function Lc(){w()}function ka(){return C.length}
function Mc(a){a=xa(a);var b=buffer.byteLength;try{return-1!==na.grow((a-b)/65536)?(buffer=na.buffer,!0):!1}catch(c){return!1}}function la(a){if(2147418112<a)return!1;for(var b=Math.max(ka(),16777216);b<a;)536870912>=b?b=xa(2*b):b=Math.min(xa((3*b+2147483648)/4),2147418112);if(!Mc(b))return!1;Ca();return!0}function Nc(a){if(0===a)return 0;a=ua(a);if(!G.hasOwnProperty(a))return 0;Nc.Hb&&Z(Nc.Hb);a=G[a];var b=wa(a)+1,c=ra(b);c&&va(a,C,c,b);Nc.Hb=c;return Nc.Hb}va("GMT",D,3397248,4);
function Oc(a){return Math.pow(2,a)}function Pc(a){return Math.log(a)/Math.LN10}function Qc(a){return Math.log(a)/Math.LN2}function Rc(){Rc.Hb||(Rc.Hb=[]);Rc.Hb.push(Sc());return Rc.Hb.length-1}
function Tc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Uc){Uc=!0;A[Vc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);A[Wc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=pa(nb(d));f=pa(nb(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(A[Xc()>>2]=d,A[Xc()+4>>2]=f):(A[Xc()>>2]=f,A[Xc()+4>>2]=d)}}var Uc;function Yc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Zc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var $c=[31,29,31,30,31,30,31,31,30,31,30,31],ad=[31,28,31,30,31,30,31,31,30,31,30,31];function bd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Yc(a.getFullYear())?$c:ad)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}Zb();yb=Array(4096);Ob(J,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");lb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});Qb("/dev/null",259);kb(1280,ob);kb(1536,pb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(t)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){w("random_device")});bc("random",b);bc("urandom",b);P("/dev/shm");
P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");Ob({Gb:function(){var a=rb("/proc/self","fd",16895,73);a.Ab={lookup:function(a,c){var b=wb[+c];if(!b)throw new I(9);a={parent:null,Gb:{rc:"fake"},Ab:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(t){var fs=require("fs"),tb=require("path");M.Lc()}pc=l.InternalError=oc("InternalError");for(var cd=Array(256),dd=0;256>dd;++dd)cd[dd]=String.fromCharCode(dd);sc=cd;tc=l.BindingError=oc("BindingError");
l.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};l.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Fc=l.UnboundTypeError=oc("UnboundTypeError");t?Lc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Lc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Lc=function(){return performance.now()}:Lc=Date.now;
function nb(a,b){var c=Array(wa(a)+1);a=va(a,c,0,c.length);b&&(c.length=a);return c}
var fd=l.asm({},{d:w,l:function(){},c:function(a,b,c,d){w("Assertion failed: "+ua(a)+", at: "+[b?ua(b):"unknown filename",c,d?ua(d):"unknown function"])},ea:$a,F:function(){},C:gb,A:function(a,b){R=b;try{var c=ec(),d=O(c,{parent:!0}).node,f=db(c),g=L(d,f),h=Kb(d,f,!1);if(h)throw new I(h);if(!d.Ab.unlink)throw new I(1);if(g.Pb)throw new I(16);try{N.willDeletePath&&N.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Ab.unlink(d,
f);Eb(g);try{if(N.onDeletePath)N.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof I||w(m),-m.Db}},y:function(a,b){R=b;try{var c=T(),d=S(),f=S(),g=S(),h=S();if(!(-1==d&&0>f||0==d&&0<=f))return-75;Wb(c,f,h);e=[c.position>>>0,(k=c.position,1<=+La(k)?0<k?(Oa(+Na(k/4294967296),4294967295)|0)>>>0:~~+Ma((k-+(~~k>>>0))/4294967296)>>>0:0)];A[g>>2]=e[0];A[g+4>>2]=e[1];c.Sb&&0===f&&
0===h&&(c.Sb=null);return 0}catch(m){return"undefined"!==typeof Q&&m instanceof I||w(m),-m.Db}},K:function(a,b){R=b;try{var c=T(),d=S();a:{var f=S();for(b=a=0;b<f;b++){var g=A[d+(8*b+4)>>2],h=Xb(c,A[d+8*b>>2],g,void 0);if(0>h){var m=-1;break a}a+=h;if(h<g)break}m=a}return m}catch(x){return"undefined"!==typeof Q&&x instanceof I||w(x),-x.Db}},w:function(a,b){R=b;try{var c=T(),d=S();a:{var f=S();for(b=a=0;b<f;b++){var g=Yb(c,A[d+8*b>>2],A[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(m){return"undefined"!==
typeof Q&&m instanceof I||w(m),-m.Db}},v:function(a,b){R=b;try{var c=ec(),d=S();return dc(Sb,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof I||w(f),-f.Db}},ma:function(a,b){R=b;try{var c=ec(),d=S();return dc(Tb,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof I||w(f),-f.Db}},la:function(a,b){R=b;try{var c=T(),d=S();return dc(Sb,c.path,d)}catch(f){return"undefined"!==typeof Q&&f instanceof I||w(f),-f.Db}},ka:function(a,b){R=b;return 0},ja:function(a,b){R=b;try{var c=T(),d=S(),f=S();
if(!c.Sb){var g=O(c.path,{Wb:!0}).node;if(!g.Ab.readdir)throw new I(20);var h=g.Ab.readdir(g);c.Sb=h}a=0;for(var m=Wb(c,0,1),x=Math.floor(m/280);x<c.Sb.length&&a+280<=f;){var p=c.Sb[x];if("."===p[0]){var u=1;var y=4}else{var E=L(c.node,p);u=E.id;y=8192===(E.mode&61440)?2:K(E.mode)?4:40960===(E.mode&61440)?10:8}e=[u>>>0,(k=u,1<=+La(k)?0<k?(Oa(+Na(k/4294967296),4294967295)|0)>>>0:~~+Ma((k-+(~~k>>>0))/4294967296)>>>0:0)];A[d+a>>2]=e[0];A[d+a+4>>2]=e[1];e=[280*(x+1)>>>0,(k=280*(x+1),1<=+La(k)?0<k?(Oa(+Na(k/
4294967296),4294967295)|0)>>>0:~~+Ma((k-+(~~k>>>0))/4294967296)>>>0:0)];A[d+a+8>>2]=e[0];A[d+a+12>>2]=e[1];ya[d+a+16>>1]=280;C[d+a+18>>0]=y;va(p,D,d+a+19,256);a+=280;x+=1}Wb(c,280*x,0);return a}catch(H){return"undefined"!==typeof Q&&H instanceof I||w(H),-H.Db}},k:function(a,b){R=b;try{var c=T();switch(S()){case 0:var d=S();return 0>d?-22:Ub(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=S(),c.flags|=d,0;case 12:return d=S(),ya[d+0>>1]=2,0;case 13:case 14:return 0;
case 16:case 8:return-22;case 9:return gb(22),-1;default:return-22}}catch(f){return"undefined"!==typeof Q&&f instanceof I||w(f),-f.Db}},ia:function(a,b){R=b;try{var c=T(),d=S(),f=S();return Xb(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof I||w(g),-g.Db}},ha:function(a,b){R=b;try{var c=ec();var d=S();if(d&-8)var f=-22;else{var g=O(c,{Wb:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");f=a&&Fb(g,a)?-13:0}return f}catch(h){return"undefined"!==typeof Q&&h instanceof I||w(h),-h.Db}},
ga:function(a,b){R=b;try{var c=ec(),d=ec(),f=cb(c),g=cb(d),h=db(c),m=db(d);try{var x=O(c,{parent:!0});var p=x.node;x=O(d,{parent:!0});var u=x.node}catch(B){throw new I(16);}if(!p||!u)throw new I(2);if(p.Gb!==u.Gb)throw new I(18);var y=L(p,h),E=ib(c,g);if("."!==E.charAt(0))throw new I(22);E=ib(d,f);if("."!==E.charAt(0))throw new I(39);try{var H=L(u,m)}catch(B){}if(y!==H){var q=K(y.mode),X=Kb(p,h,q);if(X)throw new I(X);if(X=H?Kb(u,m,q):Jb(u,m))throw new I(X);if(!p.Ab.rename)throw new I(1);if(y.Pb||
H&&H.Pb)throw new I(16);if(u!==p&&(X=Fb(p,"w")))throw new I(X);try{N.willMovePath&&N.willMovePath(c,d)}catch(B){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+B.message)}Eb(y);try{p.Ab.rename(y,u,m)}catch(B){throw B;}finally{Db(y)}try{if(N.onMovePath)N.onMovePath(c,d)}catch(B){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+B.message)}}return 0}catch(B){return"undefined"!==typeof Q&&B instanceof I||w(B),-B.Db}},fa:function(a,
b){R=b;try{var c=T(),d=S(),f=S();return Yb(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof I||w(g),-g.Db}},J:function(a,b){R=b;try{var c=ec(),d=O(c,{parent:!0}).node,f=db(c),g=L(d,f),h=Kb(d,f,!0);if(h)throw new I(h);if(!d.Ab.rmdir)throw new I(1);if(g.Pb)throw new I(16);try{N.willDeletePath&&N.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Ab.rmdir(d,f);Eb(g);try{if(N.onDeletePath)N.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof I||w(m),-m.Db}},I:function(a,b){R=b;try{var c=ec(),d=S(),f=S();return Ub(c,d,f).fd}catch(g){return"undefined"!==typeof Q&&g instanceof I||w(g),-g.Db}},u:function(a,b){R=b;try{var c=T(),d=S();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var f=S();return A[f>>2]=0;case 21520:return c.tty?
-22:-25;case 21531:a=f=S();if(!c.Cb.Cc)throw new I(25);return c.Cb.Cc(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:w("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof Q&&g instanceof I||w(g),-g.Db}},p:function(a,b){R=b;try{var c=T();if(null===c.fd)throw new I(9);c.Sb&&(c.Sb=null);try{c.Cb.close&&c.Cb.close(c)}catch(d){throw d;}finally{wb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof I||w(d),-d.Db}},o:function(){},da:function(a){var b=
fc[a];delete fc[a];var c=b.Ec,d=b.Fc,f=b.lc,g=f.map(function(a){return a.Ac}).concat(f.map(function(a){return a.Jc}));qc([a],g,function(a){var g={};f.forEach(function(b,c){var d=a[c],h=b.yc,m=b.zc,H=a[c+f.length],q=b.Ic,p=b.Kc;g[b.vc]={read:function(a){return d.fromWireType(h(m,a))},write:function(a,b){var c=[];q(p,a,H.toWireType(c,b));hc(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);d(a);return b},toWireType:function(a,b){for(var f in g)if(!(f in b))throw new TypeError("Missing field");
var h=c();for(f in g)g[f].write(h,b[f]);null!==a&&a.push(d,h);return h},argPackAdvance:8,readValueFromPointer:ic,Nb:d}]})},ca:function(a,b,c,d,f){var g=rc(c);b=V(b);U(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=C;else if(2===c)d=ya;else if(4===c)d=A;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},Nb:null})},ba:function(a,b){b=V(b);U(a,{name:b,fromWireType:function(a){var b=
Y[a].value;vc(a);return b},toWireType:function(a,b){return wc(b)},argPackAdvance:8,readValueFromPointer:ic,Nb:null})},H:function(a,b,c){c=rc(c);b=V(b);U(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+xc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:yc(b,c),Nb:null})},G:function(a,b,c,d,f,g){var h=Dc(b,c);a=V(a);f=Ec(d,f);Cc(a,function(){Ic("Cannot call "+a+" due to unbound types",
h)},b-1);qc([],h,function(c){var d=[c[0],null].concat(c.slice(1)),h=c=a,m=f,y=d.length;2>y&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var E=null!==d[1]&&!1,H=!1,q=1;q<d.length;++q)if(null!==d[q]&&void 0===d[q].Nb){H=!0;break}var X="void"!==d[0].name,B="",qa="";for(q=0;q<y-2;++q)B+=(0!==q?", ":"")+"arg"+q,qa+=(0!==q?", ":"")+"arg"+q+"Wired";h="return function "+mc(h)+"("+B+") {\nif (arguments.length !== "+(y-2)+") {\nthrowBindingError('function "+h+" called with ' + arguments.length + ' arguments, expected "+
(y-2)+" args!');\n}\n";H&&(h+="var destructors = [];\n");var Ac=H?"destructors":"null";B="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[W,m,g,hc,d[0],d[1]];E&&(h+="var thisWired = classParam.toWireType("+Ac+", this);\n");for(q=0;q<y-2;++q)h+="var arg"+q+"Wired = argType"+q+".toWireType("+Ac+", arg"+q+"); // "+d[q+2].name+"\n",B.push("argType"+q),m.push(d[q+2]);E&&(qa="thisWired"+(0<qa.length?", ":"")+qa);h+=(X?"var rv = ":"")+"invoker(fn"+(0<qa.length?", ":"")+qa+");\n";
if(H)h+="runDestructors(destructors);\n";else for(q=E?1:2;q<d.length;++q)y=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==d[q].Nb&&(h+=y+"_dtor("+y+"); // "+d[q].name+"\n",B.push(y+"_dtor"),m.push(d[q].Nb));X&&(h+="var ret = retType.fromWireType(rv);\nreturn ret;\n");B.push(h+"}\n");d=zc(B).apply(null,m);q=b-1;if(!l.hasOwnProperty(c))throw new pc("Replacing nonexistant public symbol");void 0!==l[c].Mb&&void 0!==q?l[c].Mb[q]=d:(l[c]=d,l[c].uc=q);return[]})},j:function(a,b,c,d,f){function g(a){return a}
b=V(b);-1===f&&(f=4294967295);var h=rc(c);if(0===d){var m=32-8*c;g=function(a){return a<<m>>>m}}var x=-1!=b.indexOf("unsigned");U(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+xc(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+xc(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return x?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Jc(b,
h,0!==d),Nb:null})},i:function(a,b,c){function d(a){a>>=2;var b=F;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);U(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Bc:!0})},E:function(a,b){b=V(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(a){var b=F[a>>2];if(c){var d=D[a+4+b],h=0;0!=d&&(h=d,D[a+4+b]=0);var m=a+4;for(d=0;d<=b;++d){var x=a+4+d;if(0==D[x]){m=ua(m);if(void 0===
p)var p=m;else p+=String.fromCharCode(0),p+=m;m=x+1}}0!=h&&(D[a+4+b]=h)}else{p=Array(b);for(d=0;d<b;++d)p[d]=String.fromCharCode(D[a+4+d]);p=p.join("")}Z(a);return p},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||W("Cannot pass non-string to std::string");var f=(c&&d?function(){return wa(b)}:function(){return b.length})(),m=ra(4+f+1);F[m>>2]=f;if(c&&d)va(b,D,m+4,
f+1);else if(d)for(d=0;d<f;++d){var x=b.charCodeAt(d);255<x&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));D[m+4+d]=x}else for(d=0;d<f;++d)D[m+4+d]=b[d];null!==a&&a.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:ic,Nb:function(a){Z(a)}})},aa:function(a,b,c){c=V(c);if(2===b){var d=function(){return za};var f=1}else 4===b&&(d=function(){return F},f=2);U(a,{name:c,fromWireType:function(a){for(var b=d(),c=F[a>>2],g=Array(c),p=a+4>>f,u=0;u<c;++u)g[u]=String.fromCharCode(b[p+
u]);Z(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,p=ra(4+h*b);F[p>>2]=h;for(var u=p+4>>f,y=0;y<h;++y)g[u+y]=c.charCodeAt(y);null!==a&&a.push(Z,p);return p},argPackAdvance:8,readValueFromPointer:ic,Nb:function(a){Z(a)}})},$:function(a,b,c,d,f,g){fc[a]={name:V(b),Ec:Ec(c,d),Fc:Ec(f,g),lc:[]}},D:function(a,b,c,d,f,g,h,m,x,p){fc[a].lc.push({vc:V(b),Ac:c,yc:Ec(d,f),zc:g,Jc:h,Ic:Ec(m,x),Kc:p})},_:function(a,b){b=V(b);U(a,{Uc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
Z:vc,Y:function(a){4<a&&(Y[a].fc+=1)},X:function(a,b){var c=kc[a];void 0===c&&W("_emval_take_value has unknown type "+Gc(a));a=c.readValueFromPointer(b);return wc(a)},b:function(){l.abort()},W:Kc,V:function(a,b){if(0===a)a=Date.now();else if(1===a&&(t||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Lc();else return gb(22),-1;A[b>>2]=a/1E3|0;A[b+4>>2]=a%1E3*1E6|0;return 0},U:ka,T:function(a,b,c){D.set(D.subarray(b,b+c),a)},S:la,t:function(a){if(!l.noExitRuntime&&
(oa=!0,l.onExit))l.onExit(a);l.quit(a,new fa(a))},R:La,n:Nc,Q:function(a){var b=Date.now();A[a>>2]=b/1E3|0;A[a+4>>2]=b%1E3*1E3|0;return 0},B:function(a,b){a=new Date(1E3*A[a>>2]);A[b>>2]=a.getUTCSeconds();A[b+4>>2]=a.getUTCMinutes();A[b+8>>2]=a.getUTCHours();A[b+12>>2]=a.getUTCDate();A[b+16>>2]=a.getUTCMonth();A[b+20>>2]=a.getUTCFullYear()-1900;A[b+24>>2]=a.getUTCDay();A[b+36>>2]=0;A[b+32>>2]=0;A[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;A[b+40>>2]=3397248;return b},
e:Oc,h:function(a){return Oc(a)},P:Pc,g:function(a){return Pc(a)},f:Qc,m:function(a){return Qc(a)},s:function(a){var b=Rc.Hb[a];Rc.Hb.splice(a,1);ed(b)},z:Rc,O:Pa,r:function(a,b){Tc();a=new Date(1E3*A[a>>2]);A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);A[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;A[b+36>>2]=-(60*a.getTimezoneOffset());var d=
(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A[b+32>>2]=a;a=A[Xc()+(a?4:0)>>2];A[b+40>>2]=a;return b},N:function(a){Tc();var b=new Date(A[a+20>>2]+1900,A[a+16>>2],A[a+12>>2],A[a+8>>2],A[a+4>>2],A[a>>2],0),c=A[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(2E3,6,1)).getTimezoneOffset(),h=f.getTimezoneOffset(),m=Math.min(h,g);0>c?A[a+32>>2]=Number(g!=h&&m==d):0<c!=(m==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+
6E4*((0<c?m:g)-d)));A[a+24>>2]=b.getDay();A[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},x:function(a,b){var c=A[a>>2];a=A[a+4>>2];0!==b&&(A[b>>2]=0,A[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((ba||r)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},q:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,
b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-
1,11,30)}}function x(a){a=bd(new Date(a.Fb+1900,0,1),a.ac);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=h(m(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var p=A[d+40>>2];d={Oc:A[d>>2],Nc:A[d+4>>2],$b:A[d+8>>2],Tb:A[d+12>>2],Qb:A[d+16>>2],Fb:A[d+20>>2],tc:A[d+24>>2],ac:A[d+28>>2],Xc:A[d+32>>2],Mc:A[d+36>>2],Pc:p?ua(p):""};c=ua(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var u in p)c=c.replace(new RegExp(u,"g"),p[u]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),E="January February March April May June July August September October November December".split(" ");p={"%a":function(a){return y[a.tc].substring(0,3)},"%A":function(a){return y[a.tc]},"%b":function(a){return E[a.Qb].substring(0,3)},"%B":function(a){return E[a.Qb]},"%C":function(a){return g((a.Fb+1900)/100|0,2)},"%d":function(a){return g(a.Tb,
2)},"%e":function(a){return f(a.Tb,2," ")},"%g":function(a){return x(a).toString().substring(2)},"%G":function(a){return x(a)},"%H":function(a){return g(a.$b,2)},"%I":function(a){a=a.$b;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Tb+Zc(Yc(a.Fb+1900)?$c:ad,a.Qb-1),3)},"%m":function(a){return g(a.Qb+1,2)},"%M":function(a){return g(a.Nc,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.$b&&12>a.$b?"AM":"PM"},"%S":function(a){return g(a.Oc,2)},"%t":function(){return"\t"},
"%u":function(a){return(new Date(a.Fb+1900,a.Qb+1,a.Tb,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Fb+1900,0,1),c=0===b.getDay()?b:bd(b,7-b.getDay());a=new Date(a.Fb+1900,a.Qb,a.Tb);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Zc(Yc(a.getFullYear())?$c:ad,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.Fb+1900,0,4)),c=m(new Date(a.Fb+1901,0,4)),d=bd(new Date(a.Fb+1900,0,1),a.ac);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<
a.Fb+1900?a.ac+32-b.getDate():a.ac+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Fb+1900,a.Qb+1,a.Tb,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Fb,0,1),c=1===b.getDay()?b:bd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Fb+1900,a.Qb,a.Tb);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Zc(Yc(a.getFullYear())?$c:ad,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.Fb+1900).toString().substring(2)},"%Y":function(a){return a.Fb+1900},"%z":function(a){a=
a.Mc;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Pc},"%%":function(){return"%"}};for(u in p)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),p[u](d)));u=nb(c,!1);if(u.length>b)return 0;C.set(u,a);return u.length-1},M:function(a){var b=Date.now()/1E3|0;a&&(A[a>>2]=b);return b},L:function(){w("OOM")},a:ja},buffer);l.asm=fd;l.___errno_location=function(){return l.asm.na.apply(null,arguments)};
var Hc=l.___getTypeName=function(){return l.asm.oa.apply(null,arguments)},Wc=l.__get_daylight=function(){return l.asm.pa.apply(null,arguments)},Vc=l.__get_timezone=function(){return l.asm.qa.apply(null,arguments)},Xc=l.__get_tzname=function(){return l.asm.ra.apply(null,arguments)},Z=l._free=function(){return l.asm.sa.apply(null,arguments)},ra=l._malloc=function(){return l.asm.ta.apply(null,arguments)},Za=l.globalCtors=function(){return l.asm.wb.apply(null,arguments)};
l.stackAlloc=function(){return l.asm.xb.apply(null,arguments)};var ed=l.stackRestore=function(){return l.asm.yb.apply(null,arguments)},Sc=l.stackSave=function(){return l.asm.zb.apply(null,arguments)};l.dynCall_dd=function(){return l.asm.ua.apply(null,arguments)};l.dynCall_did=function(){return l.asm.va.apply(null,arguments)};l.dynCall_didd=function(){return l.asm.wa.apply(null,arguments)};l.dynCall_fii=function(){return l.asm.xa.apply(null,arguments)};
l.dynCall_fiifi=function(){return l.asm.ya.apply(null,arguments)};l.dynCall_fiii=function(){return l.asm.za.apply(null,arguments)};l.dynCall_fiiii=function(){return l.asm.Aa.apply(null,arguments)};l.dynCall_fiiiiiiiiffii=function(){return l.asm.Ba.apply(null,arguments)};l.dynCall_i=function(){return l.asm.Ca.apply(null,arguments)};l.dynCall_ii=function(){return l.asm.Da.apply(null,arguments)};l.dynCall_iidiiii=function(){return l.asm.Ea.apply(null,arguments)};
l.dynCall_iii=function(){return l.asm.Fa.apply(null,arguments)};l.dynCall_iiifii=function(){return l.asm.Ga.apply(null,arguments)};l.dynCall_iiii=function(){return l.asm.Ha.apply(null,arguments)};l.dynCall_iiiii=function(){return l.asm.Ia.apply(null,arguments)};l.dynCall_iiiiii=function(){return l.asm.Ja.apply(null,arguments)};l.dynCall_iiiiiii=function(){return l.asm.Ka.apply(null,arguments)};l.dynCall_iiiiiiidiiddii=function(){return l.asm.La.apply(null,arguments)};
l.dynCall_iiiiiiii=function(){return l.asm.Ma.apply(null,arguments)};l.dynCall_iiiiiiiiii=function(){return l.asm.Na.apply(null,arguments)};l.dynCall_iiiiiiiiiiiiiifii=function(){return l.asm.Oa.apply(null,arguments)};l.dynCall_iiiiij=function(){return l.asm.Pa.apply(null,arguments)};l.dynCall_iiiji=function(){return l.asm.Qa.apply(null,arguments)};l.dynCall_iiijjji=function(){return l.asm.Ra.apply(null,arguments)};l.dynCall_iij=function(){return l.asm.Sa.apply(null,arguments)};
l.dynCall_ijiii=function(){return l.asm.Ta.apply(null,arguments)};l.dynCall_jii=function(){return l.asm.Ua.apply(null,arguments)};l.dynCall_jiiii=function(){return l.asm.Va.apply(null,arguments)};l.dynCall_jiiij=function(){return l.asm.Wa.apply(null,arguments)};l.dynCall_jiiji=function(){return l.asm.Xa.apply(null,arguments)};l.dynCall_jij=function(){return l.asm.Ya.apply(null,arguments)};l.dynCall_jiji=function(){return l.asm.Za.apply(null,arguments)};
l.dynCall_v=function(){return l.asm._a.apply(null,arguments)};l.dynCall_vi=function(){return l.asm.$a.apply(null,arguments)};l.dynCall_vii=function(){return l.asm.ab.apply(null,arguments)};l.dynCall_viidi=function(){return l.asm.bb.apply(null,arguments)};l.dynCall_viifi=function(){return l.asm.cb.apply(null,arguments)};l.dynCall_viii=function(){return l.asm.db.apply(null,arguments)};l.dynCall_viiif=function(){return l.asm.eb.apply(null,arguments)};
l.dynCall_viiiff=function(){return l.asm.fb.apply(null,arguments)};l.dynCall_viiii=function(){return l.asm.gb.apply(null,arguments)};l.dynCall_viiiif=function(){return l.asm.hb.apply(null,arguments)};l.dynCall_viiiifii=function(){return l.asm.ib.apply(null,arguments)};l.dynCall_viiiii=function(){return l.asm.jb.apply(null,arguments)};l.dynCall_viiiiii=function(){return l.asm.kb.apply(null,arguments)};l.dynCall_viiiiiiff=function(){return l.asm.lb.apply(null,arguments)};
l.dynCall_viiiiiifi=function(){return l.asm.mb.apply(null,arguments)};l.dynCall_viiiiiii=function(){return l.asm.nb.apply(null,arguments)};l.dynCall_viiiiiiifi=function(){return l.asm.ob.apply(null,arguments)};l.dynCall_viiiiiiii=function(){return l.asm.pb.apply(null,arguments)};l.dynCall_viiiiiiiii=function(){return l.asm.qb.apply(null,arguments)};l.dynCall_viiiiiiiiii=function(){return l.asm.rb.apply(null,arguments)};l.dynCall_viiiiiiiiiii=function(){return l.asm.sb.apply(null,arguments)};
l.dynCall_viiiiiiiiiiii=function(){return l.asm.tb.apply(null,arguments)};l.dynCall_viiiiiiiiiiiiii=function(){return l.asm.ub.apply(null,arguments)};l.dynCall_viiijj=function(){return l.asm.vb.apply(null,arguments)};l.asm=fd;l.then=function(a){if(l.calledRun)a(l);else{var b=l.onRuntimeInitialized;l.onRuntimeInitialized=function(){b&&b();a(l)}}return l};function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();
fa.prototype.constructor=fa;Sa=function gd(){l.calledRun||hd();l.calledRun||(Sa=gd)};
function hd(){function a(){if(!l.calledRun&&(l.calledRun=!0,!oa)){Ja||(Ja=!0,l.noFSInit||$b||($b=!0,Zb(),l.stdin=l.stdin,l.stdout=l.stdout,l.stderr=l.stderr,l.stdin?bc("stdin",l.stdin):Rb("/dev/tty","/dev/stdin"),l.stdout?bc("stdout",null,l.stdout):Rb("/dev/tty","/dev/stdout"),l.stderr?bc("stderr",null,l.stderr):Rb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin","r"),Ub("/dev/stdout","w"),Ub("/dev/stderr","w")),Ea(Ga));zb=!1;Ea(Ha);if(l.onRuntimeInitialized)l.onRuntimeInitialized();if(l.postRun)for("function"==
typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();Ia.unshift(a)}Ea(Ia)}}if(!(0<Qa)){if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)Ka();Ea(Fa);0<Qa||l.calledRun||(l.setStatus?(l.setStatus("Running..."),setTimeout(function(){setTimeout(function(){l.setStatus("")},1);a()},1)):a())}}l.run=hd;
function w(a){if(l.onAbort)l.onAbort(a);void 0!==a?(ha(a),z(a),a=JSON.stringify(a)):a="";oa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}l.abort=w;if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.pop()();l.noExitRuntime=!0;hd();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    