
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var f;f||(f=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa=!1;
f.convert=function(a,b){if(!aa){k("/data");var c=l("/data",{zc:!0});if(null===c.node)throw new r(44);if(!t(c.node.mode))throw new r(54);var d=ba(c.node,"x");if(d)throw new r(d);ca=c.path;aa=!0}c=da("input","w+");ea(c,a,0,a.length);fa(c);ha(["-hide_banner","-nostdin","-loglevel",b.verbose?"verbose":"quiet","-i","input","-vcodec",b.videoEncoder,"-acodec",b.audioEncoder,"-f",b.outputFormat].concat(b.extraOptions||[]).concat(["output"]));a=l("/data").node.Xb.output.Xb;Array.isArray(a)||a instanceof ArrayBuffer?
a=new Uint8Array(a):a?a instanceof Uint8Array||(a=new Uint8Array(a.buffer)):a=new Uint8Array(0);return a};var ja={},ka;for(ka in f)f.hasOwnProperty(ka)&&(ja[ka]=f[ka]);var la=[],ma="./this.program";function na(a,b){throw b;}var oa=!1,pa=!1;oa="object"===typeof window;pa="function"===typeof importScripts;var u="",qa;
if(oa||pa)pa?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",pa&&(qa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ra=f.print||console.log.bind(console),v=f.printErr||console.warn.bind(console);for(ka in ja)ja.hasOwnProperty(ka)&&(f[ka]=ja[ka]);ja=null;f.arguments&&(la=f.arguments);
f.thisProgram&&(ma=f.thisProgram);f.quit&&(na=f.quit);function sa(a){var b=w[ta>>2];a=b+a+15&-16;a>ua()&&z();w[ta>>2]=a;return b}var va={"f64-rem":function(a,b){return a%b},"debugger":function(){}},wa;f.wasmBinary&&(wa=f.wasmBinary);var xa;f.noExitRuntime&&(xa=f.noExitRuntime);"object"!==typeof WebAssembly&&v("no native wasm support detected");var ya,za=new WebAssembly.Table({initial:7445,maximum:7445,element:"anyfunc"}),Aa=!1;
function Ba(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=Ca(Math.max(c,1));if(b){a=d;0==(d&3)||z("Assertion failed: undefined");for(b=d+(c&-4);a<b;a+=4)w[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}var Da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ea(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Fa(a){return a?Ea(B,a,void 0):""}
function Ga(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ia(a){var b=Ha(a)+1,c=Ja(b);Ga(a,A,c,b);return c}function Ka(a){0<a%65536&&(a+=65536-a%65536);return a}var La,A,B,Ma,Na,w,D,Oa,Pa;
function Qa(a){La=a;f.HEAP8=A=new Int8Array(a);f.HEAP16=Ma=new Int16Array(a);f.HEAP32=w=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=Na=new Uint16Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=Oa=new Float32Array(a);f.HEAPF64=Pa=new Float64Array(a)}var ta=3986352,Ra=f.TOTAL_MEMORY||16777216;f.wasmMemory?ya=f.wasmMemory:ya=new WebAssembly.Memory({initial:Ra/65536});ya&&(La=ya.buffer);Ra=La.byteLength;Qa(La);w[ta>>2]=9229424;
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.wd;"number"===typeof c?void 0===b.Vc?f.dynCall_v(c):f.dynCall_vi(c,b.Vc):c(void 0===b.Vc?null:b.Vc)}}}var Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=f.preRun.shift();Ta.unshift(a)}var Za=Math.abs,$a=Math.ceil,ab=Math.floor,bb=Math.min,cb=Math.trunc,db=0,eb=null,fb=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);ra(a);v(a);Aa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}function gb(){var a=hb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var hb="convert.wasm";if(!gb()){var ib=hb;hb=f.locateFile?f.locateFile(ib,u):u+ib}
function jb(){try{if(wa)return new Uint8Array(wa);if(qa)return qa(hb);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}function kb(){return wa||!oa&&!pa||"function"!==typeof fetch?new Promise(function(a){a(jb())}):fetch(hb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+hb+"'";return a.arrayBuffer()}).catch(function(){return jb()})}
f.asm=function(){function a(a){f.asm=a.exports;db--;f.monitorRunDependencies&&f.monitorRunDependencies(db);0==db&&(null!==eb&&(clearInterval(eb),eb=null),fb&&(a=fb,fb=null,a()))}function b(b){a(b.instance)}function c(a){return kb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+a);z(a)})}var d={env:lb,wasi_unstable:lb,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:va};db++;f.monitorRunDependencies&&f.monitorRunDependencies(db);
if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(wa||"function"!==typeof WebAssembly.instantiateStreaming||gb()||"function"!==typeof fetch)return c(b);fetch(hb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");c(b)})})})();return{}};var E,F;Ua.push({wd:function(){mb()}});
var G={};
function nb(a){if(nb.jc){var b=w[a>>2];var c=w[b>>2]}else nb.jc=!0,G.USER="web_user",G.LOGNAME="web_user",G.PATH="/",G.PWD="/",G.HOME="/home/web_user",G.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",G._=ma,c=Xa?Ca(1024):sa(1024),b=Xa?Ca(256):sa(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,e;for(e in G)if("string"===typeof G[e]){var g=e+"="+G[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<
a.length;e++){d=g=a[e];for(var h=c,m=0;m<d.length;++m)A[h++>>0]=d.charCodeAt(m);A[h>>0]=0;w[b+4*e>>2]=c;c+=g.length+1}w[b+4*a.length>>2]=0}function ob(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function pb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ob(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function qb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function rb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function sb(){f.___errno_location&&(w[f.___errno_location()>>2]=28)}
function tb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:ca;if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ob(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function ub(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=tb(a).substr(1);b=tb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var xb=[];function yb(a,b){xb[a]={input:[],fc:[],Bc:b};zb(a,Ab)}
var Ab={open:function(a){var b=xb[a.node.Fc];if(!b)throw new r(43);a.ec=b;a.seekable=!1},close:function(a){a.ec.Bc.flush(a.ec)},flush:function(a){a.ec.Bc.flush(a.ec)},read:function(a,b,c,d){if(!a.ec||!a.ec.Bc.hd)throw new r(60);for(var e=0,g=0;g<d;g++){try{var h=a.ec.Bc.hd(a.ec)}catch(m){throw new r(29);}if(void 0===h&&0===e)throw new r(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.ec||!a.ec.Bc.Yc)throw new r(60);try{for(var e=
0;e<d;e++)a.ec.Bc.Yc(a.ec,b[c+e])}catch(g){throw new r(29);}d&&(a.node.timestamp=Date.now());return e}},Cb={hd:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Bb(b,!0)}return a.input.shift()},Yc:function(a,b){null===b||10===b?(ra(Ea(a.fc,0)),a.fc=[]):0!=b&&a.fc.push(b)},flush:function(a){a.fc&&0<a.fc.length&&
(ra(Ea(a.fc,0)),a.fc=[])}},Db={Yc:function(a,b){null===b||10===b?(v(Ea(a.fc,0)),a.fc=[]):0!=b&&a.fc.push(b)},flush:function(a){a.fc&&0<a.fc.length&&(v(Ea(a.fc,0)),a.fc=[])}},H={pc:null,lc:function(){return H.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new r(63);H.pc||(H.pc={dir:{node:{oc:H.Yb.oc,qc:H.Yb.qc,Dc:H.Yb.Dc,Mc:H.Yb.Mc,Oc:H.Yb.Oc,Uc:H.Yb.Uc,Pc:H.Yb.Pc,Nc:H.Yb.Nc,Qc:H.Yb.Qc},stream:{xc:H.Zb.xc}},file:{node:{oc:H.Yb.oc,qc:H.Yb.qc},
stream:{xc:H.Zb.xc,read:H.Zb.read,write:H.Zb.write,bd:H.Zb.bd,jd:H.Zb.jd,ld:H.Zb.ld}},link:{node:{oc:H.Yb.oc,qc:H.Yb.qc,Gc:H.Yb.Gc},stream:{}},cd:{node:{oc:H.Yb.oc,qc:H.Yb.qc},stream:Eb}});c=Fb(a,b,c,d);t(c.mode)?(c.Yb=H.pc.dir.node,c.Zb=H.pc.dir.stream,c.Xb={}):32768===(c.mode&61440)?(c.Yb=H.pc.file.node,c.Zb=H.pc.file.stream,c.cc=0,c.Xb=null):40960===(c.mode&61440)?(c.Yb=H.pc.link.node,c.Zb=H.pc.link.stream):8192===(c.mode&61440)&&(c.Yb=H.pc.cd.node,c.Zb=H.pc.cd.stream);c.timestamp=Date.now();a&&
(a.Xb[b]=c);return c},Yd:function(a){if(a.Xb&&a.Xb.subarray){for(var b=[],c=0;c<a.cc;++c)b.push(a.Xb[c]);return b}return a.Xb},Zd:function(a){return a.Xb?a.Xb.subarray?a.Xb.subarray(0,a.cc):new Uint8Array(a.Xb):new Uint8Array},ed:function(a,b){var c=a.Xb?a.Xb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Xb,a.Xb=new Uint8Array(b),0<a.cc&&a.Xb.set(c.subarray(0,a.cc),0))},Md:function(a,b){if(a.cc!=b)if(0==b)a.Xb=null,a.cc=0;else{if(!a.Xb||a.Xb.subarray){var c=a.Xb;
a.Xb=new Uint8Array(new ArrayBuffer(b));c&&a.Xb.set(c.subarray(0,Math.min(b,a.cc)))}else if(a.Xb||(a.Xb=[]),a.Xb.length>b)a.Xb.length=b;else for(;a.Xb.length<b;)a.Xb.push(0);a.cc=b}},Yb:{oc:function(a){var b={};b.td=8192===(a.mode&61440)?a.id:1;b.Wc=a.id;b.mode=a.mode;b.Hd=1;b.uid=0;b.Cd=0;b.Fc=a.Fc;t(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.cc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.od=new Date(a.timestamp);b.Gd=new Date(a.timestamp);b.sd=new Date(a.timestamp);b.pd=4096;
b.qd=Math.ceil(b.size/b.pd);return b},qc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&H.Md(a,b.size)},Dc:function(){throw Gb[44];},Mc:function(a,b,c,d){return H.createNode(a,b,c,d)},Oc:function(a,b,c){if(t(a.mode)){try{var d=I(b,c)}catch(g){}if(d)for(var e in d.Xb)throw new r(55);}delete a.parent.Xb[a.name];a.name=c;b.Xb[c]=a;a.parent=b},Uc:function(a,b){delete a.Xb[b]},Pc:function(a,b){var c=I(a,b),d;for(d in c.Xb)throw new r(55);
delete a.Xb[b]},Nc:function(a){var b=[".",".."],c;for(c in a.Xb)a.Xb.hasOwnProperty(c)&&b.push(c);return b},Qc:function(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},Gc:function(a){if(40960!==(a.mode&61440))throw new r(28);return a.link}},Zb:{read:function(a,b,c,d,e){var g=a.node.Xb;if(e>=a.node.cc)return 0;a=Math.min(a.node.cc-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.Xb||a.Xb.subarray)){if(g)return a.Xb=b.subarray(c,c+d),a.cc=d;if(0===a.cc&&0===e)return a.Xb=new Uint8Array(b.subarray(c,c+d)),a.cc=d;if(e+d<=a.cc)return a.Xb.set(b.subarray(c,c+d),e),d}H.ed(a,e+d);if(a.Xb.subarray&&b.subarray)a.Xb.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Xb[e+g]=b[c+g];a.cc=Math.max(a.cc,e+d);return d},xc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.cc);if(0>b)throw new r(28);return b},bd:function(a,b,c){H.ed(a.node,
b+c);a.node.cc=Math.max(a.node.cc,b+c)},jd:function(a,b,c,d,e,g,h){if(32768!==(a.node.mode&61440))throw new r(43);c=a.node.Xb;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.cc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==A.buffer;d=Ca(d);if(!d)throw new r(48);(e?A:b).set(c,d)}else a=!1,d=c.byteOffset;return{ac:d,Xd:a}},ld:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new r(43);if(e&2)return 0;H.Zb.write(a,b,0,d,c,!1);return 0}}},Hb=
null,Ib={},Jb=[],Kb=1,Lb=null,ca="/",Mb=!0,L={},r=null,Gb={};
function l(a,b){a=tb(ca,a);b=b||{};if(!a)return{path:"",node:null};var c={gd:!0,$c:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$c)throw new r(32);a=ob(a.split("/").filter(function(a){return!!a}),!1);var e=Hb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=I(e,a[d]);c=pb(c+"/"+a[d]);e.uc&&(!g||g&&b.gd)&&(e=e.uc.root);if(!g||b.zc)for(g=0;40960===(e.mode&61440);)if(e=Nb(c),c=tb(qb(c),e),e=l(c,{$c:b.$c}).node,40<g++)throw new r(32);}return{path:c,node:e}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.lc.kd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Lb.length}function Qb(a){var b=Pb(a.parent.id,a.name);a.Ac=Lb[b];Lb[b]=a}function Rb(a){var b=Pb(a.parent.id,a.name);if(Lb[b]===a)Lb[b]=a.Ac;else for(b=Lb[b];b;){if(b.Ac===a){b.Ac=a.Ac;break}b=b.Ac}}
function I(a,b){var c;if(c=(c=ba(a,"x"))?c:a.Yb.Dc?0:2)throw new r(c,a);for(c=Lb[Pb(a.id,b)];c;c=c.Ac){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Yb.Dc(a,b)}
function Fb(a,b,c,d){Sb||(Sb=function(a,b,c,d){a||(a=this);this.parent=a;this.lc=a.lc;this.uc=null;this.id=Kb++;this.name=b;this.mode=c;this.Yb={};this.Zb={};this.Fc=d},Sb.prototype={},Object.defineProperties(Sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Sb(a,b,c,d);Qb(a);return a}
function t(a){return 16384===(a&61440)}var Tb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ba(a,b){if(Mb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Vb(a,b){try{return I(a,b),20}catch(c){}return ba(a,"wx")}
function Wb(a,b,c){try{var d=I(a,b)}catch(e){return e.bc}if(a=ba(a,"wx"))return a;if(c){if(!t(d.mode))return 54;if(d===d.parent||Ob(d)===ca)return 10}else if(t(d.mode))return 31;return 0}function Xb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Jb[a])return a;throw new r(33);}
function Yb(a,b){Zb||(Zb=function(){},Zb.prototype={},Object.defineProperties(Zb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Zb,d;for(d in a)c[d]=a[d];a=c;b=Xb(b);a.sc=b;return Jb[b]=a}var Eb={open:function(a){a.Zb=Ib[a.node.Fc].Zb;a.Zb.open&&a.Zb.open(a)},xc:function(){throw new r(70);}};function zb(a,b){Ib[a]={Zb:b}}
function $b(a,b){var c="/"===b,d=!b;if(c&&Hb)throw new r(10);if(!c&&!d){var e=l(b,{gd:!1});b=e.path;e=e.node;if(e.uc)throw new r(10);if(!t(e.mode))throw new r(54);}b={type:a,be:{},kd:b,Fd:[]};a=a.lc(b);a.lc=b;b.root=a;c?Hb=a:e&&(e.uc=b,e.lc&&e.lc.Fd.push(b))}function ac(a,b,c){var d=l(a,{parent:!0}).node;a=rb(a);if(!a||"."===a||".."===a)throw new r(28);var e=Vb(d,a);if(e)throw new r(e);if(!d.Yb.Mc)throw new r(63);return d.Yb.Mc(d,a,b,c)}function k(a){ac(a,16895,0)}
function bc(a,b,c){"undefined"===typeof c&&(c=b,b=438);ac(a,b|8192,c)}function cc(a,b){if(!tb(a))throw new r(44);var c=l(b,{parent:!0}).node;if(!c)throw new r(44);b=rb(b);var d=Vb(c,b);if(d)throw new r(d);if(!c.Yb.Qc)throw new r(63);c.Yb.Qc(c,b,a)}function Nb(a){a=l(a).node;if(!a)throw new r(44);if(!a.Yb.Gc)throw new r(28);return tb(Ob(a.parent),a.Yb.Gc(a))}function dc(a,b){a=l(a,{zc:!b}).node;if(!a)throw new r(44);if(!a.Yb.oc)throw new r(63);return a.Yb.oc(a)}function ec(a){return dc(a,!0)}
function da(a,b,c,d){if(""===a)throw new r(44);if("string"===typeof b){var e=Tb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=pb(a);try{g=l(a,{zc:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(g){if(b&128)throw new r(20);}else g=ac(a,c,0),e=!0;if(!g)throw new r(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!t(g.mode))throw new r(54);if(!e&&(c=g?40960===(g.mode&61440)?32:t(g.mode)&&
("r"!==Ub(b)||b&512)?31:ba(g,Ub(b)):44))throw new r(c);if(b&512){c=g;var h;"string"===typeof c?h=l(c,{zc:!0}).node:h=c;if(!h.Yb.qc)throw new r(63);if(t(h.mode))throw new r(31);if(32768!==(h.mode&61440))throw new r(28);if(c=ba(h,"w"))throw new r(c);h.Yb.qc(h,{size:0,timestamp:Date.now()})}b&=-641;d=Yb({node:g,path:Ob(g),flags:b,seekable:!0,position:0,Zb:g.Zb,Wd:[],error:!1},d);d.Zb.open&&d.Zb.open(d);!f.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{L.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),L.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function fa(a){if(null===a.sc)throw new r(8);a.wc&&(a.wc=null);try{a.Zb.close&&a.Zb.close(a)}catch(b){throw b;}finally{Jb[a.sc]=null}a.sc=null}
function hc(a,b,c){if(null===a.sc)throw new r(8);if(!a.seekable||!a.Zb.xc)throw new r(70);if(0!=c&&1!=c&&2!=c)throw new r(28);a.position=a.Zb.xc(a,b,c);a.Wd=[];return a.position}
function ic(a,b,c,d){var e=A;if(0>c||0>d)throw new r(28);if(null===a.sc)throw new r(8);if(1===(a.flags&2097155))throw new r(8);if(t(a.node.mode))throw new r(31);if(!a.Zb.read)throw new r(28);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new r(70);b=a.Zb.read(a,e,b,c,d);g||(a.position+=b);return b}
function ea(a,b,c,d,e){if(0>d||0>e)throw new r(28);if(null===a.sc)throw new r(8);if(0===(a.flags&2097155))throw new r(8);if(t(a.node.mode))throw new r(31);if(!a.Zb.write)throw new r(28);a.flags&1024&&hc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new r(70);b=a.Zb.write(a,b,c,d,e,void 0);g||(a.position+=b);try{if(a.path&&L.onWriteToFile)L.onWriteToFile(a.path)}catch(h){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+h.message)}return b}
function jc(){r||(r=function(a,b){this.node=b;this.Nd=function(a){this.bc=a};this.Nd(a);this.message="FS error"},r.prototype=Error(),r.prototype.constructor=r,[44].forEach(function(a){Gb[a]=new r(a);Gb[a].stack="<generic error, no stack>"}))}var kc;function lc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function mc(a,b,c){a=pb("/dev/"+a);var d=lc(!!b,!!c);nc||(nc=64);var e=nc++<<8|0;zb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,h=0;h<e;h++){try{var m=b()}catch(C){throw new r(29);}if(void 0===m&&0===g)throw new r(6);if(null===m||void 0===m)break;g++;c[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(p){throw new r(29);}e&&(a.node.timestamp=Date.now());return g}});
bc(a,d,e)}var nc,M={},Sb,Zb,fc;
function oc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&pb(b)!==pb(Ob(e.node)))return-54;throw e;}w[c>>2]=d.td;w[c+4>>2]=0;w[c+8>>2]=d.Wc;w[c+12>>2]=d.mode;w[c+16>>2]=d.Hd;w[c+20>>2]=d.uid;w[c+24>>2]=d.Cd;w[c+28>>2]=d.Fc;w[c+32>>2]=0;F=[d.size>>>0,(E=d.size,1<=+Za(E)?0<E?(bb(+ab(E/4294967296),4294967295)|0)>>>0:~~+$a((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+40>>2]=F[0];w[c+44>>2]=F[1];w[c+48>>2]=4096;w[c+52>>2]=d.qd;w[c+56>>2]=d.od.getTime()/1E3|0;w[c+60>>2]=0;w[c+64>>2]=d.Gd.getTime()/1E3|0;w[c+68>>
2]=0;w[c+72>>2]=d.sd.getTime()/1E3|0;w[c+76>>2]=0;F=[d.Wc>>>0,(E=d.Wc,1<=+Za(E)?0<E?(bb(+ab(E/4294967296),4294967295)|0)>>>0:~~+$a((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+80>>2]=F[0];w[c+84>>2]=F[1];return 0}var N=0;function O(){N+=4;return w[N-4>>2]}function pc(){return Fa(O())}function Q(a){void 0===a&&(a=O());a=Jb[a];if(!a)throw new r(8);return a}function qc(a){try{var b=Q(a);fa(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof r||z(c),c.bc}}
function rc(a,b){try{var c=Q(a);A[b>>0]=c.ec?2:t(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof r||z(d),d.bc}}function sc(a,b,c,d){try{a:{for(var e=Q(a),g=a=0;g<c;g++){var h=w[b+(8*g+4)>>2],m=ic(e,w[b+8*g>>2],h,void 0);if(0>m){var q=-1;break a}a+=m;if(m<h)break}q=a}w[d>>2]=q;return 0}catch(n){return"undefined"!==typeof M&&n instanceof r||z(n),n.bc}}
function tc(a,b,c,d,e){try{var g=Q(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;hc(g,a,d);F=[g.position>>>0,(E=g.position,1<=+Za(E)?0<E?(bb(+ab(E/4294967296),4294967295)|0)>>>0:~~+$a((E-+(~~E>>>0))/4294967296)>>>0:0)];w[e>>2]=F[0];w[e+4>>2]=F[1];g.wc&&0===a&&0===d&&(g.wc=null);return 0}catch(h){return"undefined"!==typeof M&&h instanceof r||z(h),h.bc}}
function uc(a,b,c,d){try{a:{for(var e=Q(a),g=a=0;g<c;g++){var h=ea(e,A,w[b+8*g>>2],w[b+(8*g+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}w[d>>2]=m;return 0}catch(q){return"undefined"!==typeof M&&q instanceof r||z(q),q.bc}}var vc={};function wc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function xc(a){return this.fromWireType(D[a>>2])}var yc={},zc={},Ac={};function Bc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Cc(a,b){a=Bc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Dc(a){var b=Error,c=Cc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Ec=void 0;function Fc(a){throw new Ec(a);}function R(a,b,c){function d(b){b=c(b);b.length!==a.length&&Fc("Mismatched type converter count");for(var d=0;d<a.length;++d)S(a[d],b[d])}a.forEach(function(a){Ac[a]=b});var e=Array(b.length),g=[],h=0;b.forEach(function(a,b){zc.hasOwnProperty(a)?e[b]=zc[a]:(g.push(a),yc.hasOwnProperty(a)||(yc[a]=[]),yc[a].push(function(){e[b]=zc[a];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function Gc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Hc=void 0;function T(a){for(var b="";B[a];)b+=Hc[B[a++]];return b}var Ic=void 0;function U(a){throw new Ic(a);}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(zc.hasOwnProperty(a)){if(c.Dd)return;U("Cannot register type '"+d+"' twice")}zc[a]=b;delete Ac[a];yc.hasOwnProperty(a)&&(b=yc[a],delete yc[a],b.forEach(function(a){a()}))}function Jc(a){return{count:a.count,yc:a.yc,Ec:a.Ec,ac:a.ac,dc:a.dc,ic:a.ic,mc:a.mc}}
function Kc(a){U(a.Wb.dc.$b.name+" instance already deleted")}var Lc=!1;function Mc(){}function Nc(a){--a.count.value;0===a.count.value&&(a.ic?a.mc.rc(a.ic):a.dc.$b.rc(a.ac))}
function Oc(a){if("undefined"===typeof FinalizationGroup)return Oc=function(a){return a},a;Lc=new FinalizationGroup(function(a){for(var b=a.next();!b.done;b=a.next())b=b.value,b.ac?Nc(b):console.warn("object already deleted: "+b.ac)});Oc=function(a){Lc.register(a,a.Wb,a.Wb);return a};Mc=function(a){Lc.unregister(a.Wb)};return Oc(a)}var Pc=void 0,Qc=[];function Rc(){for(;Qc.length;){var a=Qc.pop();a.Wb.yc=!1;a["delete"]()}}function Sc(){}var Tc={};
function Uc(a,b,c){if(void 0===a[b].gc){var d=a[b];a[b]=function(){a[b].gc.hasOwnProperty(arguments.length)||U("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].gc+")!");return a[b].gc[arguments.length].apply(this,arguments)};a[b].gc=[];a[b].gc[d.Jc]=d}}
function Vc(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].gc&&void 0!==f[a].gc[c])&&U("Cannot register public name '"+a+"' twice"),Uc(f,a,a),f.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].gc[c]=b):(f[a]=b,void 0!==c&&(f[a].ae=c))}function Wc(a,b,c,d,e,g,h,m){this.name=a;this.constructor=b;this.tc=c;this.rc=d;this.nc=e;this.xd=g;this.Ic=h;this.ud=m;this.Kd=[]}
function Xc(a,b,c){for(;b!==c;)b.Ic||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ic(a),b=b.nc;return a}function Yc(a,b){if(null===b)return this.Xc&&U("null is not a valid "+this.name),0;b.Wb||U('Cannot pass "'+Zc(b)+'" as a '+this.name);b.Wb.ac||U("Cannot pass deleted object as a pointer of type "+this.name);return Xc(b.Wb.ac,b.Wb.dc.$b,this.$b)}
function $c(a,b){if(null===b){this.Xc&&U("null is not a valid "+this.name);if(this.Lc){var c=this.Zc();null!==a&&a.push(this.rc,c);return c}return 0}b.Wb||U('Cannot pass "'+Zc(b)+'" as a '+this.name);b.Wb.ac||U("Cannot pass deleted object as a pointer of type "+this.name);!this.Kc&&b.Wb.dc.Kc&&U("Cannot convert argument of type "+(b.Wb.mc?b.Wb.mc.name:b.Wb.dc.name)+" to parameter type "+this.name);c=Xc(b.Wb.ac,b.Wb.dc.$b,this.$b);if(this.Lc)switch(void 0===b.Wb.ic&&U("Passing raw pointer to smart pointer is illegal"),
this.Rd){case 0:b.Wb.mc===this?c=b.Wb.ic:U("Cannot convert argument of type "+(b.Wb.mc?b.Wb.mc.name:b.Wb.dc.name)+" to parameter type "+this.name);break;case 1:c=b.Wb.ic;break;case 2:if(b.Wb.mc===this)c=b.Wb.ic;else{var d=b.clone();c=this.Ld(c,ad(function(){d["delete"]()}));null!==a&&a.push(this.rc,c)}break;default:U("Unsupporting sharing policy")}return c}
function bd(a,b){if(null===b)return this.Xc&&U("null is not a valid "+this.name),0;b.Wb||U('Cannot pass "'+Zc(b)+'" as a '+this.name);b.Wb.ac||U("Cannot pass deleted object as a pointer of type "+this.name);b.Wb.dc.Kc&&U("Cannot convert argument of type "+b.Wb.dc.name+" to parameter type "+this.name);return Xc(b.Wb.ac,b.Wb.dc.$b,this.$b)}function cd(a,b,c){if(b===c)return a;if(void 0===c.nc)return null;a=cd(a,b,c.nc);return null===a?null:c.ud(a)}var dd={};
function ed(a,b){for(void 0===b&&U("ptr should not be undefined");a.nc;)b=a.Ic(b),a=a.nc;return dd[b]}function fd(a,b){b.dc&&b.ac||Fc("makeClassHandle requires ptr and ptrType");!!b.mc!==!!b.ic&&Fc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Oc(Object.create(a,{Wb:{value:b}}))}
function V(a,b,c,d){this.name=a;this.$b=b;this.Xc=c;this.Kc=d;this.Lc=!1;this.rc=this.Ld=this.Zc=this.md=this.Rd=this.Id=void 0;void 0!==b.nc?this.toWireType=$c:(this.toWireType=d?Yc:bd,this.kc=null)}function gd(a,b,c){f.hasOwnProperty(a)||Fc("Replacing nonexistant public symbol");void 0!==f[a].gc&&void 0!==c?f[a].gc[c]=b:(f[a]=b,f[a].Jc=c)}
function W(a,b){a=T(a);if(void 0!==f["FUNCTION_TABLE_"+a])var c=f["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=f["dynCall_"+a];void 0===c&&(c=f["dynCall_"+a.replace(/f/g,"d")],void 0===c&&U("No dynCall invoker for signature: "+a));for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
e+"};\n"))(c,b)}"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var hd=void 0;function id(a){a=jd(a);var b=T(a);X(a);return b}function kd(a,b){function c(a){e[a]||zc[a]||(Ac[a]?Ac[a].forEach(c):(d.push(a),e[a]=!0))}var d=[],e={};b.forEach(c);throw new hd(a+": "+d.map(id).join([", "]));}function ld(a,b){for(var c=[],d=0;d<a;d++)c.push(w[(b>>2)+d]);return c}
function md(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Cc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function nd(a,b,c,d,e){var g=b.length;2>g&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].kc){m=!0;break}var q="void"!==b[0].name,n="",p="";for(c=0;c<g-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Bc(a)+"("+n+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";m&&(a+="var destructors = [];\n");var y=m?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[U,d,e,wc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+y+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+y+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(q?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(m)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].kc&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",n.push(g+"_dtor"),d.push(b[c].kc));q&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return md(n).apply(null,d)}
function od(a,b,c){a instanceof Object||U(c+' with invalid "this": '+a);a instanceof b.$b.constructor||U(c+' incompatible with "this" of type '+a.constructor.name);a.Wb.ac||U("cannot call emscripten binding method "+c+" on deleted object");return Xc(a.Wb.ac,a.Wb.dc.$b,b.$b)}var pd=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function qd(a){4<a&&0===--Y[a].ad&&(Y[a]=void 0,pd.push(a))}
function ad(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=pd.length?pd.pop():Y.length;Y[b]={ad:1,value:a};return b}}function rd(a,b,c){switch(b){case 0:return function(a){return this.fromWireType((c?A:B)[a])};case 1:return function(a){return this.fromWireType((c?Ma:Na)[a>>1])};case 2:return function(a){return this.fromWireType((c?w:D)[a>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function sd(a,b){var c=zc[a];void 0===c&&U(b+" has unknown type "+id(a));return c}function Zc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function td(a,b){switch(b){case 2:return function(a){return this.fromWireType(Oa[a>>2])};case 3:return function(a){return this.fromWireType(Pa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ud(a,b,c){switch(b){case 0:return c?function(a){return A[a]}:function(a){return B[a]};case 1:return c?function(a){return Ma[a>>1]}:function(a){return Na[a>>1]};case 2:return c?function(a){return w[a>>2]}:function(a){return D[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function vd(){void 0===vd.start&&(vd.start=Date.now());return 1E3*(Date.now()-vd.start)|0}function wd(){z()}function ua(){return A.length}
function xd(a){if(0===a)return 0;a=Fa(a);if(!G.hasOwnProperty(a))return 0;xd.jc&&X(xd.jc);a=G[a];var b=Ha(a)+1,c=Ca(b);c&&Ga(a,A,c,b);xd.jc=c;return xd.jc}Ga("GMT",B,3986432,4);
function yd(a,b){a=new Date(1E3*w[a>>2]);w[b>>2]=a.getUTCSeconds();w[b+4>>2]=a.getUTCMinutes();w[b+8>>2]=a.getUTCHours();w[b+12>>2]=a.getUTCDate();w[b+16>>2]=a.getUTCMonth();w[b+20>>2]=a.getUTCFullYear()-1900;w[b+24>>2]=a.getUTCDay();w[b+36>>2]=0;w[b+32>>2]=0;w[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;w[b+40>>2]=3986432;return b}function zd(a){return Math.pow(2,a)}function Ad(a){return Math.log(a)/Math.LN10}function Bd(a){return Math.log(a)/Math.LN2}
function Cd(){Cd.jc||(Cd.jc=[]);Cd.jc.push(Dd());return Cd.jc.length-1}
function Ed(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Fd){Fd=!0;w[Gd()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);w[Hd()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),e=a(b);d=Ba(Bb(d));e=Ba(Bb(e));b.getTimezoneOffset()<c.getTimezoneOffset()?(w[Id()>>2]=d,w[Id()+4>>2]=e):(w[Id()>>2]=e,w[Id()+4>>2]=d)}}var Fd;
function Jd(a,b){Ed();a=new Date(1E3*w[a>>2]);w[b>>2]=a.getSeconds();w[b+4>>2]=a.getMinutes();w[b+8>>2]=a.getHours();w[b+12>>2]=a.getDate();w[b+16>>2]=a.getMonth();w[b+20>>2]=a.getFullYear()-1900;w[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);w[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;w[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;w[b+32>>2]=a;a=w[Id()+(a?4:0)>>2];
w[b+40>>2]=a;return b}function Kd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ld(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Md=[31,29,31,30,31,30,31,31,30,31,30,31],Nd=[31,28,31,30,31,30,31,31,30,31,30,31];function Od(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Kd(a.getFullYear())?Md:Nd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}jc();Lb=Array(4096);
$b(H,"/");k("/tmp");k("/home");k("/home/web_user");(function(){k("/dev");zb(259,{read:function(){return 0},write:function(a,b,e,g){return g}});bc("/dev/null",259);yb(1280,Cb);yb(1536,Db);bc("/dev/tty",1280);bc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){z("random_device")});mc("random",b);mc("urandom",b);k("/dev/shm");k("/dev/shm/tmp")})();k("/proc");k("/proc/self");
k("/proc/self/fd");$b({lc:function(){var a=Fb("/proc/self","fd",16895,73);a.Yb={Dc:function(a,c){var b=Jb[+c];if(!b)throw new r(8);a={parent:null,lc:{kd:"fake"},Yb:{Gc:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");Ec=f.InternalError=Dc("InternalError");for(var Pd=Array(256),Qd=0;256>Qd;++Qd)Pd[Qd]=String.fromCharCode(Qd);Hc=Pd;Ic=f.BindingError=Dc("BindingError");
Sc.prototype.isAliasOf=function(a){if(!(this instanceof Sc&&a instanceof Sc))return!1;var b=this.Wb.dc.$b,c=this.Wb.ac,d=a.Wb.dc.$b;for(a=a.Wb.ac;b.nc;)c=b.Ic(c),b=b.nc;for(;d.nc;)a=d.Ic(a),d=d.nc;return b===d&&c===a};Sc.prototype.clone=function(){this.Wb.ac||Kc(this);if(this.Wb.Ec)return this.Wb.count.value+=1,this;var a=Oc(Object.create(Object.getPrototypeOf(this),{Wb:{value:Jc(this.Wb)}}));a.Wb.count.value+=1;a.Wb.yc=!1;return a};
Sc.prototype["delete"]=function(){this.Wb.ac||Kc(this);this.Wb.yc&&!this.Wb.Ec&&U("Object already scheduled for deletion");Mc(this);Nc(this.Wb);this.Wb.Ec||(this.Wb.ic=void 0,this.Wb.ac=void 0)};Sc.prototype.isDeleted=function(){return!this.Wb.ac};Sc.prototype.deleteLater=function(){this.Wb.ac||Kc(this);this.Wb.yc&&!this.Wb.Ec&&U("Object already scheduled for deletion");Qc.push(this);1===Qc.length&&Pc&&Pc(Rc);this.Wb.yc=!0;return this};V.prototype.yd=function(a){this.md&&(a=this.md(a));return a};
V.prototype.dd=function(a){this.rc&&this.rc(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=xc;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.Lc?fd(this.$b.tc,{dc:this.Id,ac:c,mc:this,ic:a}):fd(this.$b.tc,{dc:this,ac:a})}var c=this.yd(a);if(!c)return this.dd(a),null;var d=ed(this.$b,c);if(void 0!==d){if(0===d.Wb.count.value)return d.Wb.ac=c,d.Wb.ic=a,d.clone();d=d.clone();this.dd(a);return d}d=this.$b.xd(c);d=Tc[d];if(!d)return b.call(this);d=this.Kc?d.rd:d.pointerType;var e=cd(c,this.$b,d.$b);return null===e?b.call(this):this.Lc?fd(d.$b.tc,{dc:d,ac:e,mc:this,ic:a}):fd(d.$b.tc,
{dc:d,ac:e})};f.getInheritedInstanceCount=function(){return Object.keys(dd).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in dd)dd.hasOwnProperty(b)&&a.push(dd[b]);return a};f.flushPendingDeletes=Rc;f.setDelayFunction=function(a){Pc=a;Qc.length&&Pc&&Pc(Rc)};hd=f.UnboundTypeError=Dc("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
"undefined"!==typeof dateNow?wd=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?wd=function(){return performance.now()}:wd=Date.now;function Bb(a,b){var c=Array(Ha(a)+1);a=Ga(a,c,0,c.length);b&&(c.length=a);return c}
var lb={c:function(a,b,c,d){z("Assertion failed: "+Fa(a)+", at: "+[b?Fa(b):"unknown filename",c,d?Fa(d):"unknown function"])},sa:nb,t:function(a){return Ca(a)},s:function(a){"uncaught_exception"in Rd?Rd.nd++:Rd.nd=1;throw a;},L:function(){},$:function(a,b){N=b;try{var c=pc(),d=l(c,{parent:!0}).node,e=rb(c),g=I(d,e),h=Wb(d,e,!1);if(h)throw new r(h);if(!d.Yb.Uc)throw new r(63);if(g.uc)throw new r(10);try{L.willDeletePath&&L.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+
c+"') threw an exception: "+m.message)}d.Yb.Uc(d,e);Rb(g);try{if(L.onDeletePath)L.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof M&&m instanceof r||z(m),-m.bc}},X:function(a,b){N=b;try{var c=O(),d=O(),e=O(),g=O();O();a=0;for(var h=d?w[d>>2]:0,m=d?w[d+4>>2]:0,q=e?w[e>>2]:0,n=e?w[e+4>>2]:0,p=g?w[g>>2]:0,y=g?w[g+4>>2]:0,C=b=0,x=0,ia=0,Z=0,J=0,Yd=(d?w[d>>2]:0)|(e?w[e>>2]:0)|(g?w[g>>2]:0),
Zd=(d?w[d+4>>2]:0)|(e?w[e+4>>2]:0)|(g?w[g+4>>2]:0),P=0;P<c;P++){var K=1<<P%32;if(32>P?Yd&K:Zd&K){var vb=Jb[P];if(!vb)throw new r(8);var wb=5;vb.Zb.Jd&&(wb=vb.Zb.Jd(vb));wb&1&&(32>P?h&K:m&K)&&(32>P?b|=K:C|=K,a++);wb&4&&(32>P?q&K:n&K)&&(32>P?x|=K:ia|=K,a++);wb&2&&(32>P?p&K:y&K)&&(32>P?Z|=K:J|=K,a++)}}d&&(w[d>>2]=b,w[d+4>>2]=C);e&&(w[e>>2]=x,w[e+4>>2]=ia);g&&(w[g>>2]=Z,w[g+4>>2]=J);return a}catch(gc){return"undefined"!==typeof M&&gc instanceof r||z(gc),-gc.bc}},F:function(a,b){N=b;try{var c=pc(),d=O();
return oc(dc,c,d)}catch(e){return"undefined"!==typeof M&&e instanceof r||z(e),-e.bc}},S:function(a,b){N=b;try{var c=pc(),d=O();return oc(ec,c,d)}catch(e){return"undefined"!==typeof M&&e instanceof r||z(e),-e.bc}},Ba:function(a,b){N=b;try{var c=Q(),d=O();return oc(dc,c.path,d)}catch(e){return"undefined"!==typeof M&&e instanceof r||z(e),-e.bc}},Aa:function(a,b){N=b;return 0},za:function(a,b){N=b;try{var c=Q(),d=O(),e=O();if(!c.wc){var g=l(c.path,{zc:!0}).node;if(!g.Yb.Nc)throw new r(54);var h=g.Yb.Nc(g);
c.wc=h}a=0;for(var m=hc(c,0,1),q=Math.floor(m/280);q<c.wc.length&&a+280<=e;){var n=c.wc[q];if("."===n[0]){var p=1;var y=4}else{var C=I(c.node,n);p=C.id;y=8192===(C.mode&61440)?2:t(C.mode)?4:40960===(C.mode&61440)?10:8}F=[p>>>0,(E=p,1<=+Za(E)?0<E?(bb(+ab(E/4294967296),4294967295)|0)>>>0:~~+$a((E-+(~~E>>>0))/4294967296)>>>0:0)];w[d+a>>2]=F[0];w[d+a+4>>2]=F[1];F=[280*(q+1)>>>0,(E=280*(q+1),1<=+Za(E)?0<E?(bb(+ab(E/4294967296),4294967295)|0)>>>0:~~+$a((E-+(~~E>>>0))/4294967296)>>>0:0)];w[d+a+8>>2]=F[0];
w[d+a+12>>2]=F[1];Ma[d+a+16>>1]=280;A[d+a+18>>0]=y;Ga(n,B,d+a+19,256);a+=280;q+=1}hc(c,280*q,0);return a}catch(x){return"undefined"!==typeof M&&x instanceof r||z(x),-x.bc}},E:function(a,b){N=b;try{var c=Q();switch(O()){case 0:var d=O();return 0>d?-28:da(c.path,c.flags,0,d).sc;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=O(),c.flags|=d,0;case 12:return d=O(),Ma[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return sb(),-1;default:return-28}}catch(e){return"undefined"!==
typeof M&&e instanceof r||z(e),-e.bc}},ya:function(a,b){N=b;try{var c=Q(),d=O(),e=O();return ic(c,d,e)}catch(g){return"undefined"!==typeof M&&g instanceof r||z(g),-g.bc}},xa:function(a,b){N=b;try{var c=pc();var d=O();if(d&-8)var e=-28;else{var g;(g=l(c,{zc:!0}).node)?(a="",d&4&&(a+="r"),d&2&&(a+="w"),d&1&&(a+="x"),e=a&&ba(g,a)?-2:0):e=-44}return e}catch(h){return"undefined"!==typeof M&&h instanceof r||z(h),-h.bc}},wa:function(a,b){N=b;try{O();O();O();var c=O();c&&(w[c>>2]=-1,w[c+4>>2]=-1,w[c+8>>2]=
-1,w[c+12>>2]=-1);return 0}catch(d){return"undefined"!==typeof M&&d instanceof r||z(d),-d.bc}},va:function(a,b){N=b;try{var c=pc(),d=pc(),e=qb(c),g=qb(d),h=rb(c),m=rb(d);try{var q=l(c,{parent:!0});var n=q.node;q=l(d,{parent:!0});var p=q.node}catch(J){throw new r(10);}if(!n||!p)throw new r(44);if(n.lc!==p.lc)throw new r(75);var y=I(n,h),C=ub(c,g);if("."!==C.charAt(0))throw new r(28);C=ub(d,e);if("."!==C.charAt(0))throw new r(55);try{var x=I(p,m)}catch(J){}if(y!==x){var ia=t(y.mode),Z=Wb(n,h,ia);if(Z)throw new r(Z);
if(Z=x?Wb(p,m,ia):Vb(p,m))throw new r(Z);if(!n.Yb.Oc)throw new r(63);if(y.uc||x&&x.uc)throw new r(10);if(p!==n&&(Z=ba(n,"w")))throw new r(Z);try{L.willMovePath&&L.willMovePath(c,d)}catch(J){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+J.message)}Rb(y);try{n.Yb.Oc(y,p,m)}catch(J){throw J;}finally{Qb(y)}try{if(L.onMovePath)L.onMovePath(c,d)}catch(J){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+J.message)}}return 0}catch(J){return"undefined"!==
typeof M&&J instanceof r||z(J),-J.bc}},ua:function(a,b){N=b;try{var c=Q(),d=O(),e=O();return ea(c,A,d,e)}catch(g){return"undefined"!==typeof M&&g instanceof r||z(g),-g.bc}},ta:function(a,b){N=b;try{var c=pc(),d=l(c,{parent:!0}).node,e=rb(c),g=I(d,e),h=Wb(d,e,!0);if(h)throw new r(h);if(!d.Yb.Pc)throw new r(63);if(g.uc)throw new r(10);try{L.willDeletePath&&L.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Yb.Pc(d,e);Rb(g);try{if(L.onDeletePath)L.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof M&&m instanceof r||z(m),-m.bc}},R:function(a,b){N=b;try{var c=pc(),d=O(),e=O();return da(c,d,e).sc}catch(g){return"undefined"!==typeof M&&g instanceof r||z(g),-g.bc}},Q:function(a,b){N=b;try{var c=Q(),d=O();switch(d){case 21509:case 21505:return c.ec?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.ec?0:-59;case 21519:if(!c.ec)return-59;var e=O();return w[e>>2]=0;case 21520:return c.ec?
-28:-59;case 21531:a=e=O();if(!c.Zb.Ed)throw new r(59);return c.Zb.Ed(c,d,a);case 21523:return c.ec?0:-59;case 21524:return c.ec?0:-59;default:z("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof M&&g instanceof r||z(g),-g.bc}},ra:function(a,b){N=b;return 0},qa:function(a,b){N=b;try{O();var c=O();Sd(c,0,136);w[c>>2]=1;w[c+4>>2]=2;w[c+8>>2]=3;w[c+12>>2]=4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof r||z(d),-d.bc}},v:function(){},x:function(){return qc.apply(null,arguments)},
P:function(){return rc.apply(null,arguments)},pa:function(){return sc.apply(null,arguments)},T:function(){return tc.apply(null,arguments)},oa:function(){return uc.apply(null,arguments)},na:function(a){var b=vc[a];delete vc[a];var c=b.Zc,d=b.rc,e=b.fd,g=e.map(function(a){return a.Bd}).concat(e.map(function(a){return a.Pd}));R([a],g,function(a){var g={};e.forEach(function(b,c){var d=a[c],h=b.zd,m=b.Ad,x=a[c+e.length],n=b.Od,q=b.Qd;g[b.vd]={read:function(a){return d.fromWireType(h(m,a))},write:function(a,
b){var c=[];n(q,a,x.toWireType(c,b));wc(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);d(a);return b},toWireType:function(a,b){for(var e in g)if(!(e in b))throw new TypeError("Missing field");var h=c();for(e in g)g[e].write(h,b[e]);null!==a&&a.push(d,h);return h},argPackAdvance:8,readValueFromPointer:xc,kc:d}]})},ma:function(a,b,c,d,e){var g=Gc(c);b=T(b);S(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:e},argPackAdvance:8,
readValueFromPointer:function(a){if(1===c)var d=A;else if(2===c)d=Ma;else if(4===c)d=w;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},kc:null})},p:function(a,b,c,d,e,g,h,m,q,n,p,y,C){p=T(p);g=W(e,g);m&&(m=W(h,m));n&&(n=W(q,n));C=W(y,C);var x=Bc(p);Vc(x,function(){kd("Cannot construct "+p+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.$b;var e=c.tc}else e=Sc.prototype;b=Cc(x,function(){if(Object.getPrototypeOf(this)!==
h)throw new Ic("Use 'new' to construct "+p);if(void 0===q.vc)throw new Ic(p+" has no accessible constructor");var a=q.vc[arguments.length];if(void 0===a)throw new Ic("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(q.vc).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(e,{constructor:{value:b}});b.prototype=h;var q=new Wc(p,b,h,C,c,g,m,n);c=new V(p,q,!0,!1);e=new V(p+"*",q,!1,!1);var ia=new V(p+
" const*",q,!1,!0);Tc[a]={pointerType:e,rd:ia};gd(x,b);return[c,e,ia]})},D:function(a,b,c,d,e,g){var h=ld(b,c);e=W(d,e);R([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.$b.vc&&(a.$b.vc=[]);if(void 0!==a.$b.vc[b-1])throw new Ic("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.$b.vc[b-1]=function(){kd("Cannot construct "+
a.name+" due to unbound types",h)};R([],h,function(d){a.$b.vc[b-1]=function(){arguments.length!==b-1&&U(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var m=1;m<b;++m)h[m]=d[m].toWireType(a,arguments[m-1]);h=e.apply(null,h);wc(a);return d[0].fromWireType(h)};return[]});return[]})},i:function(a,b,c,d,e,g,h,m){var q=ld(c,d);b=T(b);g=W(e,g);R([],[a],function(a){function d(){kd("Cannot call "+e+" due to unbound types",q)}a=a[0];var e=a.name+"."+b;m&&a.$b.Kd.push(b);
var n=a.$b.tc,x=n[b];void 0===x||void 0===x.gc&&x.className!==a.name&&x.Jc===c-2?(d.Jc=c-2,d.className=a.name,n[b]=d):(Uc(n,b,e),n[b].gc[c-2]=d);R([],q,function(d){d=nd(e,d,a,g,h);void 0===n[b].gc?(d.Jc=c-2,n[b]=d):n[b].gc[c-2]=d;return[]});return[]})},g:function(a,b,c,d,e,g,h,m,q,n){b=T(b);e=W(d,e);R([],[a],function(a){a=a[0];var d=a.name+"."+b,p={get:function(){kd("Cannot access "+d+" due to unbound types",[c,h])},enumerable:!0,configurable:!0};q?p.set=function(){kd("Cannot access "+d+" due to unbound types",
[c,h])}:p.set=function(){U(d+" is a read-only property")};Object.defineProperty(a.$b.tc,b,p);R([],q?[c,h]:[c],function(c){var h=c[0],x={get:function(){var b=od(this,a,d+" getter");return h.fromWireType(e(g,b))},enumerable:!0};if(q){q=W(m,q);var p=c[1];x.set=function(b){var c=od(this,a,d+" setter"),e=[];q(n,c,p.toWireType(e,b));wc(e)}}Object.defineProperty(a.$b.tc,b,x);return[]});return[]})},f:function(a,b,c){a=T(a);R([],[b],function(b){b=b[0];f[a]=b.fromWireType(c);return[]})},la:function(a,b){b=
T(b);S(a,{name:b,fromWireType:function(a){var b=Y[a].value;qd(a);return b},toWireType:function(a,b){return ad(b)},argPackAdvance:8,readValueFromPointer:xc,kc:null})},C:function(a,b,c,d){function e(){}c=Gc(c);b=T(b);e.values={};S(a,{name:b,constructor:e,fromWireType:function(a){return this.constructor.values[a]},toWireType:function(a,b){return b.value},argPackAdvance:8,readValueFromPointer:rd(b,c,d),kc:null});Vc(b,e)},b:function(a,b,c){var d=sd(a,"enum");b=T(b);a=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:Cc(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},O:function(a,b,c){c=Gc(c);b=T(b);S(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Zc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:td(b,c),kc:null})},B:function(a,b,c,d,e,g){var h=ld(b,c);a=T(a);e=W(d,e);Vc(a,function(){kd("Cannot call "+a+" due to unbound types",h)},b-1);R([],h,
function(c){gd(a,nd(a,[c[0],null].concat(c.slice(1)),null,e,g),b-1);return[]})},o:function(a,b,c,d,e){function g(a){return a}b=T(b);-1===e&&(e=4294967295);var h=Gc(c);if(0===d){var m=32-8*c;g=function(a){return a<<m>>>m}}var q=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Zc(c)+'" to '+this.name);if(c<d||c>e)throw new TypeError('Passing a number "'+Zc(c)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+e+"]!");return q?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:ud(b,h,0!==d),kc:null})},j:function(a,b,c){function d(a){a>>=2;var b=D;return new e(b.buffer,b[a+1],b[a])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Dd:!0})},N:function(a,b){b=T(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(a){var b=D[a>>
2];if(c){var d=B[a+4+b],h=0;0!=d&&(h=d,B[a+4+b]=0);var m=a+4;for(d=0;d<=b;++d){var q=a+4+d;if(0==B[q]){m=Fa(m);if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;m=q+1}}0!=h&&(B[a+4+b]=h)}else{n=Array(b);for(d=0;d<b;++d)n[d]=String.fromCharCode(B[a+4+d]);n=n.join("")}X(a);return n},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||U("Cannot pass non-string to std::string");
var e=(c&&d?function(){return Ha(b)}:function(){return b.length})(),m=Ca(4+e+1);D[m>>2]=e;if(c&&d)Ga(b,B,m+4,e+1);else if(d)for(d=0;d<e;++d){var q=b.charCodeAt(d);255<q&&(X(m),U("String has UTF-16 code units that do not fit in 8 bits"));B[m+4+d]=q}else for(d=0;d<e;++d)B[m+4+d]=b[d];null!==a&&a.push(X,m);return m},argPackAdvance:8,readValueFromPointer:xc,kc:function(a){X(a)}})},ka:function(a,b,c){c=T(c);if(2===b){var d=function(){return Na};var e=1}else 4===b&&(d=function(){return D},e=2);S(a,{name:c,
fromWireType:function(a){for(var b=d(),c=D[a>>2],g=Array(c),n=a+4>>e,p=0;p<c;++p)g[p]=String.fromCharCode(b[n+p]);X(a);return g.join("")},toWireType:function(a,c){var g=c.length,h=Ca(4+g*b),n=d();D[h>>2]=g;for(var p=h+4>>e,y=0;y<g;++y)n[p+y]=c.charCodeAt(y);null!==a&&a.push(X,h);return h},argPackAdvance:8,readValueFromPointer:xc,kc:function(a){X(a)}})},ja:function(a,b,c,d,e,g){vc[a]={name:T(b),Zc:W(c,d),rc:W(e,g),fd:[]}},M:function(a,b,c,d,e,g,h,m,q,n){vc[a].fd.push({vd:T(b),Bd:c,zd:W(d,e),Ad:g,Pd:h,
Od:W(m,q),Qd:n})},ia:function(a,b){b=T(b);S(a,{$d:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ha:qd,ga:function(a){4<a&&(Y[a].ad+=1)},A:function(a,b){a=sd(a,"_emval_take_value");a=a.readValueFromPointer(b);return ad(a)},__memory_base:1024,__table_base:0,a:function(){z()},fa:vd,ea:function(a,b){if(0===a)a=Date.now();else if(1===a&&"object"===typeof performance&&performance&&"function"===typeof performance.now)a=wd();else return sb(),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=
a%1E3*1E6|0;return 0},da:ua,ca:function(a,b,c){B.set(B.subarray(b,b+c),a)},ba:function(a){if(2147418112<a)return!1;for(var b=Math.max(ua(),16777216);b<a;)536870912>=b?b=Ka(2*b):b=Math.min(Ka((3*b+2147483648)/4),2147418112);a:{try{ya.grow(b-La.byteLength+65535>>16);Qa(ya.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},u:function(a){Td(a)},aa:Za,l:xd,_:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},Z:function(a){return yd(a,3986384)},K:yd,n:zd,h:function(a){return zd(a)},
Y:Ad,m:function(a){return Ad(a)},e:Bd,r:function(a){return Bd(a)},z:function(a){var b=Cd.jc[a];Cd.jc.splice(a,1);Ud(b)},J:Cd,W:function(){z("trap!")},V:cb,I:function(a){return Jd(a,3986384)},y:Jd,U:function(a){Ed();var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0),c=w[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),m=Math.min(h,g);0>c?w[a+32>>2]=Number(g!=h&&m==d):0<c!=
(m==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));w[a+24>>2]=b.getDay();w[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;return b.getTime()/1E3|0},H:function(a,b){if(0===a)return sb(),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||0>c)return sb(),-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((oa||pa)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},k:function(){return 0},w:function(a,
b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),
0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=Od(new Date(a.hc+1900,0,1),a.Tc);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=h(m(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var n=w[d+40>>2];d={Ud:w[d>>2],Td:w[d+4>>2],Rc:w[d+8>>2],Hc:w[d+12>>2],Cc:w[d+16>>2],hc:w[d+20>>2],Sc:w[d+24>>2],Tc:w[d+28>>2],ce:w[d+32>>2],Sd:w[d+36>>2],Vd:n?Fa(n):""};c=Fa(c);n={"%c":"%a %b %d %H:%M:%S %Y",
"%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),C="January February March April May June July August September October November December".split(" ");
n={"%a":function(a){return y[a.Sc].substring(0,3)},"%A":function(a){return y[a.Sc]},"%b":function(a){return C[a.Cc].substring(0,3)},"%B":function(a){return C[a.Cc]},"%C":function(a){return g((a.hc+1900)/100|0,2)},"%d":function(a){return g(a.Hc,2)},"%e":function(a){return e(a.Hc,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return g(a.Rc,2)},"%I":function(a){a=a.Rc;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Hc+Ld(Kd(a.hc+
1900)?Md:Nd,a.Cc-1),3)},"%m":function(a){return g(a.Cc+1,2)},"%M":function(a){return g(a.Td,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.Rc&&12>a.Rc?"AM":"PM"},"%S":function(a){return g(a.Ud,2)},"%t":function(){return"\t"},"%u":function(a){return a.Sc||7},"%U":function(a){var b=new Date(a.hc+1900,0,1),c=0===b.getDay()?b:Od(b,7-b.getDay());a=new Date(a.hc+1900,a.Cc,a.Hc);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ld(Kd(a.getFullYear())?Md:Nd,a.getMonth()-1)-31)+a.getDate())/7),2):
0===h(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.hc+1900,0,4)),c=m(new Date(a.hc+1901,0,4)),d=Od(new Date(a.hc+1900,0,1),a.Tc);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.hc+1900?a.Tc+32-b.getDate():a.Tc+1-b.getDate())/7),2)},"%w":function(a){return a.Sc},"%W":function(a){var b=new Date(a.hc,0,1),c=1===b.getDay()?b:Od(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.hc+1900,a.Cc,a.Hc);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ld(Kd(a.getFullYear())?Md:Nd,a.getMonth()-
1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.hc+1900).toString().substring(2)},"%Y":function(a){return a.hc+1900},"%z":function(a){a=a.Sd;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Vd},"%%":function(){return"%"}};for(p in n)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));p=Bb(c,!1);if(p.length>b)return 0;A.set(p,a);return p.length-1},G:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b},
d:z,memory:ya,q:function(){},table:za},Vd=f.asm({},lb,La);f.asm=Vd;var Rd=f.__ZSt18uncaught_exceptionv=function(){return f.asm.Ca.apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return f.asm.Da.apply(null,arguments)};f.___errno_location=function(){return f.asm.Ea.apply(null,arguments)};
var jd=f.___getTypeName=function(){return f.asm.Fa.apply(null,arguments)},Hd=f.__get_daylight=function(){return f.asm.Ga.apply(null,arguments)},Gd=f.__get_timezone=function(){return f.asm.Ha.apply(null,arguments)},Id=f.__get_tzname=function(){return f.asm.Ia.apply(null,arguments)},X=f._free=function(){return f.asm.Ja.apply(null,arguments)};f._main=function(){return f.asm.Ka.apply(null,arguments)};
var Ca=f._malloc=function(){return f.asm.La.apply(null,arguments)},Sd=f._memset=function(){return f.asm.Ma.apply(null,arguments)},mb=f.globalCtors=function(){return f.asm.Sb.apply(null,arguments)},Ja=f.stackAlloc=function(){return f.asm.Tb.apply(null,arguments)},Ud=f.stackRestore=function(){return f.asm.Ub.apply(null,arguments)},Dd=f.stackSave=function(){return f.asm.Vb.apply(null,arguments)};f.dynCall_dd=function(){return f.asm.Na.apply(null,arguments)};
f.dynCall_did=function(){return f.asm.Oa.apply(null,arguments)};f.dynCall_didd=function(){return f.asm.Pa.apply(null,arguments)};f.dynCall_dii=function(){return f.asm.Qa.apply(null,arguments)};f.dynCall_fii=function(){return f.asm.Ra.apply(null,arguments)};f.dynCall_fiifi=function(){return f.asm.Sa.apply(null,arguments)};f.dynCall_fiii=function(){return f.asm.Ta.apply(null,arguments)};f.dynCall_fiiii=function(){return f.asm.Ua.apply(null,arguments)};
f.dynCall_fiiiiiiiiffii=function(){return f.asm.Va.apply(null,arguments)};f.dynCall_i=function(){return f.asm.Wa.apply(null,arguments)};f.dynCall_ii=function(){return f.asm.Xa.apply(null,arguments)};f.dynCall_iidiiii=function(){return f.asm.Ya.apply(null,arguments)};f.dynCall_iii=function(){return f.asm.Za.apply(null,arguments)};f.dynCall_iiifii=function(){return f.asm._a.apply(null,arguments)};f.dynCall_iiii=function(){return f.asm.$a.apply(null,arguments)};
f.dynCall_iiiii=function(){return f.asm.ab.apply(null,arguments)};f.dynCall_iiiiii=function(){return f.asm.bb.apply(null,arguments)};f.dynCall_iiiiiii=function(){return f.asm.cb.apply(null,arguments)};f.dynCall_iiiiiiidiiddii=function(){return f.asm.db.apply(null,arguments)};f.dynCall_iiiiiiii=function(){return f.asm.eb.apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return f.asm.fb.apply(null,arguments)};f.dynCall_iiiiiiiiii=function(){return f.asm.gb.apply(null,arguments)};
f.dynCall_iiiiiiiiiiiiiifii=function(){return f.asm.hb.apply(null,arguments)};f.dynCall_iiiiij=function(){return f.asm.ib.apply(null,arguments)};f.dynCall_iiiji=function(){return f.asm.jb.apply(null,arguments)};f.dynCall_iiijjji=function(){return f.asm.kb.apply(null,arguments)};f.dynCall_iij=function(){return f.asm.lb.apply(null,arguments)};f.dynCall_ijiii=function(){return f.asm.mb.apply(null,arguments)};f.dynCall_jii=function(){return f.asm.nb.apply(null,arguments)};
f.dynCall_jiiii=function(){return f.asm.ob.apply(null,arguments)};f.dynCall_jiiij=function(){return f.asm.pb.apply(null,arguments)};f.dynCall_jiiji=function(){return f.asm.qb.apply(null,arguments)};f.dynCall_jij=function(){return f.asm.rb.apply(null,arguments)};f.dynCall_jiji=function(){return f.asm.sb.apply(null,arguments)};f.dynCall_v=function(){return f.asm.tb.apply(null,arguments)};f.dynCall_vi=function(){return f.asm.ub.apply(null,arguments)};
f.dynCall_vii=function(){return f.asm.vb.apply(null,arguments)};f.dynCall_viid=function(){return f.asm.wb.apply(null,arguments)};f.dynCall_viidi=function(){return f.asm.xb.apply(null,arguments)};f.dynCall_viifi=function(){return f.asm.yb.apply(null,arguments)};f.dynCall_viii=function(){return f.asm.zb.apply(null,arguments)};f.dynCall_viiif=function(){return f.asm.Ab.apply(null,arguments)};f.dynCall_viiiff=function(){return f.asm.Bb.apply(null,arguments)};
f.dynCall_viiii=function(){return f.asm.Cb.apply(null,arguments)};f.dynCall_viiiif=function(){return f.asm.Db.apply(null,arguments)};f.dynCall_viiiifii=function(){return f.asm.Eb.apply(null,arguments)};f.dynCall_viiiii=function(){return f.asm.Fb.apply(null,arguments)};f.dynCall_viiiiii=function(){return f.asm.Gb.apply(null,arguments)};f.dynCall_viiiiiiff=function(){return f.asm.Hb.apply(null,arguments)};f.dynCall_viiiiiifi=function(){return f.asm.Ib.apply(null,arguments)};
f.dynCall_viiiiiii=function(){return f.asm.Jb.apply(null,arguments)};f.dynCall_viiiiiiifi=function(){return f.asm.Kb.apply(null,arguments)};f.dynCall_viiiiiiii=function(){return f.asm.Lb.apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return f.asm.Mb.apply(null,arguments)};f.dynCall_viiiiiiiiii=function(){return f.asm.Nb.apply(null,arguments)};f.dynCall_viiiiiiiiiii=function(){return f.asm.Ob.apply(null,arguments)};f.dynCall_viiiiiiiiiiii=function(){return f.asm.Pb.apply(null,arguments)};
f.dynCall_viiiiiiiiiiiiii=function(){return f.asm.Qb.apply(null,arguments)};f.dynCall_viiijj=function(){return f.asm.Rb.apply(null,arguments)};f.asm=Vd;var Wd;f.then=function(a){if(Wd)a(f);else{var b=f.onRuntimeInitialized;f.onRuntimeInitialized=function(){b&&b();a(f)}}return f};function Xd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fb=function $d(){Wd||ae();Wd||(fb=$d)};
function ha(a){var b=f._main;a=a||[];var c=a.length+1,d=Ja(4*(c+1));w[d>>2]=Ia(ma);for(var e=1;e<c;e++)w[(d>>2)+e]=Ia(a[e-1]);w[(d>>2)+c]=0;try{var g=b(c,d);Td(g,!0)}catch(h){h instanceof Xd||("SimulateInfiniteLoop"==h?xa=!0:((a=h)&&"object"===typeof h&&h.stack&&(a=[h,h.stack]),v("exception thrown: "+a),na(1,h)))}finally{}}
function ae(a){function b(){if(!Wd&&(Wd=!0,!Aa)){Xa=!0;f.noFSInit||kc||(kc=!0,jc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?mc("stdin",f.stdin):cc("/dev/tty","/dev/stdin"),f.stdout?mc("stdout",null,f.stdout):cc("/dev/tty","/dev/stdout"),f.stderr?mc("stderr",null,f.stderr):cc("/dev/tty1","/dev/stderr"),da("/dev/stdin","r"),da("/dev/stdout","w"),da("/dev/stderr","w"));Sa(Ua);Mb=!1;Sa(Va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();be&&ha(a);if(f.postRun)for("function"==typeof f.postRun&&
(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Wa.unshift(b)}Sa(Wa)}}a=a||la;if(!(0<db)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ya();Sa(Ta);0<db||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=ae;function Td(a,b){if(!b||!xa||0!==a){if(!xa&&(Aa=!0,f.onExit))f.onExit(a);na(a,new Xd(a))}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var be=!1;f.noInitialRun&&(be=!1);xa=!0;ae();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    