
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var e,k;var l;l||(l=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa={},r;for(r in l)l.hasOwnProperty(r)&&(aa[r]=l[r]);l.arguments=[];l.thisProgram="./this.program";l.quit=function(a,b){throw b;};l.preRun=[];l.postRun=[];var ba=!1,ca=!1,t=!1,da=!1;ba="object"===typeof window;ca="function"===typeof importScripts;t="object"===typeof process&&"function"===typeof require&&!ba&&!ca;da=!ba&&!t&&!ca;var u="";
if(t){u=__dirname+"/";var ea,fa;l.read=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};l.readBinary=function(a){a=l.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(l.thisProgram=process.argv[1].replace(/\\/g,"/"));l.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;});process.on("unhandledRejection",v);l.quit=function(a){process.exit(a)};
l.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(l.read=function(a){return read(a)}),l.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?l.arguments=scriptArgs:"undefined"!=typeof arguments&&(l.arguments=arguments),"function"===typeof quit&&(l.quit=function(a){quit(a)});else if(ba||ca)ca?u=self.location.href:document.currentScript&&
(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",l.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ca&&(l.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),l.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},l.setWindowTitle=function(a){document.title=a};var ia=l.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=l.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ia);for(r in aa)aa.hasOwnProperty(r)&&(l[r]=aa[r]);aa=void 0;function ja(a){var b=x[ka>>2];a=b+a+15&-16;if(a<=la())x[ka>>2]=a;else if(!ma(a))return 0;return b}
var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var oa,pa=!1;function assert(a,b){a||v("Assertion failed: "+b)}function qa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=ra(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)x[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}
var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function ua(a){return a?ta(B,a,void 0):""}
function va(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ya(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,A,B,za,Aa,x,C,Ba,Ca;
function Da(){l.HEAP8=A=new Int8Array(buffer);l.HEAP16=za=new Int16Array(buffer);l.HEAP32=x=new Int32Array(buffer);l.HEAPU8=B=new Uint8Array(buffer);l.HEAPU16=Aa=new Uint16Array(buffer);l.HEAPU32=C=new Uint32Array(buffer);l.HEAPF32=Ba=new Float32Array(buffer);l.HEAPF64=Ca=new Float64Array(buffer)}var ka=3406624,Ea=l.TOTAL_MEMORY||16777216;5242880>Ea&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Ea+"! (TOTAL_STACK=5242880)");
l.buffer?buffer=l.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(oa=new WebAssembly.Memory({initial:Ea/65536}),buffer=oa.buffer):buffer=new ArrayBuffer(Ea);Da();x[ka>>2]=8649536;function Fa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ad;"number"===typeof c?void 0===b.Ac?l.dynCall_v(c):l.dynCall_vi(c,b.Ac):c(void 0===b.Ac?null:b.Ac)}}}var Ga=[],Ha=[],Ia=[],Ja=[],Ka=!1;function La(){var a=l.preRun.shift();Ga.unshift(a)}
var Ma=Math.abs,Na=Math.ceil,Oa=Math.floor,Pa=Math.min,Qa=Math.trunc,Ra=0,Sa=null,Ua=null;l.preloadedImages={};l.preloadedAudios={};function Va(){var a=Wa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Wa="convert.wasm";if(!Va()){var Xa=Wa;Wa=l.locateFile?l.locateFile(Xa,u):u+Xa}
function Ya(){try{if(l.wasmBinary)return new Uint8Array(l.wasmBinary);if(l.readBinary)return l.readBinary(Wa);throw"both async and sync fetching of the wasm failed";}catch(a){v(a)}}function Za(){return l.wasmBinary||!ba&&!ca||"function"!==typeof fetch?new Promise(function(a){a(Ya())}):fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}
function $a(a){function b(a){l.asm=a.exports;Ra--;l.monitorRunDependencies&&l.monitorRunDependencies(Ra);0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ua&&(a=Ua,Ua=null,a()))}function c(a){b(a.instance)}function d(a){Za().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);v(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};Ra++;l.monitorRunDependencies&&l.monitorRunDependencies(Ra);if(l.instantiateWasm)try{return l.instantiateWasm(f,
b)}catch(g){return w("Module.instantiateWasm callback failed with error: "+g),!1}l.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Va()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Wa,{credentials:"same-origin"}),f).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
l.asm=function(a,b){b.memory=oa;b.table=new WebAssembly.Table({initial:6906,maximum:6906,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return $a(b)};Ha.push({ad:function(){ab()}});var D={};
function bb(a){if(bb.Ub){var b=x[a>>2];var c=x[b>>2]}else bb.Ub=!0,D.USER=D.LOGNAME="web_user",D.PATH="/",D.PWD="/",D.HOME="/home/web_user",D.LANG="C.UTF-8",D._=l.thisProgram,c=Ka?ra(1024):ja(1024),b=Ka?ra(256):ja(256),x[b>>2]=c,x[a>>2]=b;a=[];var d=0,f;for(f in D)if("string"===typeof D[f]){var g=f+"="+D[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,m=0;m<d.length;++m)A[h++>>0]=d.charCodeAt(m);A[h>>0]=0;x[b+
4*f>>2]=c;c+=g.length+1}x[b+4*a.length>>2]=0}function cb(){return!!cb.Hc}function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function gb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function hb(){var a=Array.prototype.slice.call(arguments,0);return eb(a.join("/"))}function ib(a,b){return eb(a+"/"+b)}function jb(a){l.___errno_location&&(x[l.___errno_location()>>2]=a);return a}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function lb(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=kb(a).substr(1);b=kb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var mb=[];function nb(a,b){mb[a]={input:[],output:[],oc:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new E(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.oc.flush(a.tty)},flush:function(a){a.tty.oc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.oc.Rc)throw new E(6);for(var f=0,g=0;g<d;g++){try{var h=a.tty.oc.Rc(a.tty)}catch(m){throw new E(5);}if(void 0===h&&0===f)throw new E(11);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.oc.Dc)throw new E(6);
try{for(var f=0;f<d;f++)a.tty.oc.Dc(a.tty,b[c+f])}catch(g){throw new E(5);}d&&(a.node.timestamp=Date.now());return f}},rb={Rc:function(a){if(!a.input.length){var b=null;if(t){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},Dc:function(a,b){null===b||10===b?(ia(ta(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ia(ta(a.output,0)),a.output=[])}},sb={Dc:function(a,b){null===b||10===b?(w(ta(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(w(ta(a.output,0)),a.output=[])}},G={bc:null,Sb:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(1);G.bc||(G.bc={dir:{node:{Yb:G.Jb.Yb,Zb:G.Jb.Zb,lookup:G.Jb.lookup,qc:G.Jb.qc,rename:G.Jb.rename,unlink:G.Jb.unlink,rmdir:G.Jb.rmdir,readdir:G.Jb.readdir,symlink:G.Jb.symlink},stream:{ec:G.Lb.ec}},file:{node:{Yb:G.Jb.Yb,Zb:G.Jb.Zb},stream:{ec:G.Lb.ec,read:G.Lb.read,write:G.Lb.write,Ic:G.Lb.Ic,Sc:G.Lb.Sc,
Uc:G.Lb.Uc}},link:{node:{Yb:G.Jb.Yb,Zb:G.Jb.Zb,readlink:G.Jb.readlink},stream:{}},Kc:{node:{Yb:G.Jb.Yb,Zb:G.Jb.Zb},stream:tb}});c=ub(a,b,c,d);H(c.mode)?(c.Jb=G.bc.dir.node,c.Lb=G.bc.dir.stream,c.Kb={}):32768===(c.mode&61440)?(c.Jb=G.bc.file.node,c.Lb=G.bc.file.stream,c.Pb=0,c.Kb=null):40960===(c.mode&61440)?(c.Jb=G.bc.link.node,c.Lb=G.bc.link.stream):8192===(c.mode&61440)&&(c.Jb=G.bc.Kc.node,c.Lb=G.bc.Kc.stream);c.timestamp=Date.now();a&&(a.Kb[b]=c);return c},Bd:function(a){if(a.Kb&&a.Kb.subarray){for(var b=
[],c=0;c<a.Pb;++c)b.push(a.Kb[c]);return b}return a.Kb},Cd:function(a){return a.Kb?a.Kb.subarray?a.Kb.subarray(0,a.Pb):new Uint8Array(a.Kb):new Uint8Array},Mc:function(a,b){var c=a.Kb?a.Kb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Kb,a.Kb=new Uint8Array(b),0<a.Pb&&a.Kb.set(c.subarray(0,a.Pb),0))},od:function(a,b){if(a.Pb!=b)if(0==b)a.Kb=null,a.Pb=0;else{if(!a.Kb||a.Kb.subarray){var c=a.Kb;a.Kb=new Uint8Array(new ArrayBuffer(b));c&&a.Kb.set(c.subarray(0,Math.min(b,
a.Pb)))}else if(a.Kb||(a.Kb=[]),a.Kb.length>b)a.Kb.length=b;else for(;a.Kb.length<b;)a.Kb.push(0);a.Pb=b}},Jb:{Yb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Pb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ic=4096;b.blocks=Math.ceil(b.size/b.ic);return b},Zb:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.od(a,b.size)},lookup:function(){throw vb[2];},qc:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(H(a.mode)){try{var d=I(b,c)}catch(g){}if(d)for(var f in d.Kb)throw new E(39);}delete a.parent.Kb[a.name];a.name=c;b.Kb[c]=a;a.parent=b},unlink:function(a,b){delete a.Kb[b]},rmdir:function(a,b){var c=I(a,b),d;for(d in c.Kb)throw new E(39);delete a.Kb[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.Kb)a.Kb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new E(22);return a.link}},Lb:{read:function(a,b,c,d,f){var g=a.node.Kb;if(f>=a.node.Pb)return 0;a=Math.min(a.node.Pb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.Kb||a.Kb.subarray)){if(g)return a.Kb=b.subarray(c,c+d),a.Pb=d;if(0===a.Pb&&0===f)return a.Kb=new Uint8Array(b.subarray(c,c+d)),a.Pb=d;if(f+d<=a.Pb)return a.Kb.set(b.subarray(c,c+d),f),d}G.Mc(a,f+d);if(a.Kb.subarray&&b.subarray)a.Kb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Kb[f+g]=b[c+g];a.Pb=Math.max(a.Pb,f+d);return d},ec:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Pb);if(0>b)throw new E(22);return b},Ic:function(a,b,c){G.Mc(a.node,b+c);a.node.Pb=
Math.max(a.node.Pb,b+c)},Sc:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new E(19);c=a.node.Kb;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Pb)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=ra(d);if(!d)throw new E(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{Ob:d,Ad:a}},Uc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new E(19);if(f&2)return 0;G.Lb.write(a,b,0,d,c,!1);return 0}}},J={xc:!1,ud:function(){J.xc=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);J.Oc={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Jc:function(a){return Buffer.Ub?Buffer.from(a):new Buffer(a)},Sb:function(a){assert(t);return J.createNode(null,"/",J.Qc(a.Cc.root),0)},createNode:function(a,b,c){if(!H(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new E(22);a=ub(a,b,c);a.Jb=J.Jb;a.Lb=J.Lb;return a},Qc:function(a){try{var b=fs.lstatSync(a);J.xc&&(b.mode=b.mode|(b.mode&
292)>>2)}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}return b.mode},Vb:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Sb.Cc.root);b.reverse();return hb.apply(null,b)},$c:function(a){a&=-2656257;var b=0,c;for(c in J.Oc)a&c&&(b|=J.Oc[c],a^=c);if(a)throw new E(22);return b},Jb:{Yb:function(a){a=J.Vb(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}J.xc&&!b.ic&&(b.ic=4096);J.xc&&!b.blocks&&(b.blocks=(b.size+b.ic-1)/b.ic|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,ic:b.ic,blocks:b.blocks}},Zb:function(a,b){var c=J.Vb(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new E(-d.Mb);}},lookup:function(a,b){var c=ib(J.Vb(a),b);c=J.Qc(c);return J.createNode(a,b,c)},qc:function(a,b,c,d){a=J.createNode(a,b,c,d);b=J.Vb(a);try{H(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new E(-f.Mb);}return a},rename:function(a,b,c){a=J.Vb(a);b=ib(J.Vb(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new E(-d.Mb);}},unlink:function(a,b){a=ib(J.Vb(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}},rmdir:function(a,b){a=ib(J.Vb(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}},readdir:function(a){a=J.Vb(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new E(-b.Mb);
}},symlink:function(a,b,c){a=ib(J.Vb(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new E(-d.Mb);}},readlink:function(a){var b=J.Vb(a);try{return b=fs.readlinkSync(b),b=wb.relative(wb.resolve(a.Sb.Cc.root),b)}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}}},Lb:{open:function(a){var b=J.Vb(a.node);try{32768===(a.node.mode&61440)&&(a.rc=fs.openSync(b,J.$c(a.flags)))}catch(c){if(!c.code)throw c;throw new E(-c.Mb);}},close:function(a){try{32768===(a.node.mode&61440)&&a.rc&&fs.closeSync(a.rc)}catch(b){if(!b.code)throw b;
throw new E(-b.Mb);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.rc,J.Jc(b.buffer),c,d,f)}catch(g){throw new E(-g.Mb);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.rc,J.Jc(b.buffer),c,d,f)}catch(g){throw new E(-g.Mb);}},ec:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.rc).size}catch(d){throw new E(-d.Mb);}if(0>b)throw new E(22);return b}}},xb=null,yb={},zb=[],Ab=1,Bb=null,Cb=!0,K={},E=null,vb={};
function L(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Pc:!0,Fc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Fc)throw new E(40);a=db(a.split("/").filter(function(a){return!!a}),!1);var f=xb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=I(f,a[d]);c=ib(c,a[d]);f.fc&&(!g||g&&b.Pc)&&(f=f.fc.root);if(!g||b.pc)for(g=0;40960===(f.mode&61440);)if(f=Db(c),c=kb(fb(c),f),f=L(c,{Fc:b.Fc}).node,40<g++)throw new E(40);}return{path:c,node:f}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.Sb.Tc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length}function Gb(a){var b=Fb(a.parent.id,a.name);a.nc=Bb[b];Bb[b]=a}function Hb(a){var b=Fb(a.parent.id,a.name);if(Bb[b]===a)Bb[b]=a.nc;else for(b=Bb[b];b;){if(b.nc===a){b.nc=a.nc;break}b=b.nc}}
function I(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.Jb.lookup?0:13)throw new E(c,a);for(c=Bb[Fb(a.id,b)];c;c=c.nc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Jb.lookup(a,b)}
function ub(a,b,c,d){Jb||(Jb=function(a,b,c,d){a||(a=this);this.parent=a;this.Sb=a.Sb;this.fc=null;this.id=Ab++;this.name=b;this.mode=c;this.Jb={};this.Lb={};this.rdev=d},Jb.prototype={},Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Jb(a,b,c,d);Gb(a);return a}
function H(a){return 16384===(a&61440)}var Kb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Mb(a,b){try{return I(a,b),17}catch(c){}return Ib(a,"wx")}
function Nb(a,b,c){try{var d=I(a,b)}catch(f){return f.Mb}if(a=Ib(a,"wx"))return a;if(c){if(!H(d.mode))return 20;if(d===d.parent||"/"===Eb(d))return 16}else if(H(d.mode))return 21;return 0}function Ob(a){var b=4096;for(a=a||0;a<=b;a++)if(!zb[a])return a;throw new E(24);}
function Pb(a,b){Qb||(Qb=function(){},Qb.prototype={},Object.defineProperties(Qb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Qb,d;for(d in a)c[d]=a[d];a=c;b=Ob(b);a.fd=b;return zb[b]=a}var tb={open:function(a){a.Lb=yb[a.node.rdev].Lb;a.Lb.open&&a.Lb.open(a)},ec:function(){throw new E(29);}};function ob(a,b){yb[a]={Lb:b}}
function Rb(a,b){var c="/"===b,d=!b;if(c&&xb)throw new E(16);if(!c&&!d){var f=L(b,{Pc:!1});b=f.path;f=f.node;if(f.fc)throw new E(16);if(!H(f.mode))throw new E(20);}b={type:a,Cc:{},Tc:b,kd:[]};a=a.Sb(b);a.Sb=b;b.root=a;c?xb=a:f&&(f.fc=b,f.Sb&&f.Sb.kd.push(b))}function Sb(a,b,c){var d=L(a,{parent:!0}).node;a=gb(a);if(!a||"."===a||".."===a)throw new E(22);var f=Mb(d,a);if(f)throw new E(f);if(!d.Jb.qc)throw new E(1);return d.Jb.qc(d,a,b,c)}function M(a){Sb(a,16895,0)}
function Tb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Sb(a,b|8192,c)}function Ub(a,b){if(!kb(a))throw new E(2);var c=L(b,{parent:!0}).node;if(!c)throw new E(2);b=gb(b);var d=Mb(c,b);if(d)throw new E(d);if(!c.Jb.symlink)throw new E(1);c.Jb.symlink(c,b,a)}function Db(a){a=L(a).node;if(!a)throw new E(2);if(!a.Jb.readlink)throw new E(22);return kb(Eb(a.parent),a.Jb.readlink(a))}function Vb(a,b){a=L(a,{pc:!b}).node;if(!a)throw new E(2);if(!a.Jb.Yb)throw new E(1);return a.Jb.Yb(a)}
function Wb(a){return Vb(a,!0)}
function Xb(a,b,c,d){if(""===a)throw new E(2);if("string"===typeof b){var f=Kb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=eb(a);try{g=L(a,{pc:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new E(17);}else g=Sb(a,c,0),f=!0;if(!g)throw new E(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!H(g.mode))throw new E(20);if(!f&&(c=g?40960===(g.mode&61440)?40:H(g.mode)&&
("r"!==Lb(b)||b&512)?21:Ib(g,Lb(b)):2))throw new E(c);if(b&512){c=g;var h;"string"===typeof c?h=L(c,{pc:!0}).node:h=c;if(!h.Jb.Zb)throw new E(1);if(H(h.mode))throw new E(21);if(32768!==(h.mode&61440))throw new E(22);if(c=Ib(h,"w"))throw new E(c);h.Jb.Zb(h,{size:0,timestamp:Date.now()})}b&=-641;d=Pb({node:g,path:Eb(g),flags:b,seekable:!0,position:0,Lb:g.Lb,zd:[],error:!1},d);d.Lb.open&&d.Lb.open(d);!l.logReadFiles||b&1||(Yb||(Yb={}),a in Yb||(Yb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{K.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),K.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Zb(a,b,c){if(null===a.fd)throw new E(9);if(!a.seekable||!a.Lb.ec)throw new E(29);if(0!=c&&1!=c&&2!=c)throw new E(22);a.position=a.Lb.ec(a,b,c);a.zd=[];return a.position}
function $b(a,b,c,d){var f=A;if(0>c||0>d)throw new E(22);if(null===a.fd)throw new E(9);if(1===(a.flags&2097155))throw new E(9);if(H(a.node.mode))throw new E(21);if(!a.Lb.read)throw new E(22);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new E(29);b=a.Lb.read(a,f,b,c,d);g||(a.position+=b);return b}
function ac(a,b,c,d){var f=A;if(0>c||0>d)throw new E(22);if(null===a.fd)throw new E(9);if(0===(a.flags&2097155))throw new E(9);if(H(a.node.mode))throw new E(21);if(!a.Lb.write)throw new E(22);a.flags&1024&&Zb(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new E(29);b=a.Lb.write(a,f,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&K.onWriteToFile)K.onWriteToFile(a.path)}catch(h){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+h.message)}return b}
function bc(){E||(E=function(a,b){this.node=b;this.pd=function(a){this.Mb=a};this.pd(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},E.prototype=Error(),E.prototype.constructor=E,[2].forEach(function(a){vb[a]=new E(a);vb[a].stack="<generic error, no stack>"}))}var cc;function dc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ec(a,b,c){a=ib("/dev",a);var d=dc(!!b,!!c);fc||(fc=64);var f=fc++<<8|0;ob(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,h=0;h<f;h++){try{var m=b()}catch(F){throw new E(5);}if(void 0===m&&0===g)throw new E(11);if(null===m||void 0===m)break;g++;c[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(p){throw new E(5);}f&&(a.node.timestamp=Date.now());return g}});
Tb(a,d,f)}var fc,N={},Jb,Qb,Yb;
function hc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&eb(b)!==eb(Eb(f.node)))return-20;throw f;}x[c>>2]=d.dev;x[c+4>>2]=0;x[c+8>>2]=d.ino;x[c+12>>2]=d.mode;x[c+16>>2]=d.nlink;x[c+20>>2]=d.uid;x[c+24>>2]=d.gid;x[c+28>>2]=d.rdev;x[c+32>>2]=0;e=[d.size>>>0,(k=d.size,1<=+Ma(k)?0<k?(Pa(+Oa(k/4294967296),4294967295)|0)>>>0:~~+Na((k-+(~~k>>>0))/4294967296)>>>0:0)];x[c+40>>2]=e[0];x[c+44>>2]=e[1];x[c+48>>2]=4096;x[c+52>>2]=d.blocks;x[c+56>>2]=d.atime.getTime()/1E3|0;x[c+60>>2]=0;x[c+64>>2]=d.mtime.getTime()/
1E3|0;x[c+68>>2]=0;x[c+72>>2]=d.ctime.getTime()/1E3|0;x[c+76>>2]=0;e=[d.ino>>>0,(k=d.ino,1<=+Ma(k)?0<k?(Pa(+Oa(k/4294967296),4294967295)|0)>>>0:~~+Na((k-+(~~k>>>0))/4294967296)>>>0:0)];x[c+80>>2]=e[0];x[c+84>>2]=e[1];return 0}var P=0;function Q(){P+=4;return x[P-4>>2]}function ic(){return ua(Q())}function R(){var a=zb[Q()];if(!a)throw new E(9);return a}var jc={};function kc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function lc(a){return this.fromWireType(C[a>>2])}var mc={},nc={},oc={};
function pc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function qc(a,b){a=pc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function rc(a){var b=Error,c=qc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var sc=void 0;function tc(a){throw new sc(a);}
function S(a,b,c){function d(b){b=c(b);b.length!==a.length&&tc("Mismatched type converter count");for(var d=0;d<a.length;++d)T(a[d],b[d])}a.forEach(function(a){oc[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){nc.hasOwnProperty(a)?f[b]=nc[a]:(g.push(a),mc.hasOwnProperty(a)||(mc[a]=[]),mc[a].push(function(){f[b]=nc[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function uc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var vc=void 0;function U(a){for(var b="";B[a];)b+=vc[B[a++]];return b}var wc=void 0;function V(a){throw new wc(a);}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(nc.hasOwnProperty(a)){if(c.hd)return;V("Cannot register type '"+d+"' twice")}nc[a]=b;delete oc[a];mc.hasOwnProperty(a)&&(b=mc[a],delete mc[a],b.forEach(function(a){a()}))}function xc(a){return{count:a.count,mc:a.mc,sc:a.sc,Ob:a.Ob,Qb:a.Qb,Wb:a.Wb,$b:a.$b}}
function yc(a){V(a.Ib.Qb.Nb.name+" instance already deleted")}var zc=void 0,Ac=[];function Bc(){for(;Ac.length;){var a=Ac.pop();a.Ib.mc=!1;a["delete"]()}}function Cc(){}var Dc={};function Ec(a,b,c){if(void 0===a[b].Tb){var d=a[b];a[b]=function(){a[b].Tb.hasOwnProperty(arguments.length)||V("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Tb+")!");return a[b].Tb[arguments.length].apply(this,arguments)};a[b].Tb=[];a[b].Tb[d.uc]=d}}
function Fc(a,b,c){l.hasOwnProperty(a)?((void 0===c||void 0!==l[a].Tb&&void 0!==l[a].Tb[c])&&V("Cannot register public name '"+a+"' twice"),Ec(l,a,a),l.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),l[a].Tb[c]=b):(l[a]=b,void 0!==c&&(l[a].Ed=c))}function Gc(a,b,c,d,f,g,h,m){this.name=a;this.constructor=b;this.dc=c;this.cc=d;this.ac=f;this.bd=g;this.tc=h;this.Yc=m;this.md=[]}
function Hc(a,b,c){for(;b!==c;)b.tc||V("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.tc(a),b=b.ac;return a}function Ic(a,b){if(null===b)return this.Bc&&V("null is not a valid "+this.name),0;b.Ib||V('Cannot pass "'+Jc(b)+'" as a '+this.name);b.Ib.Ob||V("Cannot pass deleted object as a pointer of type "+this.name);return Hc(b.Ib.Ob,b.Ib.Qb.Nb,this.Nb)}
function Kc(a,b){if(null===b){this.Bc&&V("null is not a valid "+this.name);if(this.wc){var c=this.Ec();null!==a&&a.push(this.cc,c);return c}return 0}b.Ib||V('Cannot pass "'+Jc(b)+'" as a '+this.name);b.Ib.Ob||V("Cannot pass deleted object as a pointer of type "+this.name);!this.vc&&b.Ib.Qb.vc&&V("Cannot convert argument of type "+(b.Ib.$b?b.Ib.$b.name:b.Ib.Qb.name)+" to parameter type "+this.name);c=Hc(b.Ib.Ob,b.Ib.Qb.Nb,this.Nb);if(this.wc)switch(void 0===b.Ib.Wb&&V("Passing raw pointer to smart pointer is illegal"),
this.td){case 0:b.Ib.$b===this?c=b.Ib.Wb:V("Cannot convert argument of type "+(b.Ib.$b?b.Ib.$b.name:b.Ib.Qb.name)+" to parameter type "+this.name);break;case 1:c=b.Ib.Wb;break;case 2:if(b.Ib.$b===this)c=b.Ib.Wb;else{var d=b.clone();c=this.nd(c,Lc(function(){d["delete"]()}));null!==a&&a.push(this.cc,c)}break;default:V("Unsupporting sharing policy")}return c}
function Mc(a,b){if(null===b)return this.Bc&&V("null is not a valid "+this.name),0;b.Ib||V('Cannot pass "'+Jc(b)+'" as a '+this.name);b.Ib.Ob||V("Cannot pass deleted object as a pointer of type "+this.name);b.Ib.Qb.vc&&V("Cannot convert argument of type "+b.Ib.Qb.name+" to parameter type "+this.name);return Hc(b.Ib.Ob,b.Ib.Qb.Nb,this.Nb)}function Nc(a,b,c){if(b===c)return a;if(void 0===c.ac)return null;a=Nc(a,b,c.ac);return null===a?null:c.Yc(a)}var Oc={};
function Pc(a,b){for(void 0===b&&V("ptr should not be undefined");a.ac;)b=a.tc(b),a=a.ac;return Oc[b]}function Qc(a,b){b.Qb&&b.Ob||tc("makeClassHandle requires ptr and ptrType");!!b.$b!==!!b.Wb&&tc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{Ib:{value:b}})}
function W(a,b,c,d){this.name=a;this.Nb=b;this.Bc=c;this.vc=d;this.wc=!1;this.cc=this.nd=this.Ec=this.Vc=this.td=this.ld=void 0;void 0!==b.ac?this.toWireType=Kc:(this.toWireType=d?Ic:Mc,this.Xb=null)}function Rc(a,b,c){l.hasOwnProperty(a)||tc("Replacing nonexistant public symbol");void 0!==l[a].Tb&&void 0!==c?l[a].Tb[c]=b:(l[a]=b,l[a].uc=c)}
function X(a,b){a=U(a);if(void 0!==l["FUNCTION_TABLE_"+a])var c=l["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=l["dynCall_"+a];void 0===c&&(c=l["dynCall_"+a.replace(/f/g,"d")],void 0===c&&V("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var Sc=void 0;function Tc(a){a=Uc(a);var b=U(a);Y(a);return b}function Vc(a,b){function c(a){f[a]||nc[a]||(oc[a]?oc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Sc(a+": "+d.map(Tc).join([", "]));}function Wc(a,b){for(var c=[],d=0;d<a;d++)c.push(x[(b>>2)+d]);return c}
function Xc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=qc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Yc(a,b,c,d,f){var g=b.length;2>g&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Xb){m=!0;break}var q="void"!==b[0].name,n="",p="";for(c=0;c<g-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+pc(a)+"("+n+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";m&&(a+="var destructors = [];\n");var y=m?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[V,d,f,kc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+y+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+y+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(q?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(m)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Xb&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",n.push(g+"_dtor"),d.push(b[c].Xb));q&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Xc(n).apply(null,d)}
function Zc(a,b,c){a instanceof Object||V(c+' with invalid "this": '+a);a instanceof b.Nb.constructor||V(c+' incompatible with "this" of type '+a.constructor.name);a.Ib.Ob||V("cannot call emscripten binding method "+c+" on deleted object");return Hc(a.Ib.Ob,a.Ib.Qb.Nb,b.Nb)}var $c=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function ad(a){4<a&&0===--Z[a].Gc&&(Z[a]=void 0,$c.push(a))}
function Lc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=$c.length?$c.pop():Z.length;Z[b]={Gc:1,value:a};return b}}function bd(a,b,c){switch(b){case 0:return function(a){return this.fromWireType((c?A:B)[a])};case 1:return function(a){return this.fromWireType((c?za:Aa)[a>>1])};case 2:return function(a){return this.fromWireType((c?x:C)[a>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function cd(a,b){var c=nc[a];void 0===c&&V(b+" has unknown type "+Tc(a));return c}function Jc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function dd(a,b){switch(b){case 2:return function(a){return this.fromWireType(Ba[a>>2])};case 3:return function(a){return this.fromWireType(Ca[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ed(a,b,c){switch(b){case 0:return c?function(a){return A[a]}:function(a){return B[a]};case 1:return c?function(a){return za[a>>1]}:function(a){return Aa[a>>1]};case 2:return c?function(a){return x[a>>2]}:function(a){return C[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function fd(){void 0===fd.start&&(fd.start=Date.now());return 1E3*(Date.now()-fd.start)|0}function gd(){v()}function la(){return A.length}
function hd(a){a=ya(a);var b=buffer.byteLength;try{return-1!==oa.grow((a-b)/65536)?(buffer=oa.buffer,!0):!1}catch(c){return!1}}function ma(a){if(2147418112<a)return!1;for(var b=Math.max(la(),16777216);b<a;)536870912>=b?b=ya(2*b):b=Math.min(ya((3*b+2147483648)/4),2147418112);if(!hd(b))return!1;Da();return!0}function id(a){if(0===a)return 0;a=ua(a);if(!D.hasOwnProperty(a))return 0;id.Ub&&Y(id.Ub);a=D[a];var b=xa(a)+1,c=ra(b);c&&va(a,A,c,b);id.Ub=c;return id.Ub}va("GMT",B,3406528,4);
function jd(a){return Math.pow(2,a)}function kd(a){return Math.log(a)/Math.LN10}function ld(a){return Math.log(a)/Math.LN2}function md(){md.Ub||(md.Ub=[]);md.Ub.push(nd());return md.Ub.length-1}
function od(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!pd){pd=!0;x[qd()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);x[rd()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=qa(qb(d));f=qa(qb(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(x[sd()>>2]=d,x[sd()+4>>2]=f):(x[sd()>>2]=f,x[sd()+4>>2]=d)}}var pd;function td(a){return 0===a%4&&(0!==a%100||0===a%400)}
function ud(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var vd=[31,29,31,30,31,30,31,31,30,31,30,31],wd=[31,28,31,30,31,30,31,31,30,31,30,31];function xd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(td(a.getFullYear())?vd:wd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}bc();Bb=Array(4096);Rb(G,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");ob(259,{read:function(){return 0},write:function(a,b,c,h){return h}});Tb("/dev/null",259);nb(1280,rb);nb(1536,sb);Tb("/dev/tty",1280);Tb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(t)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){v("random_device")});ec("random",b);ec("urandom",b);M("/dev/shm");
M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");Rb({Sb:function(){var a=ub("/proc/self","fd",16895,73);a.Jb={lookup:function(a,c){var b=zb[+c];if(!b)throw new E(9);a={parent:null,Sb:{Tc:"fake"},Jb:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(t){var fs=require("fs"),wb=require("path");J.ud()}sc=l.InternalError=rc("InternalError");for(var yd=Array(256),zd=0;256>zd;++zd)yd[zd]=String.fromCharCode(zd);vc=yd;wc=l.BindingError=rc("BindingError");
Cc.prototype.isAliasOf=function(a){if(!(this instanceof Cc&&a instanceof Cc))return!1;var b=this.Ib.Qb.Nb,c=this.Ib.Ob,d=a.Ib.Qb.Nb;for(a=a.Ib.Ob;b.ac;)c=b.tc(c),b=b.ac;for(;d.ac;)a=d.tc(a),d=d.ac;return b===d&&c===a};Cc.prototype.clone=function(){this.Ib.Ob||yc(this);if(this.Ib.sc)return this.Ib.count.value+=1,this;var a=Object.create(Object.getPrototypeOf(this),{Ib:{value:xc(this.Ib)}});a.Ib.count.value+=1;a.Ib.mc=!1;return a};
Cc.prototype["delete"]=function(){this.Ib.Ob||yc(this);this.Ib.mc&&!this.Ib.sc&&V("Object already scheduled for deletion");--this.Ib.count.value;if(0===this.Ib.count.value){var a=this.Ib;a.Wb?a.$b.cc(a.Wb):a.Qb.Nb.cc(a.Ob)}this.Ib.sc||(this.Ib.Wb=void 0,this.Ib.Ob=void 0)};Cc.prototype.isDeleted=function(){return!this.Ib.Ob};
Cc.prototype.deleteLater=function(){this.Ib.Ob||yc(this);this.Ib.mc&&!this.Ib.sc&&V("Object already scheduled for deletion");Ac.push(this);1===Ac.length&&zc&&zc(Bc);this.Ib.mc=!0;return this};W.prototype.cd=function(a){this.Vc&&(a=this.Vc(a));return a};W.prototype.Lc=function(a){this.cc&&this.cc(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=lc;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.wc?Qc(this.Nb.dc,{Qb:this.ld,Ob:c,$b:this,Wb:a}):Qc(this.Nb.dc,{Qb:this,Ob:a})}var c=this.cd(a);if(!c)return this.Lc(a),null;var d=Pc(this.Nb,c);if(void 0!==d){if(0===d.Ib.count.value)return d.Ib.Ob=c,d.Ib.Wb=a,d.clone();d=d.clone();this.Lc(a);return d}d=this.Nb.bd(c);d=Dc[d];if(!d)return b.call(this);d=this.vc?d.Xc:d.pointerType;var f=Nc(c,this.Nb,d.Nb);return null===f?b.call(this):this.wc?Qc(d.Nb.dc,{Qb:d,Ob:f,$b:this,Wb:a}):Qc(d.Nb.dc,
{Qb:d,Ob:f})};l.getInheritedInstanceCount=function(){return Object.keys(Oc).length};l.getLiveInheritedInstances=function(){var a=[],b;for(b in Oc)Oc.hasOwnProperty(b)&&a.push(Oc[b]);return a};l.flushPendingDeletes=Bc;l.setDelayFunction=function(a){zc=a;Ac.length&&zc&&zc(Bc)};Sc=l.UnboundTypeError=rc("UnboundTypeError");l.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};l.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
t?gd=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?gd=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?gd=function(){return performance.now()}:gd=Date.now;function qb(a,b){var c=Array(xa(a)+1);a=va(a,c,0,c.length);b&&(c.length=a);return c}
var Bd=l.asm({},{d:v,l:function(){},c:function(a,b,c,d){v("Assertion failed: "+ua(a)+", at: "+[b?ua(b):"unknown filename",c,d?ua(d):"unknown function"])},na:bb,ia:function(a){return ra(a)},ga:function(a){"uncaught_exception"in cb?cb.Hc++:cb.Hc=1;throw a;},E:function(){},C:jb,z:function(a,b){P=b;try{var c=ic(),d=L(c,{parent:!0}).node,f=gb(c),g=I(d,f),h=Nb(d,f,!1);if(h)throw new E(h);if(!d.Jb.unlink)throw new E(1);if(g.fc)throw new E(16);try{K.willDeletePath&&K.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+
c+"') threw an exception: "+m.message)}d.Jb.unlink(d,f);Hb(g);try{if(K.onDeletePath)K.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof N&&m instanceof E||v(m),-m.Mb}},y:function(a,b){P=b;try{var c=R(),d=Q(),f=Q(),g=Q(),h=Q();if(!(-1==d&&0>f||0==d&&0<=f))return-75;Zb(c,f,h);e=[c.position>>>0,(k=c.position,1<=+Ma(k)?0<k?(Pa(+Oa(k/4294967296),4294967295)|0)>>>0:~~+Na((k-+(~~k>>>0))/4294967296)>>>
0:0)];x[g>>2]=e[0];x[g+4>>2]=e[1];c.kc&&0===f&&0===h&&(c.kc=null);return 0}catch(m){return"undefined"!==typeof N&&m instanceof E||v(m),-m.Mb}},Q:function(a,b){P=b;try{var c=R(),d=Q();a:{var f=Q();for(b=a=0;b<f;b++){var g=x[d+(8*b+4)>>2],h=$b(c,x[d+8*b>>2],g,void 0);if(0>h){var m=-1;break a}a+=h;if(h<g)break}m=a}return m}catch(q){return"undefined"!==typeof N&&q instanceof E||v(q),-q.Mb}},P:function(a,b){P=b;try{var c=R(),d=Q();a:{var f=Q();for(b=a=0;b<f;b++){var g=ac(c,x[d+8*b>>2],x[d+(8*b+4)>>2],
void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(m){return"undefined"!==typeof N&&m instanceof E||v(m),-m.Mb}},O:function(a,b){P=b;try{var c=ic(),d=Q();return hc(Vb,c,d)}catch(f){return"undefined"!==typeof N&&f instanceof E||v(f),-f.Mb}},ua:function(a,b){P=b;try{var c=ic(),d=Q();return hc(Wb,c,d)}catch(f){return"undefined"!==typeof N&&f instanceof E||v(f),-f.Mb}},ta:function(a,b){P=b;try{var c=R(),d=Q();return hc(Vb,c.path,d)}catch(f){return"undefined"!==typeof N&&f instanceof E||v(f),-f.Mb}},
sa:function(a,b){P=b;return 0},ra:function(a,b){P=b;try{var c=R(),d=Q(),f=Q();if(!c.kc){var g=L(c.path,{pc:!0}).node;if(!g.Jb.readdir)throw new E(20);var h=g.Jb.readdir(g);c.kc=h}a=0;for(var m=Zb(c,0,1),q=Math.floor(m/280);q<c.kc.length&&a+280<=f;){var n=c.kc[q];if("."===n[0]){var p=1;var y=4}else{var F=I(c.node,n);p=F.id;y=8192===(F.mode&61440)?2:H(F.mode)?4:40960===(F.mode&61440)?10:8}e=[p>>>0,(k=p,1<=+Ma(k)?0<k?(Pa(+Oa(k/4294967296),4294967295)|0)>>>0:~~+Na((k-+(~~k>>>0))/4294967296)>>>0:0)];x[d+
a>>2]=e[0];x[d+a+4>>2]=e[1];e=[280*(q+1)>>>0,(k=280*(q+1),1<=+Ma(k)?0<k?(Pa(+Oa(k/4294967296),4294967295)|0)>>>0:~~+Na((k-+(~~k>>>0))/4294967296)>>>0:0)];x[d+a+8>>2]=e[0];x[d+a+12>>2]=e[1];za[d+a+16>>1]=280;A[d+a+18>>0]=y;va(n,B,d+a+19,256);a+=280;q+=1}Zb(c,280*q,0);return a}catch(z){return"undefined"!==typeof N&&z instanceof E||v(z),-z.Mb}},k:function(a,b){P=b;try{var c=R();switch(Q()){case 0:var d=Q();return 0>d?-22:Xb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=
Q(),c.flags|=d,0;case 12:return d=Q(),za[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return jb(22),-1;default:return-22}}catch(f){return"undefined"!==typeof N&&f instanceof E||v(f),-f.Mb}},qa:function(a,b){P=b;try{var c=R(),d=Q(),f=Q();return $b(c,d,f)}catch(g){return"undefined"!==typeof N&&g instanceof E||v(g),-g.Mb}},pa:function(a,b){P=b;try{var c=ic();var d=Q();if(d&-8)var f=-22;else{var g=L(c,{pc:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");f=a&&Ib(g,a)?-13:
0}return f}catch(h){return"undefined"!==typeof N&&h instanceof E||v(h),-h.Mb}},oa:function(a,b){P=b;try{var c=ic(),d=ic(),f=fb(c),g=fb(d),h=gb(c),m=gb(d);try{var q=L(c,{parent:!0});var n=q.node;q=L(d,{parent:!0});var p=q.node}catch(O){throw new E(16);}if(!n||!p)throw new E(2);if(n.Sb!==p.Sb)throw new E(18);var y=I(n,h),F=lb(c,g);if("."!==F.charAt(0))throw new E(22);F=lb(d,f);if("."!==F.charAt(0))throw new E(39);try{var z=I(p,m)}catch(O){}if(y!==z){var Ta=H(y.mode),wa=Nb(n,h,Ta);if(wa)throw new E(wa);
if(wa=z?Nb(p,m,Ta):Mb(p,m))throw new E(wa);if(!n.Jb.rename)throw new E(1);if(y.fc||z&&z.fc)throw new E(16);if(p!==n&&(wa=Ib(n,"w")))throw new E(wa);try{K.willMovePath&&K.willMovePath(c,d)}catch(O){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+O.message)}Hb(y);try{n.Jb.rename(y,p,m)}catch(O){throw O;}finally{Gb(y)}try{if(K.onMovePath)K.onMovePath(c,d)}catch(O){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+O.message)}}return 0}catch(O){return"undefined"!==
typeof N&&O instanceof E||v(O),-O.Mb}},ma:function(a,b){P=b;try{var c=R(),d=Q(),f=Q();return ac(c,d,f)}catch(g){return"undefined"!==typeof N&&g instanceof E||v(g),-g.Mb}},N:function(a,b){P=b;try{var c=ic(),d=L(c,{parent:!0}).node,f=gb(c),g=I(d,f),h=Nb(d,f,!0);if(h)throw new E(h);if(!d.Jb.rmdir)throw new E(1);if(g.fc)throw new E(16);try{K.willDeletePath&&K.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Jb.rmdir(d,f);Hb(g);try{if(K.onDeletePath)K.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof N&&m instanceof E||v(m),-m.Mb}},M:function(a,b){P=b;try{var c=ic(),d=Q(),f=Q();return Xb(c,d,f).fd}catch(g){return"undefined"!==typeof N&&g instanceof E||v(g),-g.Mb}},x:function(a,b){P=b;try{var c=R(),d=Q();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var f=Q();return x[f>>2]=0;case 21520:return c.tty?
-22:-25;case 21531:a=f=Q();if(!c.Lb.jd)throw new E(25);return c.Lb.jd(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:v("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof N&&g instanceof E||v(g),-g.Mb}},r:function(a,b){P=b;try{var c=R();if(null===c.fd)throw new E(9);c.kc&&(c.kc=null);try{c.Lb.close&&c.Lb.close(c)}catch(d){throw d;}finally{zb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof N&&d instanceof E||v(d),-d.Mb}},q:function(){},la:function(a){var b=
jc[a];delete jc[a];var c=b.Ec,d=b.cc,f=b.Nc,g=f.map(function(a){return a.gd}).concat(f.map(function(a){return a.rd}));S([a],g,function(a){var g={};f.forEach(function(b,c){var d=a[c],h=b.dd,m=b.ed,z=a[c+f.length],n=b.qd,q=b.sd;g[b.Zc]={read:function(a){return d.fromWireType(h(m,a))},write:function(a,b){var c=[];n(q,a,z.toWireType(c,b));kc(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);d(a);return b},toWireType:function(a,b){for(var f in g)if(!(f in b))throw new TypeError("Missing field");
var h=c();for(f in g)g[f].write(h,b[f]);null!==a&&a.push(d,h);return h},argPackAdvance:8,readValueFromPointer:lc,Xb:d}]})},ka:function(a,b,c,d,f){var g=uc(c);b=U(b);T(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=A;else if(2===c)d=za;else if(4===c)d=x;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},Xb:null})},L:function(a,b,c,d,f,g,h,m,q,n,p,y,F){p=U(p);
g=X(f,g);m&&(m=X(h,m));n&&(n=X(q,n));F=X(y,F);var z=pc(p);Fc(z,function(){Vc("Cannot construct "+p+" due to unbound types",[d])});S([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.Nb;var f=c.dc}else f=Cc.prototype;b=qc(z,function(){if(Object.getPrototypeOf(this)!==h)throw new wc("Use 'new' to construct "+p);if(void 0===q.jc)throw new wc(p+" has no accessible constructor");var a=q.jc[arguments.length];if(void 0===a)throw new wc("Tried to invoke ctor of "+p+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(q.jc).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var q=new Gc(p,b,h,F,c,g,m,n);c=new W(p,q,!0,!1);f=new W(p+"*",q,!1,!1);var Ta=new W(p+" const*",q,!1,!0);Dc[a]={pointerType:f,Xc:Ta};Rc(z,b);return[c,f,Ta]})},ja:function(a,b,c,d,f,g){var h=Wc(b,c);f=X(d,f);S([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.Nb.jc&&(a.Nb.jc=[]);if(void 0!==a.Nb.jc[b-1])throw new wc("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.Nb.jc[b-1]=function(){Vc("Cannot construct "+a.name+" due to unbound types",h)};S([],h,function(d){a.Nb.jc[b-1]=function(){arguments.length!==b-1&&V(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var m=1;m<b;++m)h[m]=d[m].toWireType(a,arguments[m-1]);h=f.apply(null,h);kc(a);return d[0].fromWireType(h)};return[]});return[]})},
p:function(a,b,c,d,f,g,h,m){var q=Wc(c,d);b=U(b);g=X(f,g);S([],[a],function(a){function d(){Vc("Cannot call "+f+" due to unbound types",q)}a=a[0];var f=a.name+"."+b;m&&a.Nb.md.push(b);var n=a.Nb.dc,z=n[b];void 0===z||void 0===z.Tb&&z.className!==a.name&&z.uc===c-2?(d.uc=c-2,d.className=a.name,n[b]=d):(Ec(n,b,f),n[b].Tb[c-2]=d);S([],q,function(d){d=Yc(f,d,a,g,h);void 0===n[b].Tb?(d.uc=c-2,n[b]=d):n[b].Tb[c-2]=d;return[]});return[]})},o:function(a,b,c,d,f,g,h,m,q,n){b=U(b);f=X(d,f);S([],[a],function(a){a=
a[0];var d=a.name+"."+b,p={get:function(){Vc("Cannot access "+d+" due to unbound types",[c,h])},enumerable:!0,configurable:!0};q?p.set=function(){Vc("Cannot access "+d+" due to unbound types",[c,h])}:p.set=function(){V(d+" is a read-only property")};Object.defineProperty(a.Nb.dc,b,p);S([],q?[c,h]:[c],function(c){var h=c[0],z={get:function(){var b=Zc(this,a,d+" getter");return h.fromWireType(f(g,b))},enumerable:!0};if(q){q=X(m,q);var p=c[1];z.set=function(b){var c=Zc(this,a,d+" setter"),f=[];q(n,c,
p.toWireType(f,b));kc(f)}}Object.defineProperty(a.Nb.dc,b,z);return[]});return[]})},ha:function(a,b){b=U(b);T(a,{name:b,fromWireType:function(a){var b=Z[a].value;ad(a);return b},toWireType:function(a,b){return Lc(b)},argPackAdvance:8,readValueFromPointer:lc,Xb:null})},K:function(a,b,c,d){function f(){}c=uc(c);b=U(b);f.values={};T(a,{name:b,constructor:f,fromWireType:function(a){return this.constructor.values[a]},toWireType:function(a,b){return b.value},argPackAdvance:8,readValueFromPointer:bd(b,c,
d),Xb:null});Fc(b,f)},J:function(a,b,c){var d=cd(a,"enum");b=U(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:qc(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},I:function(a,b,c){c=uc(c);b=U(b);T(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Jc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:dd(b,c),Xb:null})},w:function(a,
b,c,d,f,g){var h=Wc(b,c);a=U(a);f=X(d,f);Fc(a,function(){Vc("Cannot call "+a+" due to unbound types",h)},b-1);S([],h,function(c){c=[c[0],null].concat(c.slice(1));Rc(a,Yc(a,c,null,f,g),b-1);return[]})},j:function(a,b,c,d,f){function g(a){return a}b=U(b);-1===f&&(f=4294967295);var h=uc(c);if(0===d){var m=32-8*c;g=function(a){return a<<m>>>m}}var q=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+
Jc(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Jc(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return q?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:ed(b,h,0!==d),Xb:null})},i:function(a,b,c){function d(a){a>>=2;var b=C;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{hd:!0})},H:function(a,b){b=U(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(a){var b=C[a>>2];if(c){var d=B[a+4+b],h=0;0!=d&&(h=d,B[a+4+b]=0);var m=a+4;for(d=0;d<=b;++d){var q=a+4+d;if(0==B[q]){m=ua(m);if(void 0===n)var n=m;else n+=String.fromCharCode(0),n+=m;m=q+1}}0!=h&&(B[a+4+b]=h)}else{n=Array(b);for(d=0;d<b;++d)n[d]=String.fromCharCode(B[a+4+d]);n=n.join("")}Y(a);return n},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===
typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(c&&d?function(){return xa(b)}:function(){return b.length})(),m=ra(4+f+1);C[m>>2]=f;if(c&&d)va(b,B,m+4,f+1);else if(d)for(d=0;d<f;++d){var q=b.charCodeAt(d);255<q&&(Y(m),V("String has UTF-16 code units that do not fit in 8 bits"));B[m+4+d]=q}else for(d=0;d<f;++d)B[m+4+d]=b[d];null!==a&&a.push(Y,m);return m},argPackAdvance:8,readValueFromPointer:lc,Xb:function(a){Y(a)}})},
fa:function(a,b,c){c=U(c);if(2===b){var d=function(){return Aa};var f=1}else 4===b&&(d=function(){return C},f=2);T(a,{name:c,fromWireType:function(a){for(var b=d(),c=C[a>>2],g=Array(c),n=a+4>>f,p=0;p<c;++p)g[p]=String.fromCharCode(b[n+p]);Y(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,n=ra(4+h*b);C[n>>2]=h;for(var p=n+4>>f,y=0;y<h;++y)g[p+y]=c.charCodeAt(y);null!==a&&a.push(Y,n);return n},argPackAdvance:8,readValueFromPointer:lc,Xb:function(a){Y(a)}})},ea:function(a,b,c,d,f,
g){jc[a]={name:U(b),Ec:X(c,d),cc:X(f,g),Nc:[]}},G:function(a,b,c,d,f,g,h,m,q,n){jc[a].Nc.push({Zc:U(b),gd:c,dd:X(d,f),ed:g,rd:h,qd:X(m,q),sd:n})},da:function(a,b){b=U(b);T(a,{Dd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ca:ad,ba:function(a){4<a&&(Z[a].Gc+=1)},F:function(a,b){a=cd(a,"_emval_take_value");a=a.readValueFromPointer(b);return Lc(a)},b:function(){l.abort()},aa:fd,$:function(a,b){if(0===a)a=Date.now();else if(1===a&&(t||"undefined"!==typeof dateNow||
"object"===typeof performance&&performance&&"function"===typeof performance.now))a=gd();else return jb(22),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_:la,Z:function(a,b,c){B.set(B.subarray(b,b+c),a)},Y:ma,v:function(a){if(!l.noExitRuntime&&(pa=!0,l.onExit))l.onExit(a);l.quit(a,new ha(a))},X:Ma,n:id,W:function(a){var b=Date.now();x[a>>2]=b/1E3|0;x[a+4>>2]=b%1E3*1E3|0;return 0},D:function(a,b){a=new Date(1E3*x[a>>2]);x[b>>2]=a.getUTCSeconds();x[b+4>>2]=a.getUTCMinutes();x[b+8>>2]=a.getUTCHours();
x[b+12>>2]=a.getUTCDate();x[b+16>>2]=a.getUTCMonth();x[b+20>>2]=a.getUTCFullYear()-1900;x[b+24>>2]=a.getUTCDay();x[b+36>>2]=0;x[b+32>>2]=0;x[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;x[b+40>>2]=3406528;return b},e:jd,h:function(a){return jd(a)},V:kd,g:function(a){return kd(a)},f:ld,m:function(a){return ld(a)},u:function(a){var b=md.Ub[a];md.Ub.splice(a,1);Ad(b)},B:md,U:Qa,t:function(a,b){od();a=new Date(1E3*x[a>>2]);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+
8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);x[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;x[b+32>>2]=a;a=x[sd()+(a?4:0)>>2];x[b+40>>2]=a;return b},T:function(a){od();var b=new Date(x[a+20>>2]+1900,x[a+16>>2],x[a+12>>2],x[a+8>>2],x[a+
4>>2],x[a>>2],0),c=x[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(2E3,6,1)).getTimezoneOffset(),h=f.getTimezoneOffset(),m=Math.min(h,g);0>c?x[a+32>>2]=Number(g!=h&&m==d):0<c!=(m==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));x[a+24>>2]=b.getDay();x[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},A:function(a,b){var c=x[a>>2];a=x[a+4>>2];0!==b&&(x[b>>2]=0,x[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((ba||ca)&&self.performance&&self.performance.now)for(c=
self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},s:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,
11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=xd(new Date(a.Rb+1900,0,1),a.zc);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=h(m(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var n=x[d+40>>2];d={xd:x[d>>2],wd:x[d+4>>2],yc:x[d+
8>>2],lc:x[d+12>>2],hc:x[d+16>>2],Rb:x[d+20>>2],Wc:x[d+24>>2],zc:x[d+28>>2],Fd:x[d+32>>2],vd:x[d+36>>2],yd:n?ua(n):""};c=ua(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),F="January February March April May June July August September October November December".split(" ");
n={"%a":function(a){return y[a.Wc].substring(0,3)},"%A":function(a){return y[a.Wc]},"%b":function(a){return F[a.hc].substring(0,3)},"%B":function(a){return F[a.hc]},"%C":function(a){return g((a.Rb+1900)/100|0,2)},"%d":function(a){return g(a.lc,2)},"%e":function(a){return f(a.lc,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return g(a.yc,2)},"%I":function(a){a=a.yc;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.lc+ud(td(a.Rb+
1900)?vd:wd,a.hc-1),3)},"%m":function(a){return g(a.hc+1,2)},"%M":function(a){return g(a.wd,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.yc&&12>a.yc?"AM":"PM"},"%S":function(a){return g(a.xd,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Rb+1900,a.hc+1,a.lc,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Rb+1900,0,1),c=0===b.getDay()?b:xd(b,7-b.getDay());a=new Date(a.Rb+1900,a.hc,a.lc);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ud(td(a.getFullYear())?
vd:wd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.Rb+1900,0,4)),c=m(new Date(a.Rb+1901,0,4)),d=xd(new Date(a.Rb+1900,0,1),a.zc);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Rb+1900?a.zc+32-b.getDate():a.zc+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Rb+1900,a.hc+1,a.lc,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Rb,0,1),c=1===b.getDay()?b:xd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Rb+1900,a.hc,
a.lc);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ud(td(a.getFullYear())?vd:wd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.Rb+1900).toString().substring(2)},"%Y":function(a){return a.Rb+1900},"%z":function(a){a=a.vd;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.yd},"%%":function(){return"%"}};for(p in n)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));p=qb(c,!1);if(p.length>b)return 0;
A.set(p,a);return p.length-1},S:function(a){var b=Date.now()/1E3|0;a&&(x[a>>2]=b);return b},R:function(){v("OOM")},a:ka},buffer);l.asm=Bd;l.___errno_location=function(){return l.asm.va.apply(null,arguments)};
var Uc=l.___getTypeName=function(){return l.asm.wa.apply(null,arguments)},rd=l.__get_daylight=function(){return l.asm.xa.apply(null,arguments)},qd=l.__get_timezone=function(){return l.asm.ya.apply(null,arguments)},sd=l.__get_tzname=function(){return l.asm.za.apply(null,arguments)},Y=l._free=function(){return l.asm.Aa.apply(null,arguments)},ra=l._malloc=function(){return l.asm.Ba.apply(null,arguments)},ab=l.globalCtors=function(){return l.asm.Eb.apply(null,arguments)};
l.stackAlloc=function(){return l.asm.Fb.apply(null,arguments)};var Ad=l.stackRestore=function(){return l.asm.Gb.apply(null,arguments)},nd=l.stackSave=function(){return l.asm.Hb.apply(null,arguments)};l.dynCall_dd=function(){return l.asm.Ca.apply(null,arguments)};l.dynCall_did=function(){return l.asm.Da.apply(null,arguments)};l.dynCall_didd=function(){return l.asm.Ea.apply(null,arguments)};l.dynCall_fii=function(){return l.asm.Fa.apply(null,arguments)};
l.dynCall_fiifi=function(){return l.asm.Ga.apply(null,arguments)};l.dynCall_fiii=function(){return l.asm.Ha.apply(null,arguments)};l.dynCall_fiiii=function(){return l.asm.Ia.apply(null,arguments)};l.dynCall_fiiiiiiiiffii=function(){return l.asm.Ja.apply(null,arguments)};l.dynCall_i=function(){return l.asm.Ka.apply(null,arguments)};l.dynCall_ii=function(){return l.asm.La.apply(null,arguments)};l.dynCall_iidiiii=function(){return l.asm.Ma.apply(null,arguments)};
l.dynCall_iii=function(){return l.asm.Na.apply(null,arguments)};l.dynCall_iiifii=function(){return l.asm.Oa.apply(null,arguments)};l.dynCall_iiii=function(){return l.asm.Pa.apply(null,arguments)};l.dynCall_iiiii=function(){return l.asm.Qa.apply(null,arguments)};l.dynCall_iiiiii=function(){return l.asm.Ra.apply(null,arguments)};l.dynCall_iiiiiii=function(){return l.asm.Sa.apply(null,arguments)};l.dynCall_iiiiiiidiiddii=function(){return l.asm.Ta.apply(null,arguments)};
l.dynCall_iiiiiiii=function(){return l.asm.Ua.apply(null,arguments)};l.dynCall_iiiiiiiiii=function(){return l.asm.Va.apply(null,arguments)};l.dynCall_iiiiiiiiiiiiiifii=function(){return l.asm.Wa.apply(null,arguments)};l.dynCall_iiiiij=function(){return l.asm.Xa.apply(null,arguments)};l.dynCall_iiiji=function(){return l.asm.Ya.apply(null,arguments)};l.dynCall_iiijjji=function(){return l.asm.Za.apply(null,arguments)};l.dynCall_iij=function(){return l.asm._a.apply(null,arguments)};
l.dynCall_ijiii=function(){return l.asm.$a.apply(null,arguments)};l.dynCall_jii=function(){return l.asm.ab.apply(null,arguments)};l.dynCall_jiiii=function(){return l.asm.bb.apply(null,arguments)};l.dynCall_jiiij=function(){return l.asm.cb.apply(null,arguments)};l.dynCall_jiiji=function(){return l.asm.db.apply(null,arguments)};l.dynCall_jij=function(){return l.asm.eb.apply(null,arguments)};l.dynCall_jiji=function(){return l.asm.fb.apply(null,arguments)};
l.dynCall_v=function(){return l.asm.gb.apply(null,arguments)};l.dynCall_vi=function(){return l.asm.hb.apply(null,arguments)};l.dynCall_vii=function(){return l.asm.ib.apply(null,arguments)};l.dynCall_viidi=function(){return l.asm.jb.apply(null,arguments)};l.dynCall_viifi=function(){return l.asm.kb.apply(null,arguments)};l.dynCall_viii=function(){return l.asm.lb.apply(null,arguments)};l.dynCall_viiif=function(){return l.asm.mb.apply(null,arguments)};
l.dynCall_viiiff=function(){return l.asm.nb.apply(null,arguments)};l.dynCall_viiii=function(){return l.asm.ob.apply(null,arguments)};l.dynCall_viiiif=function(){return l.asm.pb.apply(null,arguments)};l.dynCall_viiiifii=function(){return l.asm.qb.apply(null,arguments)};l.dynCall_viiiii=function(){return l.asm.rb.apply(null,arguments)};l.dynCall_viiiiii=function(){return l.asm.sb.apply(null,arguments)};l.dynCall_viiiiiiff=function(){return l.asm.tb.apply(null,arguments)};
l.dynCall_viiiiiifi=function(){return l.asm.ub.apply(null,arguments)};l.dynCall_viiiiiii=function(){return l.asm.vb.apply(null,arguments)};l.dynCall_viiiiiiifi=function(){return l.asm.wb.apply(null,arguments)};l.dynCall_viiiiiiii=function(){return l.asm.xb.apply(null,arguments)};l.dynCall_viiiiiiiii=function(){return l.asm.yb.apply(null,arguments)};l.dynCall_viiiiiiiiii=function(){return l.asm.zb.apply(null,arguments)};l.dynCall_viiiiiiiiiii=function(){return l.asm.Ab.apply(null,arguments)};
l.dynCall_viiiiiiiiiiii=function(){return l.asm.Bb.apply(null,arguments)};l.dynCall_viiiiiiiiiiiiii=function(){return l.asm.Cb.apply(null,arguments)};l.dynCall_viiijj=function(){return l.asm.Db.apply(null,arguments)};l.asm=Bd;l.then=function(a){if(l.calledRun)a(l);else{var b=l.onRuntimeInitialized;l.onRuntimeInitialized=function(){b&&b();a(l)}}return l};function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ha.prototype=Error();
ha.prototype.constructor=ha;Ua=function Cd(){l.calledRun||Dd();l.calledRun||(Ua=Cd)};
function Dd(){function a(){if(!l.calledRun&&(l.calledRun=!0,!pa)){Ka||(Ka=!0,l.noFSInit||cc||(cc=!0,bc(),l.stdin=l.stdin,l.stdout=l.stdout,l.stderr=l.stderr,l.stdin?ec("stdin",l.stdin):Ub("/dev/tty","/dev/stdin"),l.stdout?ec("stdout",null,l.stdout):Ub("/dev/tty","/dev/stdout"),l.stderr?ec("stderr",null,l.stderr):Ub("/dev/tty1","/dev/stderr"),Xb("/dev/stdin","r"),Xb("/dev/stdout","w"),Xb("/dev/stderr","w")),Fa(Ha));Cb=!1;Fa(Ia);if(l.onRuntimeInitialized)l.onRuntimeInitialized();if(l.postRun)for("function"==
typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();Ja.unshift(a)}Fa(Ja)}}if(!(0<Ra)){if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)La();Fa(Ga);0<Ra||l.calledRun||(l.setStatus?(l.setStatus("Running..."),setTimeout(function(){setTimeout(function(){l.setStatus("")},1);a()},1)):a())}}l.run=Dd;
function v(a){if(l.onAbort)l.onAbort(a);void 0!==a?(ia(a),w(a),a=JSON.stringify(a)):a="";pa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}l.abort=v;if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.pop()();l.noExitRuntime=!0;Dd();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    