
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var e;e||(e=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa={},h;for(h in e)e.hasOwnProperty(h)&&(aa[h]=e[h]);var ba="./this.program";function ca(a,b){throw b;}var da=!1,l=!1,ea=!1,fa=!1,ha=!1;da="object"===typeof window;l="function"===typeof importScripts;ea=(fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!da&&!l;ha=!da&&!ea&&!l;var n="",ia,ja;
if(ea){n=__dirname+"/";var ka,la;ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);a=ka.readFileSync(a);return b?a:a.toString()};ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;});process.on("unhandledRejection",r);ca=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=
typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(ca=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||l)l?n=self.location.href:document.currentScript&&(n=document.currentScript.src),_scriptDir&&
(n=_scriptDir),0!==n.indexOf("blob:")?n=n.substr(0,n.lastIndexOf("/")+1):n="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var na=e.print||console.log.bind(console),t=e.printErr||console.warn.bind(console);for(h in aa)aa.hasOwnProperty(h)&&(e[h]=aa[h]);aa=null;e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);
function oa(a){var b=u[pa>>2];a=b+a+15&-16;a>qa()&&r();u[pa>>2]=a;return b}var sa={"f64-rem":function(a,b){return a%b},"debugger":function(){}},ta;e.wasmBinary&&(ta=e.wasmBinary);var ua;e.noExitRuntime&&(ua=e.noExitRuntime);"object"!==typeof WebAssembly&&t("no native wasm support detected");var va,wa=!1;function assert(a,b){a||r("Assertion failed: "+b)}
function xa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=ya(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)u[a>>2]=0;for(b=d+c;a<b;)w[a++>>0]=0;return d}a.subarray||a.slice?z.set(a,d):z.set(new Uint8Array(a),d);return d}var za="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Aa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function A(a){return a?Aa(z,a,void 0):""}
function Ba(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Da(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,w,z,Ea,Fa,u,C,Ga,Ha;
function Ia(a){buffer=a;e.HEAP8=w=new Int8Array(a);e.HEAP16=Ea=new Int16Array(a);e.HEAP32=u=new Int32Array(a);e.HEAPU8=z=new Uint8Array(a);e.HEAPU16=Fa=new Uint16Array(a);e.HEAPU32=C=new Uint32Array(a);e.HEAPF32=Ga=new Float32Array(a);e.HEAPF64=Ha=new Float64Array(a)}var pa=3404192,Ja=e.TOTAL_MEMORY||16777216;e.wasmMemory?va=e.wasmMemory:va=new WebAssembly.Memory({initial:Ja/65536});va&&(buffer=va.buffer);Ja=buffer.byteLength;Ia(buffer);u[pa>>2]=8647104;
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.vc;"number"===typeof c?void 0===b.cc?e.dynCall_v(c):e.dynCall_vi(c,b.cc):c(void 0===b.cc?null:b.cc)}}}var La=[],Ma=[],Na=[],Oa=[],Pa=!1;function Qa(){var a=e.preRun.shift();La.unshift(a)}var Ra=Math.abs,Sa=Math.ceil,Ta=Math.floor,Ua=Math.min,Va=Math.trunc,Wa=0,Xa=null,Ya=null;e.preloadedImages={};e.preloadedAudios={};
function Za(){var a=$a;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var $a="ffmpeg.wasm";if(!Za()){var ab=$a;$a=e.locateFile?e.locateFile(ab,n):n+ab}function bb(){try{if(ta)return new Uint8Array(ta);if(ja)return ja($a);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}
function cb(){return ta||!da&&!l||"function"!==typeof fetch?new Promise(function(a){a(bb())}):fetch($a,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+$a+"'";return a.arrayBuffer()}).catch(function(){return bb()})}
function db(a){function b(a){e.asm=a.exports;Wa--;e.monitorRunDependencies&&e.monitorRunDependencies(Wa);0==Wa&&(null!==Xa&&(clearInterval(Xa),Xa=null),Ya&&(a=Ya,Ya=null,a()))}function c(a){b(a.instance)}function d(a){return cb().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){t("failed to asynchronously prepare wasm: "+a);r(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:sa};Wa++;e.monitorRunDependencies&&e.monitorRunDependencies(Wa);if(e.instantiateWasm)try{return e.instantiateWasm(f,
b)}catch(g){return t("Module.instantiateWasm callback failed with error: "+g),!1}(function(){if(ta||"function"!==typeof WebAssembly.instantiateStreaming||Za()||"function"!==typeof fetch)return d(c);fetch($a,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,f).then(c,function(a){t("wasm streaming compile failed: "+a);t("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}
e.asm=function(a,b){b.memory=va;b.table=new WebAssembly.Table({initial:5880,maximum:5880,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return db(b)};var D,F;Ma.push({vc:function(){eb()}});var G={};
function fb(a){if(fb.Fb){var b=u[a>>2];var c=u[b>>2]}else fb.Fb=!0,G.USER=G.LOGNAME="web_user",G.PATH="/",G.PWD="/",G.HOME="/home/web_user",G.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",G._=ba,c=Pa?ya(1024):oa(1024),b=Pa?ya(256):oa(256),u[b>>2]=c,u[a>>2]=b;a=[];var d=0,f;for(f in G)if("string"===typeof G[f]){var g=f+"="+G[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=
g=a[f];for(var k=c,m=0;m<d.length;++m)w[k++>>0]=d.charCodeAt(m);w[k>>0]=0;u[b+4*f>>2]=c;c+=g.length+1}u[b+4*a.length>>2]=0}function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function kb(){var a=Array.prototype.slice.call(arguments,0);return hb(a.join("/"))}function lb(a,b){return hb(a+"/"+b)}function mb(a){e.___errno_location&&(u[e.___errno_location()>>2]=a);return a}
function nb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function ob(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=nb(a).substr(1);b=nb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var pb=[];function qb(a,b){pb[a]={input:[],output:[],Tb:b};rb(a,sb)}
var sb={open:function(a){var b=pb[a.node.rdev];if(!b)throw new H(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.Tb.flush(a.tty)},flush:function(a){a.tty.Tb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Tb.pc)throw new H(6);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Tb.pc(a.tty)}catch(m){throw new H(5);}if(void 0===k&&0===f)throw new H(11);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Tb.ec)throw new H(6);
try{for(var f=0;f<d;f++)a.tty.Tb.ec(a.tty,b[c+f])}catch(g){throw new H(5);}d&&(a.node.timestamp=Date.now());return f}},ub={pc:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.Fb?Buffer.Fb(256):new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=
typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=tb(b,!0)}return a.input.shift()},ec:function(a,b){null===b||10===b?(na(Aa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(Aa(a.output,0)),a.output=[])}},vb={ec:function(a,b){null===b||10===b?(t(Aa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(t(Aa(a.output,0)),a.output=[])}},I={Lb:null,Gb:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(1);I.Lb||(I.Lb={dir:{node:{Jb:I.Ab.Jb,Kb:I.Ab.Kb,lookup:I.Ab.lookup,Wb:I.Ab.Wb,rename:I.Ab.rename,unlink:I.Ab.unlink,rmdir:I.Ab.rmdir,readdir:I.Ab.readdir,symlink:I.Ab.symlink},stream:{Ob:I.Cb.Ob}},file:{node:{Jb:I.Ab.Jb,Kb:I.Ab.Kb},stream:{Ob:I.Cb.Ob,read:I.Cb.read,write:I.Cb.write,ic:I.Cb.ic,qc:I.Cb.qc,
sc:I.Cb.sc}},link:{node:{Jb:I.Ab.Jb,Kb:I.Ab.Kb,readlink:I.Ab.readlink},stream:{}},kc:{node:{Jb:I.Ab.Jb,Kb:I.Ab.Kb},stream:wb}});c=xb(a,b,c,d);K(c.mode)?(c.Ab=I.Lb.dir.node,c.Cb=I.Lb.dir.stream,c.Bb={}):32768===(c.mode&61440)?(c.Ab=I.Lb.file.node,c.Cb=I.Lb.file.stream,c.Eb=0,c.Bb=null):40960===(c.mode&61440)?(c.Ab=I.Lb.link.node,c.Cb=I.Lb.link.stream):8192===(c.mode&61440)&&(c.Ab=I.Lb.kc.node,c.Cb=I.Lb.kc.stream);c.timestamp=Date.now();a&&(a.Bb[b]=c);return c},Ic:function(a){if(a.Bb&&a.Bb.subarray){for(var b=
[],c=0;c<a.Eb;++c)b.push(a.Bb[c]);return b}return a.Bb},Jc:function(a){return a.Bb?a.Bb.subarray?a.Bb.subarray(0,a.Eb):new Uint8Array(a.Bb):new Uint8Array},lc:function(a,b){var c=a.Bb?a.Bb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Bb,a.Bb=new Uint8Array(b),0<a.Eb&&a.Bb.set(c.subarray(0,a.Eb),0))},zc:function(a,b){if(a.Eb!=b)if(0==b)a.Bb=null,a.Eb=0;else{if(!a.Bb||a.Bb.subarray){var c=a.Bb;a.Bb=new Uint8Array(new ArrayBuffer(b));c&&a.Bb.set(c.subarray(0,Math.min(b,
a.Eb)))}else if(a.Bb||(a.Bb=[]),a.Bb.length>b)a.Bb.length=b;else for(;a.Bb.length<b;)a.Bb.push(0);a.Eb=b}},Ab:{Jb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Eb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qb=4096;b.blocks=Math.ceil(b.size/b.Qb);return b},Kb:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.zc(a,b.size)},lookup:function(){throw yb[2];},Wb:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=L(b,c)}catch(g){}if(d)for(var f in d.Bb)throw new H(39);}delete a.parent.Bb[a.name];a.name=c;b.Bb[c]=a;a.parent=b},unlink:function(a,b){delete a.Bb[b]},rmdir:function(a,b){var c=L(a,b),d;for(d in c.Bb)throw new H(39);delete a.Bb[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.Bb)a.Bb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(22);return a.link}},Cb:{read:function(a,b,c,d,f){var g=a.node.Bb;if(f>=a.node.Eb)return 0;a=Math.min(a.node.Eb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.Bb||a.Bb.subarray)){if(g)return a.Bb=b.subarray(c,c+d),a.Eb=d;if(0===a.Eb&&0===f)return a.Bb=new Uint8Array(b.subarray(c,c+d)),a.Eb=d;if(f+d<=a.Eb)return a.Bb.set(b.subarray(c,c+d),f),d}I.lc(a,f+d);if(a.Bb.subarray&&b.subarray)a.Bb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Bb[f+g]=b[c+g];a.Eb=Math.max(a.Eb,f+d);return d},Ob:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Eb);if(0>b)throw new H(22);return b},ic:function(a,b,c){I.lc(a.node,b+c);a.node.Eb=
Math.max(a.node.Eb,b+c)},qc:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new H(19);c=a.node.Bb;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Eb)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;f=b.buffer==w.buffer;d=ya(d);if(!d)throw new H(12);(f?w:b).set(c,d)}else a=!1,d=c.byteOffset;return{Mc:d,Hc:a}},sc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new H(19);if(f&2)return 0;I.Cb.write(a,b,0,d,c,!1);return 0}}},M={Zb:!1,Bc:function(){M.Zb=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);M.mc={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},jc:function(a){return Buffer.Fb?Buffer.from(a):new Buffer(a)},Gb:function(a){assert(fa);return M.createNode(null,"/",M.oc(a.dc.root),0)},createNode:function(a,b,c){if(!K(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(22);a=xb(a,b,c);a.Ab=M.Ab;a.Cb=M.Cb;return a},oc:function(a){try{var b=fs.lstatSync(a);
M.Zb&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new H(-c.Db);}return b.mode},Ib:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Gb.dc.root);b.reverse();return kb.apply(null,b)},uc:function(a){a&=-2656257;var b=0,c;for(c in M.mc)a&c&&(b|=M.mc[c],a^=c);if(a)throw new H(22);return b},Ab:{Jb:function(a){a=M.Ib(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.Db);}M.Zb&&!b.Qb&&(b.Qb=4096);M.Zb&&!b.blocks&&(b.blocks=(b.size+b.Qb-1)/
b.Qb|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Qb:b.Qb,blocks:b.blocks}},Kb:function(a,b){var c=M.Ib(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(-d.Db);}},lookup:function(a,b){var c=lb(M.Ib(a),b);c=M.oc(c);return M.createNode(a,b,c)},Wb:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.Ib(a);try{K(a.mode)?
fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new H(-f.Db);}return a},rename:function(a,b,c){a=M.Ib(a);b=lb(M.Ib(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(-d.Db);}},unlink:function(a,b){a=lb(M.Ib(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.Db);}},rmdir:function(a,b){a=lb(M.Ib(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.Db);}},readdir:function(a){a=M.Ib(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new H(-b.Db);}},symlink:function(a,b,c){a=lb(M.Ib(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(-d.Db);}},readlink:function(a){var b=M.Ib(a);try{return b=fs.readlinkSync(b),b=zb.relative(zb.resolve(a.Gb.dc.root),b)}catch(c){if(!c.code)throw c;throw new H(-c.Db);}}},Cb:{open:function(a){var b=M.Ib(a.node);try{32768===(a.node.mode&61440)&&(a.Xb=fs.openSync(b,M.uc(a.flags)))}catch(c){if(!c.code)throw c;throw new H(-c.Db);}},close:function(a){try{32768===(a.node.mode&61440)&&
a.Xb&&fs.closeSync(a.Xb)}catch(b){if(!b.code)throw b;throw new H(-b.Db);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.Xb,M.jc(b.buffer),c,d,f)}catch(g){throw new H(-g.Db);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.Xb,M.jc(b.buffer),c,d,f)}catch(g){throw new H(-g.Db);}},Ob:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Xb).size}catch(d){throw new H(-d.Db);}if(0>b)throw new H(22);return b}}},Ab=null,Bb={},
Cb=[],Db=1,Eb=null,Fb=!0,N={},H=null,yb={};
function O(a,b){a=nb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={nc:!0,fc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.fc)throw new H(40);a=gb(a.split("/").filter(function(a){return!!a}),!1);var f=Ab;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=L(f,a[d]);c=lb(c,a[d]);f.Pb&&(!g||g&&b.nc)&&(f=f.Pb.root);if(!g||b.Vb)for(g=0;40960===(f.mode&61440);)if(f=Gb(c),c=nb(ib(c),f),f=O(c,{fc:b.fc}).node,40<g++)throw new H(40);}return{path:c,node:f}}
function Hb(a){for(var b;;){if(a===a.parent)return a=a.Gb.rc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Eb.length}function Jb(a){var b=Ib(a.parent.id,a.name);a.Sb=Eb[b];Eb[b]=a}function Kb(a){var b=Ib(a.parent.id,a.name);if(Eb[b]===a)Eb[b]=a.Sb;else for(b=Eb[b];b;){if(b.Sb===a){b.Sb=a.Sb;break}b=b.Sb}}
function L(a,b){var c;if(c=(c=Lb(a,"x"))?c:a.Ab.lookup?0:13)throw new H(c,a);for(c=Eb[Ib(a.id,b)];c;c=c.Sb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ab.lookup(a,b)}
function xb(a,b,c,d){Mb||(Mb=function(a,b,c,d){a||(a=this);this.parent=a;this.Gb=a.Gb;this.Pb=null;this.id=Db++;this.name=b;this.mode=c;this.Ab={};this.Cb={};this.rdev=d},Mb.prototype={},Object.defineProperties(Mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Mb(a,b,c,d);Jb(a);return a}
function K(a){return 16384===(a&61440)}var Nb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Lb(a,b){if(Fb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Pb(a,b){try{return L(a,b),17}catch(c){}return Lb(a,"wx")}
function Qb(a,b,c){try{var d=L(a,b)}catch(f){return f.Db}if(a=Lb(a,"wx"))return a;if(c){if(!K(d.mode))return 20;if(d===d.parent||"/"===Hb(d))return 16}else if(K(d.mode))return 21;return 0}function Rb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Cb[a])return a;throw new H(24);}
function Sb(a,b){Tb||(Tb=function(){},Tb.prototype={},Object.defineProperties(Tb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Tb,d;for(d in a)c[d]=a[d];a=c;b=Rb(b);a.fd=b;return Cb[b]=a}var wb={open:function(a){a.Cb=Bb[a.node.rdev].Cb;a.Cb.open&&a.Cb.open(a)},Ob:function(){throw new H(29);}};function rb(a,b){Bb[a]={Cb:b}}
function Ub(a,b){var c="/"===b,d=!b;if(c&&Ab)throw new H(16);if(!c&&!d){var f=O(b,{nc:!1});b=f.path;f=f.node;if(f.Pb)throw new H(16);if(!K(f.mode))throw new H(20);}b={type:a,dc:{},rc:b,yc:[]};a=a.Gb(b);a.Gb=b;b.root=a;c?Ab=a:f&&(f.Pb=b,f.Gb&&f.Gb.yc.push(b))}function Vb(a,b,c){var d=O(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new H(22);var f=Pb(d,a);if(f)throw new H(f);if(!d.Ab.Wb)throw new H(1);return d.Ab.Wb(d,a,b,c)}function P(a){Vb(a,16895,0)}
function Wb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Vb(a,b|8192,c)}function Xb(a,b){if(!nb(a))throw new H(2);var c=O(b,{parent:!0}).node;if(!c)throw new H(2);b=jb(b);var d=Pb(c,b);if(d)throw new H(d);if(!c.Ab.symlink)throw new H(1);c.Ab.symlink(c,b,a)}function Gb(a){a=O(a).node;if(!a)throw new H(2);if(!a.Ab.readlink)throw new H(22);return nb(Hb(a.parent),a.Ab.readlink(a))}function Yb(a,b){a=O(a,{Vb:!b}).node;if(!a)throw new H(2);if(!a.Ab.Jb)throw new H(1);return a.Ab.Jb(a)}
function Zb(a){return Yb(a,!0)}
function $b(a,b,c,d){if(""===a)throw new H(2);if("string"===typeof b){var f=Nb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=hb(a);try{g=O(a,{Vb:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new H(17);}else g=Vb(a,c,0),f=!0;if(!g)throw new H(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!K(g.mode))throw new H(20);if(!f&&(c=g?40960===(g.mode&61440)?40:K(g.mode)&&
("r"!==Ob(b)||b&512)?21:Lb(g,Ob(b)):2))throw new H(c);if(b&512){c=g;var k;"string"===typeof c?k=O(c,{Vb:!0}).node:k=c;if(!k.Ab.Kb)throw new H(1);if(K(k.mode))throw new H(21);if(32768!==(k.mode&61440))throw new H(22);if(c=Lb(k,"w"))throw new H(c);k.Ab.Kb(k,{size:0,timestamp:Date.now()})}b&=-641;d=Sb({node:g,path:Hb(g),flags:b,seekable:!0,position:0,Cb:g.Cb,Gc:[],error:!1},d);d.Cb.open&&d.Cb.open(d);!e.logReadFiles||b&1||(ac||(ac={}),a in ac||(ac[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{N.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),N.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function bc(a,b,c){if(null===a.fd)throw new H(9);if(!a.seekable||!a.Cb.Ob)throw new H(29);if(0!=c&&1!=c&&2!=c)throw new H(22);a.position=a.Cb.Ob(a,b,c);a.Gc=[];return a.position}
function cc(a,b,c,d){var f=w;if(0>c||0>d)throw new H(22);if(null===a.fd)throw new H(9);if(1===(a.flags&2097155))throw new H(9);if(K(a.node.mode))throw new H(21);if(!a.Cb.read)throw new H(22);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new H(29);b=a.Cb.read(a,f,b,c,d);g||(a.position+=b);return b}
function dc(a,b,c,d){var f=w;if(0>c||0>d)throw new H(22);if(null===a.fd)throw new H(9);if(0===(a.flags&2097155))throw new H(9);if(K(a.node.mode))throw new H(21);if(!a.Cb.write)throw new H(22);a.flags&1024&&bc(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new H(29);b=a.Cb.write(a,f,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&N.onWriteToFile)N.onWriteToFile(a.path)}catch(k){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+k.message)}return b}
function ec(){H||(H=function(a,b){this.node=b;this.Ac=function(a){this.Db=a};this.Ac(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[2].forEach(function(a){yb[a]=new H(a);yb[a].stack="<generic error, no stack>"}))}var fc;function hc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ic(a,b,c){a=lb("/dev",a);var d=hc(!!b,!!c);jc||(jc=64);var f=jc++<<8|0;rb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,k=0;k<f;k++){try{var m=b()}catch(E){throw new H(5);}if(void 0===m&&0===g)throw new H(11);if(null===m||void 0===m)break;g++;c[d+k]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(v){throw new H(5);}f&&(a.node.timestamp=Date.now());return g}});
Wb(a,d,f)}var jc,Q={},Mb,Tb,ac;
function kc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&hb(b)!==hb(Hb(f.node)))return-20;throw f;}u[c>>2]=d.dev;u[c+4>>2]=0;u[c+8>>2]=d.ino;u[c+12>>2]=d.mode;u[c+16>>2]=d.nlink;u[c+20>>2]=d.uid;u[c+24>>2]=d.gid;u[c+28>>2]=d.rdev;u[c+32>>2]=0;F=[d.size>>>0,(D=d.size,1<=+Ra(D)?0<D?(Ua(+Ta(D/4294967296),4294967295)|0)>>>0:~~+Sa((D-+(~~D>>>0))/4294967296)>>>0:0)];u[c+40>>2]=F[0];u[c+44>>2]=F[1];u[c+48>>2]=4096;u[c+52>>2]=d.blocks;u[c+56>>2]=d.atime.getTime()/1E3|0;u[c+60>>2]=0;u[c+64>>2]=d.mtime.getTime()/
1E3|0;u[c+68>>2]=0;u[c+72>>2]=d.ctime.getTime()/1E3|0;u[c+76>>2]=0;F=[d.ino>>>0,(D=d.ino,1<=+Ra(D)?0<D?(Ua(+Ta(D/4294967296),4294967295)|0)>>>0:~~+Sa((D-+(~~D>>>0))/4294967296)>>>0:0)];u[c+80>>2]=F[0];u[c+84>>2]=F[1];return 0}var R=0;function S(){R+=4;return u[R-4>>2]}function lc(){return A(S())}function T(){var a=Cb[S()];if(!a)throw new H(9);return a}function mc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}
var nc=void 0;function U(a){for(var b="";z[a];)b+=nc[z[a++]];return b}var oc={},pc={},qc={};function rc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function sc(a,b){a=rc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function tc(a){var b=Error,c=sc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var uc=void 0;function W(a){throw new uc(a);}var vc=void 0;
function wc(a,b){function c(a){a=b(a);if(a.length!==d.length)throw new vc("Mismatched type converter count");for(var c=0;c<d.length;++c)X(d[c],a[c])}var d=[];d.forEach(function(b){qc[b]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(a,b){pc.hasOwnProperty(a)?f[b]=pc[a]:(g.push(a),oc.hasOwnProperty(a)||(oc[a]=[]),oc[a].push(function(){f[b]=pc[a];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(pc.hasOwnProperty(a)){if(c.wc)return;W("Cannot register type '"+d+"' twice")}pc[a]=b;delete qc[a];oc.hasOwnProperty(a)&&(b=oc[a],delete oc[a],b.forEach(function(a){a()}))}var xc=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function yc(a){4<a&&0===--Y[a].hc&&(Y[a]=void 0,xc.push(a))}function zc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=xc.length?xc.pop():Y.length;Y[b]={hc:1,value:a};return b}}function Ac(a){return this.fromWireType(C[a>>2])}function Bc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Cc(a,b){switch(b){case 2:return function(a){return this.fromWireType(Ga[a>>2])};case 3:return function(a){return this.fromWireType(Ha[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ec(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=sc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Fc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Gc(a,b){var c=e;if(void 0===c[a].Mb){var d=c[a];c[a]=function(){c[a].Mb.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Mb+")!");return c[a].Mb[arguments.length].apply(this,arguments)};c[a].Mb=[];c[a].Mb[d.tc]=d}}
function Hc(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].Mb&&void 0!==e[a].Mb[c])&&W("Cannot register public name '"+a+"' twice"),Gc(a,a),e.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].Mb[c]=b):(e[a]=b,void 0!==c&&(e[a].Lc=c))}function Ic(a,b){for(var c=[],d=0;d<a;d++)c.push(u[(b>>2)+d]);return c}
function Jc(a,b){a=U(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e["dynCall_"+a];void 0===c&&(c=e["dynCall_"+a.replace(/f/g,"d")],void 0===c&&W("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var Kc=void 0;function Lc(a){a=Mc(a);var b=U(a);Z(a);return b}function Nc(a,b){function c(a){f[a]||pc[a]||(qc[a]?qc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Kc(a+": "+d.map(Lc).join([", "]));}
function Oc(a,b,c){switch(b){case 0:return c?function(a){return w[a]}:function(a){return z[a]};case 1:return c?function(a){return Ea[a>>1]}:function(a){return Fa[a>>1]};case 2:return c?function(a){return u[a>>2]}:function(a){return C[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Pc(){void 0===Pc.start&&(Pc.start=Date.now());return 1E3*(Date.now()-Pc.start)|0}function Qc(){r()}function qa(){return w.length}
function Rc(a){if(0===a)return 0;a=A(a);if(!G.hasOwnProperty(a))return 0;Rc.Fb&&Z(Rc.Fb);a=G[a];var b=Ca(a)+1,c=ya(b);c&&Ba(a,w,c,b);Rc.Fb=c;return Rc.Fb}Ba("GMT",z,3404096,4);function Sc(a){return Math.pow(2,a)}function Tc(a){return Math.log(a)/Math.LN10}function Uc(a){return Math.log(a)/Math.LN2}function Vc(){Vc.Fb||(Vc.Fb=[]);Vc.Fb.push(Wc());return Vc.Fb.length-1}
function Xc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Yc){Yc=!0;u[Zc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);u[$c()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=xa(tb(d));f=xa(tb(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(u[ad()>>2]=d,u[ad()+4>>2]=f):(u[ad()>>2]=f,u[ad()+4>>2]=d)}}var Yc;function bd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function cd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var dd=[31,29,31,30,31,30,31,31,30,31,30,31],ed=[31,28,31,30,31,30,31,31,30,31,30,31];function fd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(bd(a.getFullYear())?dd:ed)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}ec();Eb=Array(4096);Ub(I,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");rb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Wb("/dev/null",259);qb(1280,ub);qb(1536,vb);Wb("/dev/tty",1280);Wb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){r("random_device")});ic("random",b);ic("urandom",b);P("/dev/shm");
P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");Ub({Gb:function(){var a=xb("/proc/self","fd",16895,73);a.Ab={lookup:function(a,c){var b=Cb[+c];if(!b)throw new H(9);a={parent:null,Gb:{rc:"fake"},Ab:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(fa){var fs=require("fs"),zb=require("path");M.Bc()}for(var gd=Array(256),hd=0;256>hd;++hd)gd[hd]=String.fromCharCode(hd);nc=gd;uc=e.BindingError=tc("BindingError");vc=e.InternalError=tc("InternalError");
e.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Kc=e.UnboundTypeError=tc("UnboundTypeError");ea?Qc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Qc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Qc=function(){return performance.now()}:Qc=Date.now;
function tb(a,b){var c=Array(Ca(a)+1);a=Ba(a,c,0,c.length);b&&(c.length=a);return c}
var jd=e.asm({},{d:r,l:function(){},c:function(a,b,c,d){r("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},ea:fb,aa:function(){wa=!0;throw"Pure virtual function called!";},A:function(){},y:mb,w:function(a,b){R=b;try{var c=lc(),d=O(c,{parent:!0}).node,f=jb(c),g=L(d,f),k=Qb(d,f,!1);if(k)throw new H(k);if(!d.Ab.unlink)throw new H(1);if(g.Pb)throw new H(16);try{N.willDeletePath&&N.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+
c+"') threw an exception: "+m.message)}d.Ab.unlink(d,f);Kb(g);try{if(N.onDeletePath)N.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof H||r(m),-m.Db}},v:function(a,b){R=b;try{var c=T(),d=S(),f=S(),g=S(),k=S();a=4294967296*d+(f>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-75;bc(c,a,k);F=[c.position>>>0,(D=c.position,1<=+Ra(D)?0<D?(Ua(+Ta(D/4294967296),4294967295)|
0)>>>0:~~+Sa((D-+(~~D>>>0))/4294967296)>>>0:0)];u[g>>2]=F[0];u[g+4>>2]=F[1];c.Rb&&0===a&&0===k&&(c.Rb=null);return 0}catch(m){return"undefined"!==typeof Q&&m instanceof H||r(m),-m.Db}},J:function(a,b){R=b;try{var c=T(),d=S();a:{var f=S();for(b=a=0;b<f;b++){var g=u[d+(8*b+4)>>2],k=cc(c,u[d+8*b>>2],g,void 0);if(0>k){var m=-1;break a}a+=k;if(k<g)break}m=a}return m}catch(y){return"undefined"!==typeof Q&&y instanceof H||r(y),-y.Db}},I:function(a,b){R=b;try{var c=T(),d=S();a:{var f=S();for(b=a=0;b<f;b++){var g=
dc(c,u[d+8*b>>2],u[d+(8*b+4)>>2],void 0);if(0>g){var k=-1;break a}a+=g}k=a}return k}catch(m){return"undefined"!==typeof Q&&m instanceof H||r(m),-m.Db}},H:function(a,b){R=b;try{var c=lc(),d=S();return kc(Yb,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof H||r(f),-f.Db}},la:function(a,b){R=b;try{var c=lc(),d=S();return kc(Zb,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof H||r(f),-f.Db}},ka:function(a,b){R=b;try{var c=T(),d=S();return kc(Yb,c.path,d)}catch(f){return"undefined"!==typeof Q&&
f instanceof H||r(f),-f.Db}},ja:function(a,b){R=b;return 0},ia:function(a,b){R=b;try{var c=T(),d=S(),f=S();if(!c.Rb){var g=O(c.path,{Vb:!0}).node;if(!g.Ab.readdir)throw new H(20);var k=g.Ab.readdir(g);c.Rb=k}a=0;for(var m=bc(c,0,1),y=Math.floor(m/280);y<c.Rb.length&&a+280<=f;){var p=c.Rb[y];if("."===p[0]){var v=1;var x=4}else{var E=L(c.node,p);v=E.id;x=8192===(E.mode&61440)?2:K(E.mode)?4:40960===(E.mode&61440)?10:8}F=[v>>>0,(D=v,1<=+Ra(D)?0<D?(Ua(+Ta(D/4294967296),4294967295)|0)>>>0:~~+Sa((D-+(~~D>>>
0))/4294967296)>>>0:0)];u[d+a>>2]=F[0];u[d+a+4>>2]=F[1];F=[280*(y+1)>>>0,(D=280*(y+1),1<=+Ra(D)?0<D?(Ua(+Ta(D/4294967296),4294967295)|0)>>>0:~~+Sa((D-+(~~D>>>0))/4294967296)>>>0:0)];u[d+a+8>>2]=F[0];u[d+a+12>>2]=F[1];Ea[d+a+16>>1]=280;w[d+a+18>>0]=x;Ba(p,z,d+a+19,256);a+=280;y+=1}bc(c,280*y,0);return a}catch(J){return"undefined"!==typeof Q&&J instanceof H||r(J),-J.Db}},k:function(a,b){R=b;try{var c=T();switch(S()){case 0:var d=S();return 0>d?-22:$b(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;
case 4:return d=S(),c.flags|=d,0;case 12:return d=S(),Ea[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return mb(22),-1;default:return-22}}catch(f){return"undefined"!==typeof Q&&f instanceof H||r(f),-f.Db}},ha:function(a,b){R=b;try{var c=T(),d=S(),f=S();return cc(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof H||r(g),-g.Db}},ga:function(a,b){R=b;try{var c=lc();var d=S();if(d&-8)var f=-22;else{var g;(g=O(c,{Vb:!0}).node)?(a="",d&4&&(a+="r"),d&2&&(a+="w"),d&1&&(a+=
"x"),f=a&&Lb(g,a)?-13:0):f=-2}return f}catch(k){return"undefined"!==typeof Q&&k instanceof H||r(k),-k.Db}},fa:function(a,b){R=b;try{var c=lc(),d=lc(),f=ib(c),g=ib(d),k=jb(c),m=jb(d);try{var y=O(c,{parent:!0});var p=y.node;y=O(d,{parent:!0});var v=y.node}catch(B){throw new H(16);}if(!p||!v)throw new H(2);if(p.Gb!==v.Gb)throw new H(18);var x=L(p,k),E=ob(c,g);if("."!==E.charAt(0))throw new H(22);E=ob(d,f);if("."!==E.charAt(0))throw new H(39);try{var J=L(v,m)}catch(B){}if(x!==J){var q=K(x.mode),V=Qb(p,
k,q);if(V)throw new H(V);if(V=J?Qb(v,m,q):Pb(v,m))throw new H(V);if(!p.Ab.rename)throw new H(1);if(x.Pb||J&&J.Pb)throw new H(16);if(v!==p&&(V=Lb(p,"w")))throw new H(V);try{N.willMovePath&&N.willMovePath(c,d)}catch(B){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+B.message)}Kb(x);try{p.Ab.rename(x,v,m)}catch(B){throw B;}finally{Jb(x)}try{if(N.onMovePath)N.onMovePath(c,d)}catch(B){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+
B.message)}}return 0}catch(B){return"undefined"!==typeof Q&&B instanceof H||r(B),-B.Db}},da:function(a,b){R=b;try{var c=T(),d=S(),f=S();return dc(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof H||r(g),-g.Db}},G:function(a,b){R=b;try{var c=lc(),d=O(c,{parent:!0}).node,f=jb(c),g=L(d,f),k=Qb(d,f,!0);if(k)throw new H(k);if(!d.Ab.rmdir)throw new H(1);if(g.Pb)throw new H(16);try{N.willDeletePath&&N.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+
m.message)}d.Ab.rmdir(d,f);Kb(g);try{if(N.onDeletePath)N.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof H||r(m),-m.Db}},F:function(a,b){R=b;try{var c=lc(),d=S(),f=S();return $b(c,d,f).fd}catch(g){return"undefined"!==typeof Q&&g instanceof H||r(g),-g.Db}},u:function(a,b){R=b;try{var c=T(),d=S();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-25;case 21519:if(!c.tty)return-25;var f=S();return u[f>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=f=S();if(!c.Cb.xc)throw new H(25);return c.Cb.xc(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:r("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof Q&&g instanceof H||r(g),-g.Db}},p:function(a,b){R=b;try{var c=T();if(null===c.fd)throw new H(9);c.Rb&&(c.Rb=null);try{c.Cb.close&&c.Cb.close(c)}catch(d){throw d;}finally{Cb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==
typeof Q&&d instanceof H||r(d),-d.Db}},o:function(){},ca:function(a,b,c,d,f){var g=mc(c);b=U(b);X(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=w;else if(2===c)d=Ea;else if(4===c)d=u;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},Nb:null})},ba:function(a,b){b=U(b);X(a,{name:b,fromWireType:function(a){var b=Y[a].value;yc(a);return b},toWireType:function(a,
b){return zc(b)},argPackAdvance:8,readValueFromPointer:Ac,Nb:null})},E:function(a,b,c){c=mc(c);b=U(b);X(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Bc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Cc(b,c),Nb:null})},D:function(a,b,c,d,f,g){var k=Ic(b,c);a=U(a);f=Jc(d,f);Hc(a,function(){Nc("Cannot call "+a+" due to unbound types",k)},b-1);wc(k,function(c){var d=[c[0],
null].concat(c.slice(1)),k=c=a,m=f,x=d.length;2>x&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var E=null!==d[1]&&!1,J=!1,q=1;q<d.length;++q)if(null!==d[q]&&void 0===d[q].Nb){J=!0;break}var V="void"!==d[0].name,B="",ra="";for(q=0;q<x-2;++q)B+=(0!==q?", ":"")+"arg"+q,ra+=(0!==q?", ":"")+"arg"+q+"Wired";k="return function "+rc(k)+"("+B+") {\nif (arguments.length !== "+(x-2)+") {\nthrowBindingError('function "+k+" called with ' + arguments.length + ' arguments, expected "+
(x-2)+" args!');\n}\n";J&&(k+="var destructors = [];\n");var Dc=J?"destructors":"null";B="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[W,m,g,Fc,d[0],d[1]];E&&(k+="var thisWired = classParam.toWireType("+Dc+", this);\n");for(q=0;q<x-2;++q)k+="var arg"+q+"Wired = argType"+q+".toWireType("+Dc+", arg"+q+"); // "+d[q+2].name+"\n",B.push("argType"+q),m.push(d[q+2]);E&&(ra="thisWired"+(0<ra.length?", ":"")+ra);k+=(V?"var rv = ":"")+"invoker(fn"+(0<ra.length?", ":"")+ra+");\n";
if(J)k+="runDestructors(destructors);\n";else for(q=E?1:2;q<d.length;++q)x=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==d[q].Nb&&(k+=x+"_dtor("+x+"); // "+d[q].name+"\n",B.push(x+"_dtor"),m.push(d[q].Nb));V&&(k+="var ret = retType.fromWireType(rv);\nreturn ret;\n");B.push(k+"}\n");d=Ec(B).apply(null,m);q=b-1;if(!e.hasOwnProperty(c))throw new vc("Replacing nonexistant public symbol");void 0!==e[c].Mb&&void 0!==q?e[c].Mb[q]=d:(e[c]=d,e[c].tc=q);return[]})},i:function(a,b,c,d,f){function g(a){return a}
b=U(b);-1===f&&(f=4294967295);var k=mc(c);if(0===d){var m=32-8*c;g=function(a){return a<<m>>>m}}var y=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Bc(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Bc(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return y?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Oc(b,
k,0!==d),Nb:null})},g:function(a,b,c){function d(a){a>>=2;var b=C;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);X(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{wc:!0})},C:function(a,b){b=U(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(a){var b=C[a>>2];if(c){var d=z[a+4+b],k=0;0!=d&&(k=d,z[a+4+b]=0);var m=a+4;for(d=0;d<=b;++d){var y=a+4+d;if(0==z[y]){m=A(m);if(void 0===
p)var p=m;else p+=String.fromCharCode(0),p+=m;m=y+1}}0!=k&&(z[a+4+b]=k)}else{p=Array(b);for(d=0;d<b;++d)p[d]=String.fromCharCode(z[a+4+d]);p=p.join("")}Z(a);return p},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||W("Cannot pass non-string to std::string");var f=(c&&d?function(){return Ca(b)}:function(){return b.length})(),m=ya(4+f+1);C[m>>2]=f;if(c&&d)Ba(b,z,m+4,
f+1);else if(d)for(d=0;d<f;++d){var y=b.charCodeAt(d);255<y&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));z[m+4+d]=y}else for(d=0;d<f;++d)z[m+4+d]=b[d];null!==a&&a.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Ac,Nb:function(a){Z(a)}})},$:function(a,b,c){c=U(c);if(2===b){var d=function(){return Fa};var f=1}else 4===b&&(d=function(){return C},f=2);X(a,{name:c,fromWireType:function(a){for(var b=d(),c=C[a>>2],g=Array(c),p=a+4>>f,v=0;v<c;++v)g[v]=String.fromCharCode(b[p+
v]);Z(a);return g.join("")},toWireType:function(a,c){var g=d(),k=c.length,p=ya(4+k*b);C[p>>2]=k;for(var v=p+4>>f,x=0;x<k;++x)g[v+x]=c.charCodeAt(x);null!==a&&a.push(Z,p);return p},argPackAdvance:8,readValueFromPointer:Ac,Nb:function(a){Z(a)}})},_:function(a,b){b=U(b);X(a,{Kc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Z:yc,Y:function(a){4<a&&(Y[a].hc+=1)},X:function(a,b){var c=pc[a];void 0===c&&W("_emval_take_value has unknown type "+Lc(a));a=c.readValueFromPointer(b);
return zc(a)},b:function(){e.abort()},W:Pc,V:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ea||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Qc();else return mb(22),-1;u[b>>2]=a/1E3|0;u[b+4>>2]=a%1E3*1E6|0;return 0},U:qa,T:function(a,b,c){z.set(z.subarray(b,b+c),a)},S:function(a){if(2147418112<a)return!1;for(var b=Math.max(qa(),16777216);b<a;)536870912>=b?b=Da(2*b):b=Math.min(Da((3*b+2147483648)/4),2147418112);a:{try{va.grow(b-
buffer.byteLength+65535>>16);Ia(va.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},t:function(a){if(!ua&&(wa=!0,e.onExit))e.onExit(a);ca(a,new ma(a))},R:Ra,n:Rc,Q:function(a){var b=Date.now();u[a>>2]=b/1E3|0;u[a+4>>2]=b%1E3*1E3|0;return 0},B:function(a,b){a=new Date(1E3*u[a>>2]);u[b>>2]=a.getUTCSeconds();u[b+4>>2]=a.getUTCMinutes();u[b+8>>2]=a.getUTCHours();u[b+12>>2]=a.getUTCDate();u[b+16>>2]=a.getUTCMonth();u[b+20>>2]=a.getUTCFullYear()-1900;u[b+24>>2]=a.getUTCDay();u[b+36>>2]=0;u[b+
32>>2]=0;u[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;u[b+40>>2]=3404096;return b},h:Sc,f:function(a){return Sc(a)},P:Tc,j:function(a){return Tc(a)},e:Uc,m:function(a){return Uc(a)},s:function(a){var b=Vc.Fb[a];Vc.Fb.splice(a,1);id(b)},z:Vc,O:function(){r("trap!")},N:Va,r:function(a,b){Xc();a=new Date(1E3*u[a>>2]);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>
2]=a.getDay();var c=new Date(a.getFullYear(),0,1);u[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;u[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;u[b+32>>2]=a;a=u[ad()+(a?4:0)>>2];u[b+40>>2]=a;return b},M:function(a){Xc();var b=new Date(u[a+20>>2]+1900,u[a+16>>2],u[a+12>>2],u[a+8>>2],u[a+4>>2],u[a>>2],0),c=u[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(2E3,6,1)).getTimezoneOffset(),
k=f.getTimezoneOffset(),m=Math.min(k,g);0>c?u[a+32>>2]=Number(g!=k&&m==d):0<c!=(m==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));u[a+24>>2]=b.getDay();u[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},x:function(a,b){if(0===a)return mb(22),-1;var c=u[a>>2];a=u[a+4>>2];if(0>a||999999999<a||0>c)return mb(22),-1;0!==b&&(u[b>>2]=0,u[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((da||l)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-
c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},q:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),
0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function y(a){a=fd(new Date(a.Hb+1900,0,1),a.bc);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=k(m(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var p=u[d+40>>2];d={Ec:u[d>>2],Dc:u[d+4>>2],$b:u[d+8>>2],Yb:u[d+12>>2],Ub:u[d+16>>2],Hb:u[d+20>>2],ac:u[d+24>>2],
bc:u[d+28>>2],Nc:u[d+32>>2],Cc:u[d+36>>2],Fc:p?A(p):""};c=A(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var v in p)c=c.replace(new RegExp(v,"g"),p[v]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");p={"%a":function(a){return x[a.ac].substring(0,3)},"%A":function(a){return x[a.ac]},"%b":function(a){return E[a.Ub].substring(0,3)},"%B":function(a){return E[a.Ub]},"%C":function(a){return g((a.Hb+1900)/100|0,2)},"%d":function(a){return g(a.Yb,2)},"%e":function(a){return f(a.Yb,2," ")},"%g":function(a){return y(a).toString().substring(2)},"%G":function(a){return y(a)},"%H":function(a){return g(a.$b,
2)},"%I":function(a){a=a.$b;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Yb+cd(bd(a.Hb+1900)?dd:ed,a.Ub-1),3)},"%m":function(a){return g(a.Ub+1,2)},"%M":function(a){return g(a.Dc,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.$b&&12>a.$b?"AM":"PM"},"%S":function(a){return g(a.Ec,2)},"%t":function(){return"\t"},"%u":function(a){return a.ac||7},"%U":function(a){var b=new Date(a.Hb+1900,0,1),c=0===b.getDay()?b:fd(b,7-b.getDay());a=new Date(a.Hb+1900,a.Ub,a.Yb);return 0>
k(c,a)?g(Math.ceil((31-c.getDate()+(cd(bd(a.getFullYear())?dd:ed,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.Hb+1900,0,4)),c=m(new Date(a.Hb+1901,0,4)),d=fd(new Date(a.Hb+1900,0,1),a.bc);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Hb+1900?a.bc+32-b.getDate():a.bc+1-b.getDate())/7),2)},"%w":function(a){return a.ac},"%W":function(a){var b=new Date(a.Hb,0,1),c=1===b.getDay()?b:fd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Hb+
1900,a.Ub,a.Yb);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(cd(bd(a.getFullYear())?dd:ed,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.Hb+1900).toString().substring(2)},"%Y":function(a){return a.Hb+1900},"%z":function(a){a=a.Cc;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Fc},"%%":function(){return"%"}};for(v in p)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,"g"),p[v](d)));v=tb(c,!1);if(v.length>
b)return 0;w.set(v,a);return v.length-1},L:function(a){var b=Date.now()/1E3|0;a&&(u[a>>2]=b);return b},K:function(){r("OOM")},a:pa},buffer);e.asm=jd;e.___embind_register_native_and_builtin_types=function(){return e.asm.ma.apply(null,arguments)};e.___errno_location=function(){return e.asm.na.apply(null,arguments)};
var Mc=e.___getTypeName=function(){return e.asm.oa.apply(null,arguments)},$c=e.__get_daylight=function(){return e.asm.pa.apply(null,arguments)},Zc=e.__get_timezone=function(){return e.asm.qa.apply(null,arguments)},ad=e.__get_tzname=function(){return e.asm.ra.apply(null,arguments)},Z=e._free=function(){return e.asm.sa.apply(null,arguments)},ya=e._malloc=function(){return e.asm.ta.apply(null,arguments)},eb=e.globalCtors=function(){return e.asm.wb.apply(null,arguments)};
e.stackAlloc=function(){return e.asm.xb.apply(null,arguments)};var id=e.stackRestore=function(){return e.asm.yb.apply(null,arguments)},Wc=e.stackSave=function(){return e.asm.zb.apply(null,arguments)};e.dynCall_dd=function(){return e.asm.ua.apply(null,arguments)};e.dynCall_did=function(){return e.asm.va.apply(null,arguments)};e.dynCall_didd=function(){return e.asm.wa.apply(null,arguments)};e.dynCall_fii=function(){return e.asm.xa.apply(null,arguments)};
e.dynCall_fiifi=function(){return e.asm.ya.apply(null,arguments)};e.dynCall_fiii=function(){return e.asm.za.apply(null,arguments)};e.dynCall_fiiii=function(){return e.asm.Aa.apply(null,arguments)};e.dynCall_fiiiiiiiiffii=function(){return e.asm.Ba.apply(null,arguments)};e.dynCall_i=function(){return e.asm.Ca.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.Da.apply(null,arguments)};e.dynCall_iidiiii=function(){return e.asm.Ea.apply(null,arguments)};
e.dynCall_iii=function(){return e.asm.Fa.apply(null,arguments)};e.dynCall_iiifii=function(){return e.asm.Ga.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.Ha.apply(null,arguments)};e.dynCall_iiiii=function(){return e.asm.Ia.apply(null,arguments)};e.dynCall_iiiiii=function(){return e.asm.Ja.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.Ka.apply(null,arguments)};e.dynCall_iiiiiiidiiddii=function(){return e.asm.La.apply(null,arguments)};
e.dynCall_iiiiiiii=function(){return e.asm.Ma.apply(null,arguments)};e.dynCall_iiiiiiiiii=function(){return e.asm.Na.apply(null,arguments)};e.dynCall_iiiiiiiiiiiiiifii=function(){return e.asm.Oa.apply(null,arguments)};e.dynCall_iiiiij=function(){return e.asm.Pa.apply(null,arguments)};e.dynCall_iiiji=function(){return e.asm.Qa.apply(null,arguments)};e.dynCall_iiijjji=function(){return e.asm.Ra.apply(null,arguments)};e.dynCall_iij=function(){return e.asm.Sa.apply(null,arguments)};
e.dynCall_ijiii=function(){return e.asm.Ta.apply(null,arguments)};e.dynCall_jii=function(){return e.asm.Ua.apply(null,arguments)};e.dynCall_jiiii=function(){return e.asm.Va.apply(null,arguments)};e.dynCall_jiiij=function(){return e.asm.Wa.apply(null,arguments)};e.dynCall_jiiji=function(){return e.asm.Xa.apply(null,arguments)};e.dynCall_jij=function(){return e.asm.Ya.apply(null,arguments)};e.dynCall_jiji=function(){return e.asm.Za.apply(null,arguments)};
e.dynCall_v=function(){return e.asm._a.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.$a.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.ab.apply(null,arguments)};e.dynCall_viidi=function(){return e.asm.bb.apply(null,arguments)};e.dynCall_viifi=function(){return e.asm.cb.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.db.apply(null,arguments)};e.dynCall_viiif=function(){return e.asm.eb.apply(null,arguments)};
e.dynCall_viiiff=function(){return e.asm.fb.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.gb.apply(null,arguments)};e.dynCall_viiiif=function(){return e.asm.hb.apply(null,arguments)};e.dynCall_viiiifii=function(){return e.asm.ib.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.jb.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.kb.apply(null,arguments)};e.dynCall_viiiiiiff=function(){return e.asm.lb.apply(null,arguments)};
e.dynCall_viiiiiifi=function(){return e.asm.mb.apply(null,arguments)};e.dynCall_viiiiiii=function(){return e.asm.nb.apply(null,arguments)};e.dynCall_viiiiiiifi=function(){return e.asm.ob.apply(null,arguments)};e.dynCall_viiiiiiii=function(){return e.asm.pb.apply(null,arguments)};e.dynCall_viiiiiiiii=function(){return e.asm.qb.apply(null,arguments)};e.dynCall_viiiiiiiiii=function(){return e.asm.rb.apply(null,arguments)};e.dynCall_viiiiiiiiiii=function(){return e.asm.sb.apply(null,arguments)};
e.dynCall_viiiiiiiiiiii=function(){return e.asm.tb.apply(null,arguments)};e.dynCall_viiiiiiiiiiiiii=function(){return e.asm.ub.apply(null,arguments)};e.dynCall_viiijj=function(){return e.asm.vb.apply(null,arguments)};e.asm=jd;var kd;e.then=function(a){if(kd)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ya=function ld(){kd||md();kd||(Ya=ld)};
function md(){function a(){if(!kd&&(kd=!0,!wa)){Pa=!0;e.noFSInit||fc||(fc=!0,ec(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?ic("stdin",e.stdin):Xb("/dev/tty","/dev/stdin"),e.stdout?ic("stdout",null,e.stdout):Xb("/dev/tty","/dev/stdout"),e.stderr?ic("stderr",null,e.stderr):Xb("/dev/tty1","/dev/stderr"),$b("/dev/stdin","r"),$b("/dev/stdout","w"),$b("/dev/stderr","w"));Ka(Ma);Fb=!1;Ka(Na);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&
(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Oa.unshift(a)}Ka(Oa)}}if(!(0<Wa)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Qa();Ka(La);0<Wa||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=md;function r(a){if(e.onAbort)e.onAbort(a);na(a);t(a);wa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=r;
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();ua=!0;md();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    