
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var e,h;var k;k||(k=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa={},ba;for(ba in k)k.hasOwnProperty(ba)&&(aa[ba]=k[ba]);k.arguments=[];k.thisProgram="./this.program";k.quit=function(a,b){throw b;};k.preRun=[];k.postRun=[];var ca=!1,da=!1,n=!1,ea=!1;ca="object"===typeof window;da="function"===typeof importScripts;n="object"===typeof process&&"function"===typeof require&&!ca&&!da;ea=!ca&&!n&&!da;var p="";
if(n){p=__dirname+"/";var ha,ia;k.read=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);a=ha.readFileSync(a);return b?a:a.toString()};k.readBinary=function(a){a=k.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(k.thisProgram=process.argv[1].replace(/\\/g,"/"));k.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;});process.on("unhandledRejection",u);k.quit=function(a){process.exit(a)};
k.inspect=function(){return"[Emscripten Module object]"}}else if(ea)"undefined"!=typeof read&&(k.read=function(a){return read(a)}),k.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?k.arguments=scriptArgs:"undefined"!=typeof arguments&&(k.arguments=arguments),"function"===typeof quit&&(k.quit=function(a){quit(a)});else if(ca||da)da?p=self.location.href:document.currentScript&&
(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.lastIndexOf("/")+1):p="",k.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},da&&(k.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),k.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},k.setWindowTitle=function(a){document.title=a};var ka=k.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=k.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ka);for(ba in aa)aa.hasOwnProperty(ba)&&(k[ba]=aa[ba]);aa=void 0;
function la(a){var b=w[ma>>2];a=b+a+15&-16;if(a<=na())w[ma>>2]=a;else if(!oa(a))return 0;return b}var pa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&v("no native wasm support detected");var qa,ra=!1;function assert(a,b){a||u("Assertion failed: "+b)}
function sa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=ta(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)w[a>>2]=0;for(b=d+c;a<b;)z[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function wa(a){return a?va(B,a,void 0):""}
function xa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var m=a.charCodeAt(++g);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function ya(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function za(a){var b=ya(a)+1,c=Aa(b);xa(a,z,c,b);return c}function Ba(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,z,B,Ca,Da,w,C,Ea,Fa;
function Ga(){k.HEAP8=z=new Int8Array(buffer);k.HEAP16=Ca=new Int16Array(buffer);k.HEAP32=w=new Int32Array(buffer);k.HEAPU8=B=new Uint8Array(buffer);k.HEAPU16=Da=new Uint16Array(buffer);k.HEAPU32=C=new Uint32Array(buffer);k.HEAPF32=Ea=new Float32Array(buffer);k.HEAPF64=Fa=new Float64Array(buffer)}var ma=3434496,Ha=k.TOTAL_MEMORY||16777216;5242880>Ha&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Ha+"! (TOTAL_STACK=5242880)");
k.buffer?buffer=k.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(qa=new WebAssembly.Memory({initial:Ha/65536}),buffer=qa.buffer):buffer=new ArrayBuffer(Ha);Ga();w[ma>>2]=8677408;function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.yc;"number"===typeof c?void 0===b.ec?k.dynCall_v(c):k.dynCall_vi(c,b.ec):c(void 0===b.ec?null:b.ec)}}}var Ja=[],Ka=[],La=[],Ma=[],Na=!1;
function Oa(){Na||(Na=!0,k.noFSInit||Pa||(Pa=!0,Qa(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?Ra("stdin",k.stdin):Sa("/dev/tty","/dev/stdin"),k.stdout?Ra("stdout",null,k.stdout):Sa("/dev/tty","/dev/stdout"),k.stderr?Ra("stderr",null,k.stderr):Sa("/dev/tty1","/dev/stderr"),Ta("/dev/stdin","r"),Ta("/dev/stdout","w"),Ta("/dev/stderr","w")),Ia(Ka))}function Ua(){var a=k.preRun.shift();Ja.unshift(a)}
var Va=Math.abs,Wa=Math.ceil,Xa=Math.floor,Ya=Math.min,Za=Math.trunc,$a=0,ab=null,bb=null;k.preloadedImages={};k.preloadedAudios={};function cb(){var a=db;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var db="ffmpeg.wasm";if(!cb()){var hb=db;db=k.locateFile?k.locateFile(hb,p):p+hb}
function ib(){try{if(k.wasmBinary)return new Uint8Array(k.wasmBinary);if(k.readBinary)return k.readBinary(db);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function jb(){return k.wasmBinary||!ca&&!da||"function"!==typeof fetch?new Promise(function(a){a(ib())}):fetch(db,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+db+"'";return a.arrayBuffer()}).catch(function(){return ib()})}
function kb(a){function b(a){k.asm=a.exports;$a--;k.monitorRunDependencies&&k.monitorRunDependencies($a);0==$a&&(null!==ab&&(clearInterval(ab),ab=null),bb&&(a=bb,bb=null,a()))}function c(a){b(a.instance)}function d(a){jb().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+a);u(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:pa};$a++;k.monitorRunDependencies&&k.monitorRunDependencies($a);if(k.instantiateWasm)try{return k.instantiateWasm(f,
b)}catch(g){return v("Module.instantiateWasm callback failed with error: "+g),!1}k.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||cb()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(db,{credentials:"same-origin"}),f).then(c,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");d(c)});return{}}
k.asm=function(a,b){b.memory=qa;b.table=new WebAssembly.Table({initial:5876,maximum:5876,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return kb(b)};Ka.push({yc:function(){lb()}});var E={};
function mb(a){if(mb.Kb){var b=w[a>>2];var c=w[b>>2]}else mb.Kb=!0,E.USER=E.LOGNAME="web_user",E.PATH="/",E.PWD="/",E.HOME="/home/web_user",E.LANG="C.UTF-8",E._=k.thisProgram,c=Na?ta(1024):la(1024),b=Na?ta(256):la(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,f;for(f in E)if("string"===typeof E[f]){var g=f+"="+E[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var l=c,m=0;m<d.length;++m)z[l++>>0]=d.charCodeAt(m);z[l>>0]=0;w[b+
4*f>>2]=c;c+=g.length+1}w[b+4*a.length>>2]=0}function nb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ob(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=nb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function pb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function qb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function rb(){var a=Array.prototype.slice.call(arguments,0);return ob(a.join("/"))}function sb(a,b){return ob(a+"/"+b)}function tb(a){k.___errno_location&&(w[k.___errno_location()>>2]=a);return a}
function ub(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=nb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function vb(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=ub(a).substr(1);b=ub(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var wb=[];function xb(a,b){wb[a]={input:[],output:[],Yb:b};yb(a,zb)}
var zb={open:function(a){var b=wb[a.node.rdev];if(!b)throw new G(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.Yb.flush(a.tty)},flush:function(a){a.tty.Yb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Yb.rc)throw new G(6);for(var f=0,g=0;g<d;g++){try{var l=a.tty.Yb.rc(a.tty)}catch(m){throw new G(5);}if(void 0===l&&0===f)throw new G(11);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Yb.hc)throw new G(6);
try{for(var f=0;f<d;f++)a.tty.Yb.hc(a.tty,b[c+f])}catch(g){throw new G(5);}d&&(a.node.timestamp=Date.now());return f}},Bb={rc:function(a){if(!a.input.length){var b=null;if(n){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(l){}}try{d=fs.readSync(f,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ab(b,!0)}return a.input.shift()},hc:function(a,b){null===b||10===b?(ka(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(va(a.output,0)),a.output=[])}},Cb={hc:function(a,b){null===b||10===b?(v(va(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(v(va(a.output,0)),a.output=[])}},H={Ob:null,Jb:function(){return H.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(1);H.Ob||(H.Ob={dir:{node:{Mb:H.Db.Mb,Nb:H.Db.Nb,lookup:H.Db.lookup,$b:H.Db.$b,rename:H.Db.rename,unlink:H.Db.unlink,rmdir:H.Db.rmdir,readdir:H.Db.readdir,symlink:H.Db.symlink},stream:{Rb:H.Fb.Rb}},file:{node:{Mb:H.Db.Mb,Nb:H.Db.Nb},stream:{Rb:H.Fb.Rb,read:H.Fb.read,write:H.Fb.write,kc:H.Fb.kc,sc:H.Fb.sc,
uc:H.Fb.uc}},link:{node:{Mb:H.Db.Mb,Nb:H.Db.Nb,readlink:H.Db.readlink},stream:{}},mc:{node:{Mb:H.Db.Mb,Nb:H.Db.Nb},stream:Db}});c=Eb(a,b,c,d);I(c.mode)?(c.Db=H.Ob.dir.node,c.Fb=H.Ob.dir.stream,c.Eb={}):32768===(c.mode&61440)?(c.Db=H.Ob.file.node,c.Fb=H.Ob.file.stream,c.Hb=0,c.Eb=null):40960===(c.mode&61440)?(c.Db=H.Ob.link.node,c.Fb=H.Ob.link.stream):8192===(c.mode&61440)&&(c.Db=H.Ob.mc.node,c.Fb=H.Ob.mc.stream);c.timestamp=Date.now();a&&(a.Eb[b]=c);return c},Mc:function(a){if(a.Eb&&a.Eb.subarray){for(var b=
[],c=0;c<a.Hb;++c)b.push(a.Eb[c]);return b}return a.Eb},Nc:function(a){return a.Eb?a.Eb.subarray?a.Eb.subarray(0,a.Hb):new Uint8Array(a.Eb):new Uint8Array},nc:function(a,b){var c=a.Eb?a.Eb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Eb,a.Eb=new Uint8Array(b),0<a.Hb&&a.Eb.set(c.subarray(0,a.Hb),0))},Dc:function(a,b){if(a.Hb!=b)if(0==b)a.Eb=null,a.Hb=0;else{if(!a.Eb||a.Eb.subarray){var c=a.Eb;a.Eb=new Uint8Array(new ArrayBuffer(b));c&&a.Eb.set(c.subarray(0,Math.min(b,
a.Hb)))}else if(a.Eb||(a.Eb=[]),a.Eb.length>b)a.Eb.length=b;else for(;a.Eb.length<b;)a.Eb.push(0);a.Hb=b}},Db:{Mb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;I(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Hb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ub=4096;b.blocks=Math.ceil(b.size/b.Ub);return b},Nb:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&H.Dc(a,b.size)},lookup:function(){throw Fb[2];},$b:function(a,b,c,d){return H.createNode(a,b,c,d)},rename:function(a,b,c){if(I(a.mode)){try{var d=K(b,c)}catch(g){}if(d)for(var f in d.Eb)throw new G(39);}delete a.parent.Eb[a.name];a.name=c;b.Eb[c]=a;a.parent=b},unlink:function(a,b){delete a.Eb[b]},rmdir:function(a,b){var c=K(a,b),d;for(d in c.Eb)throw new G(39);delete a.Eb[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.Eb)a.Eb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new G(22);return a.link}},Fb:{read:function(a,b,c,d,f){var g=a.node.Eb;if(f>=a.node.Hb)return 0;a=Math.min(a.node.Hb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.Eb||a.Eb.subarray)){if(g)return a.Eb=b.subarray(c,c+d),a.Hb=d;if(0===a.Hb&&0===f)return a.Eb=new Uint8Array(b.subarray(c,c+d)),a.Hb=d;if(f+d<=a.Hb)return a.Eb.set(b.subarray(c,c+d),f),d}H.nc(a,f+d);if(a.Eb.subarray&&b.subarray)a.Eb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Eb[f+g]=b[c+g];a.Hb=Math.max(a.Hb,f+d);return d},Rb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Hb);if(0>b)throw new G(22);return b},kc:function(a,b,c){H.nc(a.node,b+c);a.node.Hb=
Math.max(a.node.Hb,b+c)},sc:function(a,b,c,d,f,g,l){if(32768!==(a.node.mode&61440))throw new G(19);c=a.node.Eb;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Hb)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=ta(d);if(!d)throw new G(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{Qc:d,Lc:a}},uc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new G(19);if(f&2)return 0;H.Fb.write(a,b,0,d,c,!1);return 0}}},L={bc:!1,Fc:function(){L.bc=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);L.oc={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},lc:function(a){return Buffer.Kb?Buffer.from(a):new Buffer(a)},Jb:function(a){assert(n);return L.createNode(null,"/",L.qc(a.fc.root),0)},createNode:function(a,b,c){if(!I(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new G(22);a=Eb(a,b,c);a.Db=L.Db;a.Fb=L.Fb;return a},qc:function(a){try{var b=fs.lstatSync(a);L.bc&&(b.mode=b.mode|(b.mode&
292)>>2)}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}return b.mode},Lb:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Jb.fc.root);b.reverse();return rb.apply(null,b)},xc:function(a){a&=-2656257;var b=0,c;for(c in L.oc)a&c&&(b|=L.oc[c],a^=c);if(a)throw new G(22);return b},Db:{Mb:function(a){a=L.Lb(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}L.bc&&!b.Ub&&(b.Ub=4096);L.bc&&!b.blocks&&(b.blocks=(b.size+b.Ub-1)/b.Ub|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Ub:b.Ub,blocks:b.blocks}},Nb:function(a,b){var c=L.Lb(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new G(-d.Gb);}},lookup:function(a,b){var c=sb(L.Lb(a),b);c=L.qc(c);return L.createNode(a,b,c)},$b:function(a,b,c,d){a=L.createNode(a,b,c,d);b=L.Lb(a);try{I(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new G(-f.Gb);}return a},rename:function(a,b,c){a=L.Lb(a);b=sb(L.Lb(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new G(-d.Gb);}},unlink:function(a,b){a=sb(L.Lb(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}},rmdir:function(a,b){a=sb(L.Lb(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}},readdir:function(a){a=L.Lb(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new G(-b.Gb);
}},symlink:function(a,b,c){a=sb(L.Lb(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new G(-d.Gb);}},readlink:function(a){var b=L.Lb(a);try{return b=fs.readlinkSync(b),b=Gb.relative(Gb.resolve(a.Jb.fc.root),b)}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}}},Fb:{open:function(a){var b=L.Lb(a.node);try{32768===(a.node.mode&61440)&&(a.ac=fs.openSync(b,L.xc(a.flags)))}catch(c){if(!c.code)throw c;throw new G(-c.Gb);}},close:function(a){try{32768===(a.node.mode&61440)&&a.ac&&fs.closeSync(a.ac)}catch(b){if(!b.code)throw b;
throw new G(-b.Gb);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.ac,L.lc(b.buffer),c,d,f)}catch(g){throw new G(-g.Gb);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.ac,L.lc(b.buffer),c,d,f)}catch(g){throw new G(-g.Gb);}},Rb:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ac).size}catch(d){throw new G(-d.Gb);}if(0>b)throw new G(22);return b}}},Hb=null,Ib={},Jb=[],Kb=1,Mb=null,Nb=!0,M={},G=null,Fb={};
function O(a,b){a=ub("/",a);b=b||{};if(!a)return{path:"",node:null};var c={pc:!0,ic:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ic)throw new G(40);a=nb(a.split("/").filter(function(a){return!!a}),!1);var f=Hb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=K(f,a[d]);c=sb(c,a[d]);f.Sb&&(!g||g&&b.pc)&&(f=f.Sb.root);if(!g||b.Zb)for(g=0;40960===(f.mode&61440);)if(f=Ob(c),c=ub(pb(c),f),f=O(c,{ic:b.ic}).node,40<g++)throw new G(40);}return{path:c,node:f}}
function Pb(a){for(var b;;){if(a===a.parent)return a=a.Jb.tc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Qb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Mb.length}function Rb(a){var b=Qb(a.parent.id,a.name);a.Xb=Mb[b];Mb[b]=a}function Sb(a){var b=Qb(a.parent.id,a.name);if(Mb[b]===a)Mb[b]=a.Xb;else for(b=Mb[b];b;){if(b.Xb===a){b.Xb=a.Xb;break}b=b.Xb}}
function K(a,b){var c;if(c=(c=Tb(a,"x"))?c:a.Db.lookup?0:13)throw new G(c,a);for(c=Mb[Qb(a.id,b)];c;c=c.Xb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Db.lookup(a,b)}
function Eb(a,b,c,d){Ub||(Ub=function(a,b,c,d){a||(a=this);this.parent=a;this.Jb=a.Jb;this.Sb=null;this.id=Kb++;this.name=b;this.mode=c;this.Db={};this.Fb={};this.rdev=d},Ub.prototype={},Object.defineProperties(Ub.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Ub(a,b,c,d);Rb(a);return a}
function I(a){return 16384===(a&61440)}var Vb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Wb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Tb(a,b){if(Nb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Xb(a,b){try{return K(a,b),17}catch(c){}return Tb(a,"wx")}
function Yb(a,b,c){try{var d=K(a,b)}catch(f){return f.Gb}if(a=Tb(a,"wx"))return a;if(c){if(!I(d.mode))return 20;if(d===d.parent||"/"===Pb(d))return 16}else if(I(d.mode))return 21;return 0}function Zb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Jb[a])return a;throw new G(24);}
function $b(a,b){ac||(ac=function(){},ac.prototype={},Object.defineProperties(ac.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new ac,d;for(d in a)c[d]=a[d];a=c;b=Zb(b);a.fd=b;return Jb[b]=a}var Db={open:function(a){a.Fb=Ib[a.node.rdev].Fb;a.Fb.open&&a.Fb.open(a)},Rb:function(){throw new G(29);}};function yb(a,b){Ib[a]={Fb:b}}
function bc(a,b){var c="/"===b,d=!b;if(c&&Hb)throw new G(16);if(!c&&!d){var f=O(b,{pc:!1});b=f.path;f=f.node;if(f.Sb)throw new G(16);if(!I(f.mode))throw new G(20);}b={type:a,fc:{},tc:b,Bc:[]};a=a.Jb(b);a.Jb=b;b.root=a;c?Hb=a:f&&(f.Sb=b,f.Jb&&f.Jb.Bc.push(b))}function cc(a,b,c){var d=O(a,{parent:!0}).node;a=qb(a);if(!a||"."===a||".."===a)throw new G(22);var f=Xb(d,a);if(f)throw new G(f);if(!d.Db.$b)throw new G(1);return d.Db.$b(d,a,b,c)}function P(a){cc(a,16895,0)}
function dc(a,b,c){"undefined"===typeof c&&(c=b,b=438);cc(a,b|8192,c)}function Sa(a,b){if(!ub(a))throw new G(2);var c=O(b,{parent:!0}).node;if(!c)throw new G(2);b=qb(b);var d=Xb(c,b);if(d)throw new G(d);if(!c.Db.symlink)throw new G(1);c.Db.symlink(c,b,a)}function Ob(a){a=O(a).node;if(!a)throw new G(2);if(!a.Db.readlink)throw new G(22);return ub(Pb(a.parent),a.Db.readlink(a))}function ec(a,b){a=O(a,{Zb:!b}).node;if(!a)throw new G(2);if(!a.Db.Mb)throw new G(1);return a.Db.Mb(a)}
function fc(a){return ec(a,!0)}
function Ta(a,b,c,d){if(""===a)throw new G(2);if("string"===typeof b){var f=Vb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=ob(a);try{g=O(a,{Zb:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new G(17);}else g=cc(a,c,0),f=!0;if(!g)throw new G(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!I(g.mode))throw new G(20);if(!f&&(c=g?40960===(g.mode&61440)?40:I(g.mode)&&
("r"!==Wb(b)||b&512)?21:Tb(g,Wb(b)):2))throw new G(c);if(b&512){c=g;var l;"string"===typeof c?l=O(c,{Zb:!0}).node:l=c;if(!l.Db.Nb)throw new G(1);if(I(l.mode))throw new G(21);if(32768!==(l.mode&61440))throw new G(22);if(c=Tb(l,"w"))throw new G(c);l.Db.Nb(l,{size:0,timestamp:Date.now()})}b&=-641;d=$b({node:g,path:Pb(g),flags:b,seekable:!0,position:0,Fb:g.Fb,Kc:[],error:!1},d);d.Fb.open&&d.Fb.open(d);!k.logReadFiles||b&1||(hc||(hc={}),a in hc||(hc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{M.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),M.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function ic(a,b,c){if(null===a.fd)throw new G(9);if(!a.seekable||!a.Fb.Rb)throw new G(29);if(0!=c&&1!=c&&2!=c)throw new G(22);a.position=a.Fb.Rb(a,b,c);a.Kc=[];return a.position}
function jc(a,b,c,d){var f=z;if(0>c||0>d)throw new G(22);if(null===a.fd)throw new G(9);if(1===(a.flags&2097155))throw new G(9);if(I(a.node.mode))throw new G(21);if(!a.Fb.read)throw new G(22);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new G(29);b=a.Fb.read(a,f,b,c,d);g||(a.position+=b);return b}
function kc(a,b,c,d){var f=z;if(0>c||0>d)throw new G(22);if(null===a.fd)throw new G(9);if(0===(a.flags&2097155))throw new G(9);if(I(a.node.mode))throw new G(21);if(!a.Fb.write)throw new G(22);a.flags&1024&&ic(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new G(29);b=a.Fb.write(a,f,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&M.onWriteToFile)M.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function Qa(){G||(G=function(a,b){this.node=b;this.Ec=function(a){this.Gb=a};this.Ec(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},G.prototype=Error(),G.prototype.constructor=G,[2].forEach(function(a){Fb[a]=new G(a);Fb[a].stack="<generic error, no stack>"}))}var Pa;function lc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ra(a,b,c){a=sb("/dev",a);var d=lc(!!b,!!c);mc||(mc=64);var f=mc++<<8|0;yb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,l=0;l<f;l++){try{var m=b()}catch(D){throw new G(5);}if(void 0===m&&0===g)throw new G(11);if(null===m||void 0===m)break;g++;c[d+l]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(t){throw new G(5);}f&&(a.node.timestamp=Date.now());return g}});
dc(a,d,f)}var mc,Q={},Ub,ac,hc;
function nc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&ob(b)!==ob(Pb(f.node)))return-20;throw f;}w[c>>2]=d.dev;w[c+4>>2]=0;w[c+8>>2]=d.ino;w[c+12>>2]=d.mode;w[c+16>>2]=d.nlink;w[c+20>>2]=d.uid;w[c+24>>2]=d.gid;w[c+28>>2]=d.rdev;w[c+32>>2]=0;e=[d.size>>>0,(h=d.size,1<=+Va(h)?0<h?(Ya(+Xa(h/4294967296),4294967295)|0)>>>0:~~+Wa((h-+(~~h>>>0))/4294967296)>>>0:0)];w[c+40>>2]=e[0];w[c+44>>2]=e[1];w[c+48>>2]=4096;w[c+52>>2]=d.blocks;w[c+56>>2]=d.atime.getTime()/1E3|0;w[c+60>>2]=0;w[c+64>>2]=d.mtime.getTime()/
1E3|0;w[c+68>>2]=0;w[c+72>>2]=d.ctime.getTime()/1E3|0;w[c+76>>2]=0;e=[d.ino>>>0,(h=d.ino,1<=+Va(h)?0<h?(Ya(+Xa(h/4294967296),4294967295)|0)>>>0:~~+Wa((h-+(~~h>>>0))/4294967296)>>>0:0)];w[c+80>>2]=e[0];w[c+84>>2]=e[1];return 0}var S=0;function T(){S+=4;return w[S-4>>2]}function oc(){return wa(T())}function U(){var a=Jb[T()];if(!a)throw new G(9);return a}function pc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}
var qc=void 0;function V(a){for(var b="";B[a];)b+=qc[B[a++]];return b}var rc={},sc={},tc={};function uc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function vc(a,b){a=uc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function wc(a){var b=Error,c=vc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var xc=void 0;function W(a){throw new xc(a);}var yc=void 0;
function zc(a,b){function c(a){a=b(a);if(a.length!==d.length)throw new yc("Mismatched type converter count");for(var c=0;c<d.length;++c)X(d[c],a[c])}var d=[];d.forEach(function(b){tc[b]=a});var f=Array(a.length),g=[],l=0;a.forEach(function(a,b){sc.hasOwnProperty(a)?f[b]=sc[a]:(g.push(a),rc.hasOwnProperty(a)||(rc[a]=[]),rc[a].push(function(){f[b]=sc[a];++l;l===g.length&&c(f)}))});0===g.length&&c(f)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(sc.hasOwnProperty(a)){if(c.zc)return;W("Cannot register type '"+d+"' twice")}sc[a]=b;delete tc[a];rc.hasOwnProperty(a)&&(b=rc[a],delete rc[a],b.forEach(function(a){a()}))}var Ac=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Bc(a){4<a&&0===--Y[a].jc&&(Y[a]=void 0,Ac.push(a))}function Cc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ac.length?Ac.pop():Y.length;Y[b]={jc:1,value:a};return b}}function Dc(a){return this.fromWireType(C[a>>2])}function Ec(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Fc(a,b){switch(b){case 2:return function(a){return this.fromWireType(Ea[a>>2])};case 3:return function(a){return this.fromWireType(Fa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Gc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=vc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Hc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ic(a,b){var c=k;if(void 0===c[a].Pb){var d=c[a];c[a]=function(){c[a].Pb.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Pb+")!");return c[a].Pb[arguments.length].apply(this,arguments)};c[a].Pb=[];c[a].Pb[d.wc]=d}}
function Jc(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].Pb&&void 0!==k[a].Pb[c])&&W("Cannot register public name '"+a+"' twice"),Ic(a,a),k.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),k[a].Pb[c]=b):(k[a]=b,void 0!==c&&(k[a].Pc=c))}function Kc(a,b){for(var c=[],d=0;d<a;d++)c.push(w[(b>>2)+d]);return c}
function Lc(a,b){a=V(a);if(void 0!==k["FUNCTION_TABLE_"+a])var c=k["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=k["dynCall_"+a];void 0===c&&(c=k["dynCall_"+a.replace(/f/g,"d")],void 0===c&&W("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var Mc=void 0;function Nc(a){a=Oc(a);var b=V(a);Z(a);return b}function Pc(a,b){function c(a){f[a]||sc[a]||(tc[a]?tc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Mc(a+": "+d.map(Nc).join([", "]));}
function Qc(a,b,c){switch(b){case 0:return c?function(a){return z[a]}:function(a){return B[a]};case 1:return c?function(a){return Ca[a>>1]}:function(a){return Da[a>>1]};case 2:return c?function(a){return w[a>>2]}:function(a){return C[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Rc(){void 0===Rc.start&&(Rc.start=Date.now());return 1E3*(Date.now()-Rc.start)|0}function Sc(){u()}function na(){return z.length}
function Tc(a){a=Ba(a);var b=buffer.byteLength;try{return-1!==qa.grow((a-b)/65536)?(buffer=qa.buffer,!0):!1}catch(c){return!1}}function oa(a){if(2147418112<a)return!1;for(var b=Math.max(na(),16777216);b<a;)536870912>=b?b=Ba(2*b):b=Math.min(Ba((3*b+2147483648)/4),2147418112);if(!Tc(b))return!1;Ga();return!0}function Uc(a){if(0===a)return 0;a=wa(a);if(!E.hasOwnProperty(a))return 0;Uc.Kb&&Z(Uc.Kb);a=E[a];var b=ya(a)+1,c=ta(b);c&&xa(a,z,c,b);Uc.Kb=c;return Uc.Kb}xa("GMT",B,3434400,4);
function Vc(a,b){a=new Date(1E3*w[a>>2]);w[b>>2]=a.getUTCSeconds();w[b+4>>2]=a.getUTCMinutes();w[b+8>>2]=a.getUTCHours();w[b+12>>2]=a.getUTCDate();w[b+16>>2]=a.getUTCMonth();w[b+20>>2]=a.getUTCFullYear()-1900;w[b+24>>2]=a.getUTCDay();w[b+36>>2]=0;w[b+32>>2]=0;w[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;w[b+40>>2]=3434400;return b}function Wc(a){return Math.pow(2,a)}function Xc(a){return Math.log(a)/Math.LN10}function Yc(a){return Math.log(a)/Math.LN2}
function Zc(){Zc.Kb||(Zc.Kb=[]);Zc.Kb.push($c());return Zc.Kb.length-1}function ad(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!bd){bd=!0;w[cd()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);w[dd()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=sa(Ab(d));f=sa(Ab(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(w[ed()>>2]=d,w[ed()+4>>2]=f):(w[ed()>>2]=f,w[ed()+4>>2]=d)}}var bd;
function fd(a,b){ad();a=new Date(1E3*w[a>>2]);w[b>>2]=a.getSeconds();w[b+4>>2]=a.getMinutes();w[b+8>>2]=a.getHours();w[b+12>>2]=a.getDate();w[b+16>>2]=a.getMonth();w[b+20>>2]=a.getFullYear()-1900;w[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);w[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;w[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;w[b+32>>2]=a;a=w[ed()+(a?4:0)>>2];w[b+40>>2]=
a;return b}function gd(a){return 0===a%4&&(0!==a%100||0===a%400)}function hd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var id=[31,29,31,30,31,30,31,31,30,31,30,31],jd=[31,28,31,30,31,30,31,31,30,31,30,31];function kd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(gd(a.getFullYear())?id:jd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}Qa();Mb=Array(4096);
bc(H,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");yb(259,{read:function(){return 0},write:function(a,b,c,l){return l}});dc("/dev/null",259);xb(1280,Bb);xb(1536,Cb);dc("/dev/tty",1280);dc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(n)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});Ra("random",b);Ra("urandom",b);P("/dev/shm");
P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");bc({Jb:function(){var a=Eb("/proc/self","fd",16895,73);a.Db={lookup:function(a,c){var b=Jb[+c];if(!b)throw new G(9);a={parent:null,Jb:{tc:"fake"},Db:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(n){var fs=require("fs"),Gb=require("path");L.Fc()}for(var ld=Array(256),md=0;256>md;++md)ld[md]=String.fromCharCode(md);qc=ld;xc=k.BindingError=wc("BindingError");yc=k.InternalError=wc("InternalError");
k.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Mc=k.UnboundTypeError=wc("UnboundTypeError");n?Sc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Sc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Sc=function(){return performance.now()}:Sc=Date.now;
function Ab(a,b){var c=Array(ya(a)+1);a=xa(a,c,0,c.length);b&&(c.length=a);return c}
var qd=k.asm({},{f:u,o:function(){},c:function(a,b,c,d){u("Assertion failed: "+wa(a)+", at: "+[b?wa(b):"unknown filename",c,d?wa(d):"unknown function"])},ha:mb,H:function(){},D:tb,Q:function(a,b){S=b;try{var c=oc(),d=O(c,{parent:!0}).node,f=qb(c),g=K(d,f),l=Yb(d,f,!1);if(l)throw new G(l);if(!d.Db.unlink)throw new G(1);if(g.Sb)throw new G(16);try{M.willDeletePath&&M.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Db.unlink(d,
f);Sb(g);try{if(M.onDeletePath)M.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof G||u(m),-m.Gb}},A:function(a,b){S=b;try{var c=U(),d=T(),f=T(),g=T(),l=T();if(!(-1==d&&0>f||0==d&&0<=f))return-75;ic(c,f,l);e=[c.position>>>0,(h=c.position,1<=+Va(h)?0<h?(Ya(+Xa(h/4294967296),4294967295)|0)>>>0:~~+Wa((h-+(~~h>>>0))/4294967296)>>>0:0)];w[g>>2]=e[0];w[g+4>>2]=e[1];c.Vb&&0===f&&
0===l&&(c.Vb=null);return 0}catch(m){return"undefined"!==typeof Q&&m instanceof G||u(m),-m.Gb}},L:function(a,b){S=b;try{var c=T(),d=T(),f=T(),g=T();T();a=0;for(var l=d?w[d>>2]:0,m=d?w[d+4>>2]:0,y=f?w[f>>2]:0,q=f?w[f+4>>2]:0,t=g?w[g>>2]:0,x=g?w[g+4>>2]:0,D=b=0,F=0,r=0,N=0,A=0,fa=(d?w[d>>2]:0)|(f?w[f>>2]:0)|(g?w[g>>2]:0),eb=(d?w[d+4>>2]:0)|(f?w[f+4>>2]:0)|(g?w[g+4>>2]:0),R=0;R<c;R++){var J=1<<R%32;if(32>R?fa&J:eb&J){var fb=Jb[R];if(!fb)throw new G(9);var gb=5;fb.Fb.Cc&&(gb=fb.Fb.Cc(fb));gb&1&&(32>R?
l&J:m&J)&&(32>R?b|=J:D|=J,a++);gb&4&&(32>R?y&J:q&J)&&(32>R?F|=J:r|=J,a++);gb&2&&(32>R?t&J:x&J)&&(32>R?N|=J:A|=J,a++)}}d&&(w[d>>2]=b,w[d+4>>2]=D);f&&(w[f>>2]=F,w[f+4>>2]=r);g&&(w[g>>2]=N,w[g+4>>2]=A);return a}catch(Lb){return"undefined"!==typeof Q&&Lb instanceof G||u(Lb),-Lb.Gb}},K:function(a,b){S=b;try{var c=U(),d=T();a:{var f=T();for(b=a=0;b<f;b++){var g=w[d+(8*b+4)>>2],l=jc(c,w[d+8*b>>2],g,void 0);if(0>l){var m=-1;break a}a+=l;if(l<g)break}m=a}return m}catch(y){return"undefined"!==typeof Q&&y instanceof
G||u(y),-y.Gb}},x:function(a,b){S=b;try{var c=U(),d=T();a:{var f=T();for(b=a=0;b<f;b++){var g=kc(c,w[d+8*b>>2],w[d+(8*b+4)>>2],void 0);if(0>g){var l=-1;break a}a+=g}l=a}return l}catch(m){return"undefined"!==typeof Q&&m instanceof G||u(m),-m.Gb}},J:function(a,b){S=b;try{var c=oc(),d=T();return nc(ec,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof G||u(f),-f.Gb}},pa:function(a,b){S=b;try{var c=oc(),d=T();return nc(fc,c,d)}catch(f){return"undefined"!==typeof Q&&f instanceof G||u(f),-f.Gb}},
oa:function(a,b){S=b;try{var c=U(),d=T();return nc(ec,c.path,d)}catch(f){return"undefined"!==typeof Q&&f instanceof G||u(f),-f.Gb}},na:function(a,b){S=b;return 0},ma:function(a,b){S=b;try{var c=U(),d=T(),f=T();if(!c.Vb){var g=O(c.path,{Zb:!0}).node;if(!g.Db.readdir)throw new G(20);var l=g.Db.readdir(g);c.Vb=l}a=0;for(var m=ic(c,0,1),y=Math.floor(m/280);y<c.Vb.length&&a+280<=f;){var q=c.Vb[y];if("."===q[0]){var t=1;var x=4}else{var D=K(c.node,q);t=D.id;x=8192===(D.mode&61440)?2:I(D.mode)?4:40960===
(D.mode&61440)?10:8}e=[t>>>0,(h=t,1<=+Va(h)?0<h?(Ya(+Xa(h/4294967296),4294967295)|0)>>>0:~~+Wa((h-+(~~h>>>0))/4294967296)>>>0:0)];w[d+a>>2]=e[0];w[d+a+4>>2]=e[1];e=[280*(y+1)>>>0,(h=280*(y+1),1<=+Va(h)?0<h?(Ya(+Xa(h/4294967296),4294967295)|0)>>>0:~~+Wa((h-+(~~h>>>0))/4294967296)>>>0:0)];w[d+a+8>>2]=e[0];w[d+a+12>>2]=e[1];Ca[d+a+16>>1]=280;z[d+a+18>>0]=x;xa(q,B,d+a+19,256);a+=280;y+=1}ic(c,280*y,0);return a}catch(F){return"undefined"!==typeof Q&&F instanceof G||u(F),-F.Gb}},n:function(a,b){S=b;try{var c=
U();switch(T()){case 0:var d=T();return 0>d?-22:Ta(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=T(),c.flags|=d,0;case 12:return d=T(),Ca[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return tb(22),-1;default:return-22}}catch(f){return"undefined"!==typeof Q&&f instanceof G||u(f),-f.Gb}},la:function(a,b){S=b;try{var c=U(),d=T(),f=T();return jc(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof G||u(g),-g.Gb}},ka:function(a,b){S=b;
try{var c=oc();var d=T();if(d&-8)var f=-22;else{var g=O(c,{Zb:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");f=a&&Tb(g,a)?-13:0}return f}catch(l){return"undefined"!==typeof Q&&l instanceof G||u(l),-l.Gb}},ja:function(a,b){S=b;try{T();T();T();var c=T();c&&(w[c>>2]=-1,w[c+4>>2]=-1,w[c+8>>2]=-1,w[c+12>>2]=-1);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof G||u(d),-d.Gb}},ia:function(a,b){S=b;try{var c=oc(),d=oc(),f=pb(c),g=pb(d),l=qb(c),m=qb(d);try{var y=O(c,{parent:!0});var q=
y.node;y=O(d,{parent:!0});var t=y.node}catch(A){throw new G(16);}if(!q||!t)throw new G(2);if(q.Jb!==t.Jb)throw new G(18);var x=K(q,l),D=vb(c,g);if("."!==D.charAt(0))throw new G(22);D=vb(d,f);if("."!==D.charAt(0))throw new G(39);try{var F=K(t,m)}catch(A){}if(x!==F){var r=I(x.mode),N=Yb(q,l,r);if(N)throw new G(N);if(N=F?Yb(t,m,r):Xb(t,m))throw new G(N);if(!q.Db.rename)throw new G(1);if(x.Sb||F&&F.Sb)throw new G(16);if(t!==q&&(N=Tb(q,"w")))throw new G(N);try{M.willMovePath&&M.willMovePath(c,d)}catch(A){console.log("FS.trackingDelegate['willMovePath']('"+
c+"', '"+d+"') threw an exception: "+A.message)}Sb(x);try{q.Db.rename(x,t,m)}catch(A){throw A;}finally{Rb(x)}try{if(M.onMovePath)M.onMovePath(c,d)}catch(A){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+A.message)}}return 0}catch(A){return"undefined"!==typeof Q&&A instanceof G||u(A),-A.Gb}},ga:function(a,b){S=b;try{var c=U(),d=T(),f=T();return kc(c,d,f)}catch(g){return"undefined"!==typeof Q&&g instanceof G||u(g),-g.Gb}},fa:function(a,b){S=b;try{var c=oc(),d=
O(c,{parent:!0}).node,f=qb(c),g=K(d,f),l=Yb(d,f,!0);if(l)throw new G(l);if(!d.Db.rmdir)throw new G(1);if(g.Sb)throw new G(16);try{M.willDeletePath&&M.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.Db.rmdir(d,f);Sb(g);try{if(M.onDeletePath)M.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof Q&&m instanceof G||u(m),
-m.Gb}},I:function(a,b){S=b;try{var c=oc(),d=T(),f=T();return Ta(c,d,f).fd}catch(g){return"undefined"!==typeof Q&&g instanceof G||u(g),-g.Gb}},t:function(a,b){S=b;try{var c=U(),d=T();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var f=T();return w[f>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=f=T();if(!c.Fb.Ac)throw new G(25);return c.Fb.Ac(c,d,a);case 21523:return c.tty?
0:-25;case 21524:return c.tty?0:-25;default:u("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof Q&&g instanceof G||u(g),-g.Gb}},s:function(a,b){S=b;try{var c=U();if(null===c.fd)throw new G(9);c.Vb&&(c.Vb=null);try{c.Fb.close&&c.Fb.close(c)}catch(d){throw d;}finally{Jb[c.fd]=null}c.fd=null;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof G||u(d),-d.Gb}},ea:function(a,b){S=b;return 0},da:function(a,b){S=b;try{T();var c=T();nd(c,0,136);w[c>>2]=1;w[c+4>>2]=2;w[c+8>>2]=3;w[c+12>>
2]=4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof G||u(d),-d.Gb}},q:function(){},ca:function(a,b,c,d,f){var g=pc(c);b=V(b);X(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=z;else if(2===c)d=Ca;else if(4===c)d=w;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},Qb:null})},ba:function(a,b){b=V(b);X(a,{name:b,fromWireType:function(a){var b=
Y[a].value;Bc(a);return b},toWireType:function(a,b){return Cc(b)},argPackAdvance:8,readValueFromPointer:Dc,Qb:null})},G:function(a,b,c){c=pc(c);b=V(b);X(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ec(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Fc(b,c),Qb:null})},F:function(a,b,c,d,f,g){var l=Kc(b,c);a=V(a);f=Lc(d,f);Jc(a,function(){Pc("Cannot call "+a+" due to unbound types",
l)},b-1);zc(l,function(c){var d=[c[0],null].concat(c.slice(1)),l=c=a,m=f,x=d.length;2>x&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var D=null!==d[1]&&!1,F=!1,r=1;r<d.length;++r)if(null!==d[r]&&void 0===d[r].Qb){F=!0;break}var N="void"!==d[0].name,A="",fa="";for(r=0;r<x-2;++r)A+=(0!==r?", ":"")+"arg"+r,fa+=(0!==r?", ":"")+"arg"+r+"Wired";l="return function "+uc(l)+"("+A+") {\nif (arguments.length !== "+(x-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+
(x-2)+" args!');\n}\n";F&&(l+="var destructors = [];\n");var eb=F?"destructors":"null";A="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[W,m,g,Hc,d[0],d[1]];D&&(l+="var thisWired = classParam.toWireType("+eb+", this);\n");for(r=0;r<x-2;++r)l+="var arg"+r+"Wired = argType"+r+".toWireType("+eb+", arg"+r+"); // "+d[r+2].name+"\n",A.push("argType"+r),m.push(d[r+2]);D&&(fa="thisWired"+(0<fa.length?", ":"")+fa);l+=(N?"var rv = ":"")+"invoker(fn"+(0<fa.length?", ":"")+fa+");\n";
if(F)l+="runDestructors(destructors);\n";else for(r=D?1:2;r<d.length;++r)x=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==d[r].Qb&&(l+=x+"_dtor("+x+"); // "+d[r].name+"\n",A.push(x+"_dtor"),m.push(d[r].Qb));N&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");A.push(l+"}\n");d=Gc(A).apply(null,m);r=b-1;if(!k.hasOwnProperty(c))throw new yc("Replacing nonexistant public symbol");void 0!==k[c].Pb&&void 0!==r?k[c].Pb[r]=d:(k[c]=d,k[c].wc=r);return[]})},m:function(a,b,c,d,f){function g(a){return a}
b=V(b);-1===f&&(f=4294967295);var l=pc(c);if(0===d){var m=32-8*c;g=function(a){return a<<m>>>m}}var y=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Ec(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Ec(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return y?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Qc(b,
l,0!==d),Qb:null})},h:function(a,b,c){function d(a){a>>=2;var b=C;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);X(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{zc:!0})},E:function(a,b){b=V(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(a){var b=C[a>>2];if(c){var d=B[a+4+b],l=0;0!=d&&(l=d,B[a+4+b]=0);var m=a+4;for(d=0;d<=b;++d){var y=a+4+d;if(0==B[y]){m=wa(m);if(void 0===
q)var q=m;else q+=String.fromCharCode(0),q+=m;m=y+1}}0!=l&&(B[a+4+b]=l)}else{q=Array(b);for(d=0;d<b;++d)q[d]=String.fromCharCode(B[a+4+d]);q=q.join("")}Z(a);return q},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||W("Cannot pass non-string to std::string");var f=(c&&d?function(){return ya(b)}:function(){return b.length})(),m=ta(4+f+1);C[m>>2]=f;if(c&&d)xa(b,B,m+4,
f+1);else if(d)for(d=0;d<f;++d){var y=b.charCodeAt(d);255<y&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));B[m+4+d]=y}else for(d=0;d<f;++d)B[m+4+d]=b[d];null!==a&&a.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Dc,Qb:function(a){Z(a)}})},aa:function(a,b,c){c=V(c);if(2===b){var d=function(){return Da};var f=1}else 4===b&&(d=function(){return C},f=2);X(a,{name:c,fromWireType:function(a){for(var b=d(),c=C[a>>2],g=Array(c),q=a+4>>f,t=0;t<c;++t)g[t]=String.fromCharCode(b[q+
t]);Z(a);return g.join("")},toWireType:function(a,c){var g=d(),l=c.length,q=ta(4+l*b);C[q>>2]=l;for(var t=q+4>>f,x=0;x<l;++x)g[t+x]=c.charCodeAt(x);null!==a&&a.push(Z,q);return q},argPackAdvance:8,readValueFromPointer:Dc,Qb:function(a){Z(a)}})},$:function(a,b){b=V(b);X(a,{Oc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_:Bc,Z:function(a){4<a&&(Y[a].jc+=1)},b:function(){k.abort()},Y:Rc,X:function(a,b){if(0===a)a=Date.now();else if(1===a&&(n||"undefined"!==typeof dateNow||
"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Sc();else return tb(22),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},W:na,V:function(a,b,c){B.set(B.subarray(b,b+c),a)},U:oa,j:function(a){od(a)},T:Va,l:Uc,S:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},R:function(a){return Vc(a,3434352)},C:Vc,d:Wc,i:function(a){return Wc(a)},P:Xc,g:function(a){return Xc(a)},e:Yc,p:function(a){return Yc(a)},w:function(a){var b=Zc.Kb[a];Zc.Kb.splice(a,
1);pd(b)},B:Zc,O:Za,z:function(a){return fd(a,3434352)},v:fd,N:function(a){ad();var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0),c=w[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(2E3,6,1)).getTimezoneOffset(),l=f.getTimezoneOffset(),m=Math.min(l,g);0>c?w[a+32>>2]=Number(g!=l&&m==d):0<c!=(m==d)&&(g=Math.max(l,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));w[a+24>>2]=b.getDay();w[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/
1E3|0},y:function(a,b){var c=w[a>>2];a=w[a+4>>2];0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((ca||da)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},k:function(){return 0},r:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-
b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function y(a){a=kd(new Date(a.Ib+1900,0,1),a.dc);var b=m(new Date(a.getFullYear()+
1,0,4));return 0>=l(m(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var q=w[d+40>>2];d={Ic:w[d>>2],Hc:w[d+4>>2],cc:w[d+8>>2],Wb:w[d+12>>2],Tb:w[d+16>>2],Ib:w[d+20>>2],vc:w[d+24>>2],dc:w[d+28>>2],Rc:w[d+32>>2],Gc:w[d+36>>2],Jc:q?wa(q):""};c=wa(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var t in q)c=c.replace(new RegExp(t,"g"),q[t]);
var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");q={"%a":function(a){return x[a.vc].substring(0,3)},"%A":function(a){return x[a.vc]},"%b":function(a){return D[a.Tb].substring(0,3)},"%B":function(a){return D[a.Tb]},"%C":function(a){return g((a.Ib+1900)/100|0,2)},"%d":function(a){return g(a.Wb,2)},"%e":function(a){return f(a.Wb,2," ")},"%g":function(a){return y(a).toString().substring(2)},
"%G":function(a){return y(a)},"%H":function(a){return g(a.cc,2)},"%I":function(a){a=a.cc;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Wb+hd(gd(a.Ib+1900)?id:jd,a.Tb-1),3)},"%m":function(a){return g(a.Tb+1,2)},"%M":function(a){return g(a.Hc,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.cc&&12>a.cc?"AM":"PM"},"%S":function(a){return g(a.Ic,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Ib+1900,a.Tb+1,a.Wb,0,0,0,0)).getDay()||7},"%U":function(a){var b=
new Date(a.Ib+1900,0,1),c=0===b.getDay()?b:kd(b,7-b.getDay());a=new Date(a.Ib+1900,a.Tb,a.Wb);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(hd(gd(a.getFullYear())?id:jd,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.Ib+1900,0,4)),c=m(new Date(a.Ib+1901,0,4)),d=kd(new Date(a.Ib+1900,0,1),a.dc);return 0>l(d,b)?"53":0>=l(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Ib+1900?a.dc+32-b.getDate():a.dc+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Ib+
1900,a.Tb+1,a.Wb,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Ib,0,1),c=1===b.getDay()?b:kd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Ib+1900,a.Tb,a.Wb);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(hd(gd(a.getFullYear())?id:jd,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%y":function(a){return(a.Ib+1900).toString().substring(2)},"%Y":function(a){return a.Ib+1900},"%z":function(a){a=a.Gc;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},
"%Z":function(a){return a.Jc},"%%":function(){return"%"}};for(t in q)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),q[t](d)));t=Ab(c,!1);if(t.length>b)return 0;z.set(t,a);return t.length-1},u:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b},M:function(){u("OOM")},a:ma},buffer);k.asm=qd;k.___errno_location=function(){return k.asm.qa.apply(null,arguments)};
var Oc=k.___getTypeName=function(){return k.asm.ra.apply(null,arguments)},dd=k.__get_daylight=function(){return k.asm.sa.apply(null,arguments)},cd=k.__get_timezone=function(){return k.asm.ta.apply(null,arguments)},ed=k.__get_tzname=function(){return k.asm.ua.apply(null,arguments)},Z=k._free=function(){return k.asm.va.apply(null,arguments)};k._main=function(){return k.asm.wa.apply(null,arguments)};
var ta=k._malloc=function(){return k.asm.xa.apply(null,arguments)},nd=k._memset=function(){return k.asm.ya.apply(null,arguments)},lb=k.globalCtors=function(){return k.asm.zb.apply(null,arguments)},Aa=k.stackAlloc=function(){return k.asm.Ab.apply(null,arguments)},pd=k.stackRestore=function(){return k.asm.Bb.apply(null,arguments)},$c=k.stackSave=function(){return k.asm.Cb.apply(null,arguments)};k.dynCall_dd=function(){return k.asm.za.apply(null,arguments)};
k.dynCall_did=function(){return k.asm.Aa.apply(null,arguments)};k.dynCall_didd=function(){return k.asm.Ba.apply(null,arguments)};k.dynCall_fii=function(){return k.asm.Ca.apply(null,arguments)};k.dynCall_fiifi=function(){return k.asm.Da.apply(null,arguments)};k.dynCall_fiii=function(){return k.asm.Ea.apply(null,arguments)};k.dynCall_fiiii=function(){return k.asm.Fa.apply(null,arguments)};k.dynCall_fiiiiiiiiffii=function(){return k.asm.Ga.apply(null,arguments)};
k.dynCall_ii=function(){return k.asm.Ha.apply(null,arguments)};k.dynCall_iidiiii=function(){return k.asm.Ia.apply(null,arguments)};k.dynCall_iii=function(){return k.asm.Ja.apply(null,arguments)};k.dynCall_iiifii=function(){return k.asm.Ka.apply(null,arguments)};k.dynCall_iiii=function(){return k.asm.La.apply(null,arguments)};k.dynCall_iiiii=function(){return k.asm.Ma.apply(null,arguments)};k.dynCall_iiiiii=function(){return k.asm.Na.apply(null,arguments)};
k.dynCall_iiiiiii=function(){return k.asm.Oa.apply(null,arguments)};k.dynCall_iiiiiiidiiddii=function(){return k.asm.Pa.apply(null,arguments)};k.dynCall_iiiiiiii=function(){return k.asm.Qa.apply(null,arguments)};k.dynCall_iiiiiiiiii=function(){return k.asm.Ra.apply(null,arguments)};k.dynCall_iiiiiiiiiiiiiifii=function(){return k.asm.Sa.apply(null,arguments)};k.dynCall_iiiiij=function(){return k.asm.Ta.apply(null,arguments)};k.dynCall_iiiji=function(){return k.asm.Ua.apply(null,arguments)};
k.dynCall_iiijjji=function(){return k.asm.Va.apply(null,arguments)};k.dynCall_iij=function(){return k.asm.Wa.apply(null,arguments)};k.dynCall_ijiii=function(){return k.asm.Xa.apply(null,arguments)};k.dynCall_jii=function(){return k.asm.Ya.apply(null,arguments)};k.dynCall_jiiii=function(){return k.asm.Za.apply(null,arguments)};k.dynCall_jiiij=function(){return k.asm._a.apply(null,arguments)};k.dynCall_jiiji=function(){return k.asm.$a.apply(null,arguments)};
k.dynCall_jij=function(){return k.asm.ab.apply(null,arguments)};k.dynCall_jiji=function(){return k.asm.bb.apply(null,arguments)};k.dynCall_v=function(){return k.asm.cb.apply(null,arguments)};k.dynCall_vi=function(){return k.asm.db.apply(null,arguments)};k.dynCall_vii=function(){return k.asm.eb.apply(null,arguments)};k.dynCall_viidi=function(){return k.asm.fb.apply(null,arguments)};k.dynCall_viifi=function(){return k.asm.gb.apply(null,arguments)};
k.dynCall_viii=function(){return k.asm.hb.apply(null,arguments)};k.dynCall_viiif=function(){return k.asm.ib.apply(null,arguments)};k.dynCall_viiii=function(){return k.asm.jb.apply(null,arguments)};k.dynCall_viiiif=function(){return k.asm.kb.apply(null,arguments)};k.dynCall_viiiifii=function(){return k.asm.lb.apply(null,arguments)};k.dynCall_viiiii=function(){return k.asm.mb.apply(null,arguments)};k.dynCall_viiiiii=function(){return k.asm.nb.apply(null,arguments)};
k.dynCall_viiiiiiff=function(){return k.asm.ob.apply(null,arguments)};k.dynCall_viiiiiifi=function(){return k.asm.pb.apply(null,arguments)};k.dynCall_viiiiiii=function(){return k.asm.qb.apply(null,arguments)};k.dynCall_viiiiiiifi=function(){return k.asm.rb.apply(null,arguments)};k.dynCall_viiiiiiii=function(){return k.asm.sb.apply(null,arguments)};k.dynCall_viiiiiiiii=function(){return k.asm.tb.apply(null,arguments)};k.dynCall_viiiiiiiiii=function(){return k.asm.ub.apply(null,arguments)};
k.dynCall_viiiiiiiiiii=function(){return k.asm.vb.apply(null,arguments)};k.dynCall_viiiiiiiiiiii=function(){return k.asm.wb.apply(null,arguments)};k.dynCall_viiiiiiiiiiiiii=function(){return k.asm.xb.apply(null,arguments)};k.dynCall_viiijj=function(){return k.asm.yb.apply(null,arguments)};k.asm=qd;k.then=function(a){if(k.calledRun)a(k);else{var b=k.onRuntimeInitialized;k.onRuntimeInitialized=function(){b&&b();a(k)}}return k};
function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ja.prototype=Error();ja.prototype.constructor=ja;bb=function rd(){k.calledRun||sd();k.calledRun||(bb=rd)};
k.callMain=function(a){a=a||[];Oa();var b=a.length+1,c=Aa(4*(b+1));w[c>>2]=za(k.thisProgram);for(var d=1;d<b;d++)w[(c>>2)+d]=za(a[d-1]);w[(c>>2)+b]=0;try{var f=k._main(b,c,0);od(f,!0)}catch(g){g instanceof ja||("SimulateInfiniteLoop"==g?k.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),v("exception thrown: "+a),k.quit(1,g)))}finally{}};
function sd(a){function b(){if(!k.calledRun&&(k.calledRun=!0,!ra)){Oa();Nb=!1;Ia(La);if(k.onRuntimeInitialized)k.onRuntimeInitialized();k._main&&td&&k.callMain(a);if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Ma.unshift(b)}Ia(Ma)}}a=a||k.arguments;if(!(0<$a)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ua();Ia(Ja);0<$a||k.calledRun||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},
1);b()},1)):b())}}k.run=sd;function od(a,b){if(!b||!k.noExitRuntime||0!==a){if(!k.noExitRuntime&&(ra=!0,k.onExit))k.onExit(a);k.quit(a,new ja(a))}}function u(a){if(k.onAbort)k.onAbort(a);void 0!==a?(ka(a),v(a),a=JSON.stringify(a)):a="";ra=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}k.abort=u;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var td=!1;k.noInitialRun&&(td=!1);k.noExitRuntime=!0;sd();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    