
var ffmpeg = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(ffmpeg) {
  ffmpeg = ffmpeg || {};

var d;d||(d=typeof ffmpeg !== 'undefined' ? ffmpeg : {});var aa={},g;for(g in d)d.hasOwnProperty(g)&&(aa[g]=d[g]);var ba=[],ca="./this.program";function ea(a,b){throw b;}var fa=!1,l=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;l="function"===typeof importScripts;ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!l;ja=!fa&&!ha&&!l;
if(d.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var n="",ma,na;
if(ha){n=__dirname+"/";var oa,pa;ma=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);a=oa.readFileSync(a);return b?a:a.toString()};na=function(a){a=ma(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;});process.on("unhandledRejection",p);ea=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=
typeof read&&(ma=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||
l)l?n=self.location.href:document.currentScript&&(n=document.currentScript.src),_scriptDir&&(n=_scriptDir),0!==n.indexOf("blob:")?n=n.substr(0,n.lastIndexOf("/")+1):n="",ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});else throw Error("environment detection error");
var ra=d.print||console.log.bind(console),r=d.printErr||console.warn.bind(console);for(g in aa)aa.hasOwnProperty(g)&&(d[g]=aa[g]);aa=null;d.arguments&&(ba=d.arguments);Object.getOwnPropertyDescriptor(d,"arguments")||Object.defineProperty(d,"arguments",{get:function(){p("Module.arguments has been replaced with plain arguments_")}});d.thisProgram&&(ca=d.thisProgram);Object.getOwnPropertyDescriptor(d,"thisProgram")||Object.defineProperty(d,"thisProgram",{get:function(){p("Module.thisProgram has been replaced with plain thisProgram")}});
d.quit&&(ea=d.quit);Object.getOwnPropertyDescriptor(d,"quit")||Object.defineProperty(d,"quit",{get:function(){p("Module.quit has been replaced with plain quit_")}});assert("undefined"===typeof d.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof d.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof d.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof d.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof d.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"===typeof d.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"===typeof d.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"===typeof d.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");
Object.getOwnPropertyDescriptor(d,"read")||Object.defineProperty(d,"read",{get:function(){p("Module.read has been replaced with plain read_")}});Object.getOwnPropertyDescriptor(d,"readAsync")||Object.defineProperty(d,"readAsync",{get:function(){p("Module.readAsync has been replaced with plain readAsync")}});Object.getOwnPropertyDescriptor(d,"readBinary")||Object.defineProperty(d,"readBinary",{get:function(){p("Module.readBinary has been replaced with plain readBinary")}});sa=ta=function(){p("cannot use the stack before compiled code is ready to run, and has provided stack access")};
function ua(a){va||(va={});va[a]||(va[a]=1,r(a))}var va,wa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},xa=0,ya;d.wasmBinary&&(ya=d.wasmBinary);Object.getOwnPropertyDescriptor(d,"wasmBinary")||Object.defineProperty(d,"wasmBinary",{get:function(){p("Module.wasmBinary has been replaced with plain wasmBinary")}});var za;d.noExitRuntime&&(za=d.noExitRuntime);Object.getOwnPropertyDescriptor(d,"noExitRuntime")||Object.defineProperty(d,"noExitRuntime",{get:function(){p("Module.noExitRuntime has been replaced with plain noExitRuntime")}});
"object"!==typeof WebAssembly&&p("No WebAssembly support found. Build with -s WASM=0 to target JavaScript instead.");var t,Aa=!1;function assert(a,b){a||p("Assertion failed: "+b)}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;224==(f&240)?f=(f&15)<<12|h<<6|k:(240!=(f&248)&&ua("Invalid UTF-8 leading byte 0x"+f.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),f=(f&7)<<18|h<<12|k<<6|a[b++]&63);65536>f?e+=String.fromCharCode(f):(f-=
65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function Da(a){return a?Ca(u,a,void 0):""}
function Ea(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=e)break;b[c++]=k}else{if(2047>=k){if(c+1>=e)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++]=224|k>>12}else{if(c+3>=e)break;2097152<=k&&ua("Invalid Unicode code point 0x"+k.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");
b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function Fa(a,b,c){assert("number"==typeof c,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");Ea(a,u,b,c)}function Ga(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function Ha(a){var b=Ga(a)+1,c=ta(b);Ea(a,w,c,b);return c}function Ia(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,w,u,Ja,Ka,y,z,La,Ma;function Na(a){buffer=a;d.HEAP8=w=new Int8Array(a);d.HEAP16=Ja=new Int16Array(a);d.HEAP32=y=new Int32Array(a);d.HEAPU8=u=new Uint8Array(a);d.HEAPU16=Ka=new Uint16Array(a);d.HEAPU32=z=new Uint32Array(a);d.HEAPF32=La=new Float32Array(a);d.HEAPF64=Ma=new Float64Array(a)}assert(!0,"stack must start aligned");assert(!0,"heap must start aligned");
d.TOTAL_STACK&&assert(5242880===d.TOTAL_STACK,"the stack size can no longer be determined at runtime");var Oa=d.TOTAL_MEMORY||16777216;Object.getOwnPropertyDescriptor(d,"TOTAL_MEMORY")||Object.defineProperty(d,"TOTAL_MEMORY",{get:function(){p("Module.TOTAL_MEMORY has been replaced with plain INITIAL_TOTAL_MEMORY")}});assert(5242880<=Oa,"TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Oa+"! (TOTAL_STACK=5242880)");
assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");d.wasmMemory?t=d.wasmMemory:t=new WebAssembly.Memory({initial:Oa/65536});t&&(buffer=t.buffer);Oa=buffer.byteLength;assert(0===Oa%65536);Na(buffer);y[4748]=5261904;
function Pa(){var a=z[1315475],b=z[1315474];34821223==a&&2310721022==b||p("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x02135467, but received 0x"+b.toString(16)+" "+a.toString(16));1668509029!==y[0]&&p("Runtime error: The application has corrupted its heap memory area (address zero)!")}y[0]=1668509029;Ja[1]=25459;if(115!==u[2]||99!==u[3])throw"Runtime error: expected the system to be little-endian!";
function B(a,b){p("Invalid function pointer "+a+" called with signature '"+b+"'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this). Build with ASSERTIONS=2 for more info.")}
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.cc;"number"===typeof c?void 0===b.Jb?d.dynCall_v(c):d.dynCall_vi(c,b.Jb):c(void 0===b.Jb?null:b.Jb)}}}var Ra=[],Sa=[],Ta=[],Ua=[],C=!1,D=!1;function Va(){var a=d.preRun.shift();Ra.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var Wa=Math.abs,Xa=Math.ceil,Ya=Math.floor,Za=Math.min,E=0,F=null,$a=null,ab={};
function bb(){E++;d.monitorRunDependencies&&d.monitorRunDependencies(E);assert(!ab["wasm-instantiate"]);ab["wasm-instantiate"]=1;null===F&&"undefined"!==typeof setInterval&&(F=setInterval(function(){if(Aa)clearInterval(F),F=null;else{var a=!1,b;for(b in ab)a||(a=!0,r("still waiting on run dependencies:")),r("dependency: "+b);a&&r("(end of list)")}},1E4))}d.preloadedImages={};d.preloadedAudios={};
function cb(){var a=H;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var H="ffmpeg.wasm";if(!cb()){var db=H;H=d.locateFile?d.locateFile(db,n):n+db}function eb(){try{if(ya)return new Uint8Array(ya);if(na)return na(H);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}
function fb(){return ya||!fa&&!l||"function"!==typeof fetch?new Promise(function(a){a(eb())}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return eb()})}
function gb(a){function b(a){d.asm=a.exports;E--;d.monitorRunDependencies&&d.monitorRunDependencies(E);assert(ab["wasm-instantiate"]);delete ab["wasm-instantiate"];0==E&&(null!==F&&(clearInterval(F),F=null),$a&&(a=$a,$a=null,a()))}function c(a){assert(d===h,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");h=null;b(a.instance)}function e(a){return fb().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){r("failed to asynchronously prepare wasm: "+
a);p(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:wa};bb();var h=d;if(d.instantiateWasm)try{return d.instantiateWasm(f,b)}catch(k){return r("Module.instantiateWasm callback failed with error: "+k),!1}(function(){if(ya||"function"!==typeof WebAssembly.instantiateStreaming||cb()||"function"!==typeof fetch)return e(c);fetch(H,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,f).then(c,function(a){r("wasm streaming compile failed: "+
a);r("falling back to ArrayBuffer instantiation");e(c)})})})();return{}}d.asm=function(a,b){b.memory=t;b.table=new WebAssembly.Table({initial:326,maximum:326,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;a=gb(b);assert(a,"binaryen setup failed (no wasm support?)");return a};var hb,ib;Sa.push({cc:function(){jb()}});assert(!0);
function kb(a){return a.replace(/\b__Z[\w\d_]+/g,function(a){ua("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return a===a?a:a+" ["+a+"]"})}function lb(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}d.extraStackTrace&&(a+="\n"+d.extraStackTrace());return kb(a)}
function mb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function qb(){var a=Array.prototype.slice.call(arguments,0);return nb(a.join("/"))}function rb(a,b){return nb(a+"/"+b)}function sb(a){d.___errno_location?y[d.___errno_location()>>2]=a:r("failed to set errno from JS");return a}
function tb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ub=[];function vb(a,b){ub[a]={input:[],output:[],Eb:b};wb(a,xb)}
var xb={open:function(a){var b=ub[a.node.rdev];if(!b)throw new I(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.Eb.flush(a.tty)},flush:function(a){a.tty.Eb.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.Eb.Wb)throw new I(6);for(var f=0,h=0;h<e;h++){try{var k=a.tty.Eb.Wb(a.tty)}catch(m){throw new I(5);}if(void 0===k&&0===f)throw new I(11);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.Eb.Mb)throw new I(6);
try{for(var f=0;f<e;f++)a.tty.Eb.Mb(a.tty,b[c+f])}catch(h){throw new I(5);}e&&(a.node.timestamp=Date.now());return f}},yb={Wb:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.$b?Buffer.$b(256):new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var h=!1;try{f=fs.openSync("/dev/stdin","r"),h=!0}catch(k){}}try{e=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))e=0;else throw k;}h&&fs.closeSync(f);0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=
typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Ga(b)+1);b=Ea(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Mb:function(a,b){null===b||10===b?(ra(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(Ca(a.output,0)),a.output=[])}},zb={Mb:function(a,b){null===b||10===b?(r(Ca(a.output,0)),a.output=
[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(r(Ca(a.output,0)),a.output=[])}},J={wb:null,tb:function(){return J.createNode(null,"/",16895,0)},createNode:function(a,b,c,e){if(24576===(c&61440)||4096===(c&61440))throw new I(1);J.wb||(J.wb={dir:{node:{yb:J.pb.yb,vb:J.pb.vb,lookup:J.pb.lookup,Fb:J.pb.Fb,rename:J.pb.rename,unlink:J.pb.unlink,rmdir:J.pb.rmdir,readdir:J.pb.readdir,symlink:J.pb.symlink},stream:{Ab:J.qb.Ab}},file:{node:{yb:J.pb.yb,vb:J.pb.vb},stream:{Ab:J.qb.Ab,
read:J.qb.read,write:J.qb.write,Pb:J.qb.Pb,Xb:J.qb.Xb,Zb:J.qb.Zb}},link:{node:{yb:J.pb.yb,vb:J.pb.vb,readlink:J.pb.readlink},stream:{}},Rb:{node:{yb:J.pb.yb,vb:J.pb.vb},stream:Ab}});c=Bb(a,b,c,e);K(c.mode)?(c.pb=J.wb.dir.node,c.qb=J.wb.dir.stream,c.ob={}):32768===(c.mode&61440)?(c.pb=J.wb.file.node,c.qb=J.wb.file.stream,c.sb=0,c.ob=null):40960===(c.mode&61440)?(c.pb=J.wb.link.node,c.qb=J.wb.link.stream):8192===(c.mode&61440)&&(c.pb=J.wb.Rb.node,c.qb=J.wb.Rb.stream);c.timestamp=Date.now();a&&(a.ob[b]=
c);return c},He:function(a){if(a.ob&&a.ob.subarray){for(var b=[],c=0;c<a.sb;++c)b.push(a.ob[c]);return b}return a.ob},Ie:function(a){return a.ob?a.ob.subarray?a.ob.subarray(0,a.sb):new Uint8Array(a.ob):new Uint8Array},Sb:function(a,b){var c=a.ob?a.ob.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ob,a.ob=new Uint8Array(b),0<a.sb&&a.ob.set(c.subarray(0,a.sb),0))},lc:function(a,b){if(a.sb!=b)if(0==b)a.ob=null,a.sb=0;else{if(!a.ob||a.ob.subarray){var c=a.ob;a.ob=
new Uint8Array(new ArrayBuffer(b));c&&a.ob.set(c.subarray(0,Math.min(b,a.sb)))}else if(a.ob||(a.ob=[]),a.ob.length>b)a.ob.length=b;else for(;a.ob.length<b;)a.ob.push(0);a.sb=b}},pb:{yb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.sb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);
b.Bb=4096;b.blocks=Math.ceil(b.size/b.Bb);return b},vb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.lc(a,b.size)},lookup:function(){throw Cb[2];},Fb:function(a,b,c,e){return J.createNode(a,b,c,e)},rename:function(a,b,c){if(K(a.mode)){try{var e=Db(b,c)}catch(h){}if(e)for(var f in e.ob)throw new I(39);}delete a.parent.ob[a.name];a.name=c;b.ob[c]=a;a.parent=b},unlink:function(a,b){delete a.ob[b]},rmdir:function(a,b){var c=Db(a,b),e;
for(e in c.ob)throw new I(39);delete a.ob[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ob)a.ob.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(22);return a.link}},qb:{read:function(a,b,c,e,f){var h=a.node.ob;if(f>=a.node.sb)return 0;a=Math.min(a.node.sb-f,e);assert(0<=a);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=h[f+e];return a},write:function(a,
b,c,e,f,h){h&&ua("file packager has copied file data into memory, but in memory growth we are forced to copy it again (see --no-heap-copy)");h=!1;if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ob||a.ob.subarray)){if(h)return assert(0===f,"canOwn must imply no weird position inside the file"),a.ob=b.subarray(c,c+e),a.sb=e;if(0===a.sb&&0===f)return a.ob=new Uint8Array(b.subarray(c,c+e)),a.sb=e;if(f+e<=a.sb)return a.ob.set(b.subarray(c,c+e),f),e}J.Sb(a,f+e);if(a.ob.subarray&&b.subarray)a.ob.set(b.subarray(c,
c+e),f);else for(h=0;h<e;h++)a.ob[f+h]=b[c+h];a.sb=Math.max(a.sb,f+e);return e},Ab:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.sb);if(0>b)throw new I(22);return b},Pb:function(a,b,c){J.Sb(a.node,b+c);a.node.sb=Math.max(a.node.sb,b+c)},Xb:function(a,b,c,e,f,h,k){if(32768!==(a.node.mode&61440))throw new I(19);c=a.node.ob;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+e<a.node.sb)c.subarray?c=c.subarray(f,f+e):c=Array.prototype.slice.call(c,f,f+e);a=!0;f=
b.buffer==w.buffer;e=Eb(e);if(!e)throw new I(12);(f?w:b).set(c,e)}else a=!1,e=c.byteOffset;return{Le:e,Ge:a}},Zb:function(a,b,c,e,f){if(32768!==(a.node.mode&61440))throw new I(19);if(f&2)return 0;J.qb.write(a,b,0,e,c,!1);return 0}}},L={Ib:!1,nc:function(){L.Ib=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);L.Tb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Qb:function(a){return Buffer.$b?Buffer.from(a):
new Buffer(a)},tb:function(a){assert(ia);return L.createNode(null,"/",L.Vb(a.Lb.root),0)},createNode:function(a,b,c){if(!K(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(22);a=Bb(a,b,c);a.pb=L.pb;a.qb=L.qb;return a},Vb:function(a){try{var b=fs.lstatSync(a);L.Ib&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new I(-c.rb);}return b.mode},ub:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.tb.Lb.root);b.reverse();return qb.apply(null,b)},bc:function(a){a&=
-2656257;var b=0,c;for(c in L.Tb)a&c&&(b|=L.Tb[c],a^=c);if(a)throw new I(22);return b},pb:{yb:function(a){a=L.ub(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.rb);}L.Ib&&!b.Bb&&(b.Bb=4096);L.Ib&&!b.blocks&&(b.blocks=(b.size+b.Bb-1)/b.Bb|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Bb:b.Bb,blocks:b.blocks}},vb:function(a,b){var c=L.ub(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),
a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new I(-e.rb);}},lookup:function(a,b){var c=rb(L.ub(a),b);c=L.Vb(c);return L.createNode(a,b,c)},Fb:function(a,b,c,e){a=L.createNode(a,b,c,e);b=L.ub(a);try{K(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(-f.rb);}return a},rename:function(a,b,c){a=L.ub(a);b=rb(L.ub(b),c);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new I(-e.rb);}},unlink:function(a,
b){a=rb(L.ub(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.rb);}},rmdir:function(a,b){a=rb(L.ub(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(-c.rb);}},readdir:function(a){a=L.ub(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new I(-b.rb);}},symlink:function(a,b,c){a=rb(L.ub(a),b);try{fs.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new I(-e.rb);}},readlink:function(a){var b=L.ub(a);try{return b=fs.readlinkSync(b),b=Fb.relative(Fb.resolve(a.tb.Lb.root),
b)}catch(c){if(!c.code)throw c;throw new I(-c.rb);}}},qb:{open:function(a){var b=L.ub(a.node);try{32768===(a.node.mode&61440)&&(a.Gb=fs.openSync(b,L.bc(a.flags)))}catch(c){if(!c.code)throw c;throw new I(-c.rb);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Gb&&fs.closeSync(a.Gb)}catch(b){if(!b.code)throw b;throw new I(-b.rb);}},read:function(a,b,c,e,f){if(0===e)return 0;try{return fs.readSync(a.Gb,L.Qb(b.buffer),c,e,f)}catch(h){throw new I(-h.rb);}},write:function(a,b,c,e,f){try{return fs.writeSync(a.Gb,
L.Qb(b.buffer),c,e,f)}catch(h){throw new I(-h.rb);}},Ab:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Gb).size}catch(e){throw new I(-e.rb);}if(0>b)throw new I(22);return b}}},Gb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"},Hb={ge:1,Gd:2,te:3,ad:4,cd:5,ce:6,pc:7,Hd:8,yc:9,Hc:10,vc:11,De:11,Ld:12,qc:13,Uc:14,Ud:15,Fc:16,Tc:17,Ee:18,Fd:19,Wd:20,ed:21,bd:22,Ad:23,sd:24,ae:25,Ae:26,
Vc:27,Qd:28,se:29,pe:30,td:31,ie:32,Qc:33,me:34,Md:42,Yc:43,Ic:44,hd:45,jd:46,kd:47,qd:48,Be:49,Dd:50,gd:51,Nc:35,Id:37,xc:52,Bc:53,Fe:54,Bd:55,Cc:56,Dc:57,Oc:35,Ec:59,Sd:60,Ed:61,xe:62,Rd:63,Nd:64,Od:65,oe:66,Jd:67,tc:68,ue:69,Jc:70,je:71,vd:72,Rc:73,Ac:74,be:76,zc:77,ne:78,ld:79,md:80,pd:81,od:82,nd:83,Td:38,Xd:39,wd:36,rd:40,de:95,he:96,Mc:104,Cd:105,uc:97,le:91,Zd:88,Pd:92,qe:108,Lc:111,rc:98,Kc:103,zd:101,xd:100,ye:110,Wc:112,Xc:113,$c:115,wc:114,Pc:89,ud:90,ke:93,re:94,sc:99,yd:102,dd:106,Vd:107,
ze:109,Ce:87,Sc:122,ve:116,$d:95,Kd:123,Zc:84,ee:75,Gc:125,Yd:131,fe:130,we:86},Ib=null,Jb={},Kb=[],Lb=1,M=null,Mb=!0,P={},I=null,Cb={};
function Q(a,b){a=tb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ub:!0,Nb:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.Nb)throw new I(40);a=mb(a.split("/").filter(function(a){return!!a}),!1);var f=Ib;c="/";for(e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;f=Db(f,a[e]);c=rb(c,a[e]);f.Cb&&(!h||h&&b.Ub)&&(f=f.Cb.root);if(!h||b.Hb)for(h=0;40960===(f.mode&61440);)if(f=Nb(c),c=tb(ob(c),f),f=Q(c,{Nb:b.Nb}).node,40<h++)throw new I(40);}return{path:c,node:f}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.tb.Yb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%M.length}function Qb(a){var b=Pb(a.parent.id,a.name);a.Db=M[b];M[b]=a}function Rb(a){var b=Pb(a.parent.id,a.name);if(M[b]===a)M[b]=a.Db;else for(b=M[b];b;){if(b.Db===a){b.Db=a.Db;break}b=b.Db}}
function Db(a,b){var c;if(c=(c=Sb(a,"x"))?c:a.pb.lookup?0:13)throw new I(c,a);for(c=M[Pb(a.id,b)];c;c=c.Db){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return a.pb.lookup(a,b)}
function Bb(a,b,c,e){Tb||(Tb=function(a,b,c,e){a||(a=this);this.parent=a;this.tb=a.tb;this.Cb=null;this.id=Lb++;this.name=b;this.mode=c;this.pb={};this.qb={};this.rdev=e},Tb.prototype={},Object.defineProperties(Tb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Tb(a,b,c,e);Qb(a);return a}
function K(a){return 16384===(a&61440)}var Ub={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Vb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Sb(a,b){if(Mb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Wb(a,b){try{return Db(a,b),17}catch(c){}return Sb(a,"wx")}
function Xb(a,b,c){try{var e=Db(a,b)}catch(f){return f.rb}if(a=Sb(a,"wx"))return a;if(c){if(!K(e.mode))return 20;if(e===e.parent||"/"===Ob(e))return 16}else if(K(e.mode))return 21;return 0}function Yb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Kb[a])return a;throw new I(24);}
function Zb(a,b){$b||($b=function(){},$b.prototype={},Object.defineProperties($b.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new $b,e;for(e in a)c[e]=a[e];a=c;b=Yb(b);a.fd=b;return Kb[b]=a}var Ab={open:function(a){a.qb=Jb[a.node.rdev].qb;a.qb.open&&a.qb.open(a)},Ab:function(){throw new I(29);}};function wb(a,b){Jb[a]={qb:b}}
function ac(a,b){var c="/"===b,e=!b;if(c&&Ib)throw new I(16);if(!c&&!e){var f=Q(b,{Ub:!1});b=f.path;f=f.node;if(f.Cb)throw new I(16);if(!K(f.mode))throw new I(20);}b={type:a,Lb:{},Yb:b,hc:[]};a=a.tb(b);a.tb=b;b.root=a;c?Ib=a:f&&(f.Cb=b,f.tb&&f.tb.hc.push(b))}function bc(a,b,c){var e=Q(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new I(22);var f=Wb(e,a);if(f)throw new I(f);if(!e.pb.Fb)throw new I(1);return e.pb.Fb(e,a,b,c)}function R(a){bc(a,16895,0)}
function cc(a,b,c){"undefined"===typeof c&&(c=b,b=438);bc(a,b|8192,c)}function dc(a,b){if(!tb(a))throw new I(2);var c=Q(b,{parent:!0}).node;if(!c)throw new I(2);b=pb(b);var e=Wb(c,b);if(e)throw new I(e);if(!c.pb.symlink)throw new I(1);c.pb.symlink(c,b,a)}function Nb(a){a=Q(a).node;if(!a)throw new I(2);if(!a.pb.readlink)throw new I(22);return tb(Ob(a.parent),a.pb.readlink(a))}
function ec(a,b,c,e){if(""===a)throw new I(2);if("string"===typeof b){var f=Ub[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=nb(a);try{h=Q(a,{Hb:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(h){if(b&128)throw new I(17);}else h=bc(a,c,0),f=!0;if(!h)throw new I(2);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!K(h.mode))throw new I(20);if(!f&&(c=h?40960===(h.mode&61440)?40:K(h.mode)&&
("r"!==Vb(b)||b&512)?21:Sb(h,Vb(b)):2))throw new I(c);if(b&512){c=h;var k;"string"===typeof c?k=Q(c,{Hb:!0}).node:k=c;if(!k.pb.vb)throw new I(1);if(K(k.mode))throw new I(21);if(32768!==(k.mode&61440))throw new I(22);if(c=Sb(k,"w"))throw new I(c);k.pb.vb(k,{size:0,timestamp:Date.now()})}b&=-641;e=Zb({node:h,path:Ob(h),flags:b,seekable:!0,position:0,qb:h.qb,oc:[],error:!1},e);e.qb.open&&e.qb.open(e);!d.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{P.onOpenFile&&(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),P.onOpenFile(a,h))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return e}function hc(a,b,c){if(null===a.fd)throw new I(9);if(!a.seekable||!a.qb.Ab)throw new I(29);if(0!=c&&1!=c&&2!=c)throw new I(22);a.position=a.qb.Ab(a,b,c);a.oc=[]}
function ic(){I||(I=function(a,b){this.node=b;this.mc=function(a){this.rb=a;for(var b in Hb)if(Hb[b]===a){this.code=b;break}};this.mc(a);this.message=Gb[a];this.stack&&(Object.defineProperty(this,"stack",{value:Error().stack,writable:!0}),this.stack=kb(this.stack))},I.prototype=Error(),I.prototype.constructor=I,[2].forEach(function(a){Cb[a]=new I(a);Cb[a].stack="<generic error, no stack>"}))}var kc;function lc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function mc(a,b,c){a=rb("/dev",a);var e=lc(!!b,!!c);nc||(nc=64);var f=nc++<<8|0;wb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,e,f){for(var h=0,k=0;k<f;k++){try{var m=b()}catch(O){throw new I(5);}if(void 0===m&&0===h)throw new I(11);if(null===m||void 0===m)break;h++;c[e+k]=m}h&&(a.node.timestamp=Date.now());return h},write:function(a,b,e,f){for(var h=0;h<f;h++)try{c(b[e+h])}catch(G){throw new I(5);}f&&(a.node.timestamp=Date.now());return h}});
cc(a,e,f)}var nc,S={},Tb,$b,fc,T=0;function U(){T+=4;return y[T-4>>2]}function oc(){var a=Kb[U()];if(!a)throw new I(9);return a}function pc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var qc=void 0;function V(a){for(var b="";u[a];)b+=qc[u[a++]];return b}var rc={},sc={},tc={};function uc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function vc(a,b){a=uc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function wc(a){var b=Error,c=vc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var xc=void 0;function W(a){throw new xc(a);}var yc=void 0;function zc(a,b){function c(a){a=b(a);if(a.length!==e.length)throw new yc("Mismatched type converter count");for(var c=0;c<e.length;++c)X(e[c],a[c])}var e=[];e.forEach(function(b){tc[b]=a});var f=Array(a.length),h=[],k=0;a.forEach(function(a,b){sc.hasOwnProperty(a)?f[b]=sc[a]:(h.push(a),rc.hasOwnProperty(a)||(rc[a]=[]),rc[a].push(function(){f[b]=sc[a];++k;k===h.length&&c(f)}))});0===h.length&&c(f)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||W('type "'+e+'" must have a positive integer typeid pointer');if(sc.hasOwnProperty(a)){if(c.dc)return;W("Cannot register type '"+e+"' twice")}sc[a]=b;delete tc[a];rc.hasOwnProperty(a)&&(b=rc[a],delete rc[a],b.forEach(function(a){a()}))}var Ac=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Bc(a){4<a&&0===--Y[a].Ob&&(Y[a]=void 0,Ac.push(a))}function Cc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ac.length?Ac.pop():Y.length;Y[b]={Ob:1,value:a};return b}}function Dc(a){return this.fromWireType(z[a>>2])}function Ec(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Fc(a,b){switch(b){case 2:return function(a){return this.fromWireType(La[a>>2])};case 3:return function(a){return this.fromWireType(Ma[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Gc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=vc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Hc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ic(a,b){var c=d;if(void 0===c[a].xb){var e=c[a];c[a]=function(){c[a].xb.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].xb+")!");return c[a].xb[arguments.length].apply(this,arguments)};c[a].xb=[];c[a].xb[e.ac]=e}}
function Jc(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].xb&&void 0!==d[a].xb[c])&&W("Cannot register public name '"+a+"' twice"),Ic(a,a),d.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].xb[c]=b):(d[a]=b,void 0!==c&&(d[a].Ke=c))}function Kc(a,b){for(var c=[],e=0;e<a;e++)c.push(y[(b>>2)+e]);return c}
function Lc(a,b){a=V(a);if(void 0!==d["FUNCTION_TABLE_"+a])var c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d["dynCall_"+a];void 0===c&&(c=d["dynCall_"+a.replace(/f/g,"d")],void 0===c&&W("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var Mc=void 0;function Nc(a){a=Oc(a);var b=V(a);Z(a);return b}function Pc(a,b){function c(a){f[a]||sc[a]||(tc[a]?tc[a].forEach(c):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(c);throw new Mc(a+": "+e.map(Nc).join([", "]));}
function Qc(a,b,c){switch(b){case 0:return c?function(a){return w[a]}:function(a){return u[a]};case 1:return c?function(a){return Ja[a>>1]}:function(a){return Ka[a>>1]};case 2:return c?function(a){return y[a>>2]}:function(a){return z[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Rc(){return w.length}ic();M=Array(4096);ac(J,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");wb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});cc("/dev/null",259);vb(1280,yb);vb(1536,zb);cc("/dev/tty",1280);cc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(e){}b||(b=function(){p("no cryptographic support found for random_device. consider polyfilling it if you want to use something insecure like Math.random(), e.g. put this in a --pre-js: var crypto = { getRandomValues: function(array) { for (var i = 0; i < array.length; i++) array[i] = (Math.random()*256)|0 } };")});
mc("random",b);mc("urandom",b);R("/dev/shm");R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");ac({tb:function(){var a=Bb("/proc/self","fd",16895,73);a.pb={lookup:function(a,c){var b=Kb[+c];if(!b)throw new I(9);a={parent:null,tb:{Yb:"fake"},pb:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(ia){var fs=require("fs"),Fb=require("path");L.nc()}for(var Sc=Array(256),Tc=0;256>Tc;++Tc)Sc[Tc]=String.fromCharCode(Tc);qc=Sc;xc=d.BindingError=wc("BindingError");
yc=d.InternalError=wc("InternalError");d.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Mc=d.UnboundTypeError=wc("UnboundTypeError");
var Uc=d.asm({},{J:function(a){xa=a},H:function(){return xa},b:function(a){p("Stack overflow! Attempted to allocate "+a+" bytes on the stack, but stack has only "+(5261904-sa()+a)+" bytes available!")},Ra:function(a){B(a,"ii")},Ia:function(a){B(a,"iidiiii")},Da:function(a){B(a,"iii")},xa:function(a){B(a,"iiii")},ra:function(a){B(a,"iiiii")},ma:function(a){B(a,"jiji")},ea:function(a){B(a,"v")},Z:function(a){B(a,"vi")},O:function(a){B(a,"vii")},Qa:function(a){B(a,"viiii")},Pa:function(a){B(a,"viiiii")},
Oa:function(a){B(a,"viiiiii")},Na:function(){Aa=!0;throw"Pure virtual function called!";},Ma:function(){},F:sb,La:function(a,b){T=b;try{var c=Da(U()),e=Q(c,{parent:!0}).node,f=pb(c),h=Db(e,f),k=Xb(e,f,!1);if(k)throw new I(k);if(!e.pb.unlink)throw new I(1);if(h.Cb)throw new I(16);try{P.willDeletePath&&P.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}e.pb.unlink(e,f);Rb(h);try{if(P.onDeletePath)P.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof S&&m instanceof I||p(m),-m.rb}},Ka:function(a,b){T=b;try{var c=oc(),e=U(),f=U(),h=U(),k=U();a=4294967296*e+(f>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-75;hc(c,a,k);ib=[c.position>>>0,(hb=c.position,1<=+Wa(hb)?0<hb?(Za(+Ya(hb/4294967296),4294967295)|0)>>>0:~~+Xa((hb-+(~~hb>>>0))/4294967296)>>>0:0)];y[h>>2]=ib[0];y[h+4>>2]=ib[1];c.Kb&&0===a&&0===k&&(c.Kb=null);return 0}catch(m){return"undefined"!==typeof S&&
m instanceof I||p(m),-m.rb}},Ja:function(a,b){T=b;try{var c=oc(),e=U();a:{var f=U();for(b=a=0;b<f;b++){var h=y[e+(8*b+4)>>2],k=c,m=y[e+8*b>>2],A=h,v=void 0,G=w;if(0>A||0>v)throw new I(22);if(null===k.fd)throw new I(9);if(1===(k.flags&2097155))throw new I(9);if(K(k.node.mode))throw new I(21);if(!k.qb.read)throw new I(22);var x="undefined"!==typeof v;if(!x)v=k.position;else if(!k.seekable)throw new I(29);var O=k.qb.read(k,G,m,A,v);x||(k.position+=O);var N=O;if(0>N){var q=-1;break a}a+=N;if(N<h)break}q=
a}return q}catch(ka){return"undefined"!==typeof S&&ka instanceof I||p(ka),-ka.rb}},E:function(a,b){T=b;try{var c=oc(),e=U();a:{var f=U();for(b=a=0;b<f;b++){var h=c,k=y[e+8*b>>2],m=y[e+(8*b+4)>>2],A=void 0,v=w;if(0>m||0>A)throw new I(22);if(null===h.fd)throw new I(9);if(0===(h.flags&2097155))throw new I(9);if(K(h.node.mode))throw new I(21);if(!h.qb.write)throw new I(22);h.flags&1024&&hc(h,0,2);var G="undefined"!==typeof A;if(!G)A=h.position;else if(!h.seekable)throw new I(29);var x=h.qb.write(h,v,
k,m,A,void 0);G||(h.position+=x);try{if(h.path&&P.onWriteToFile)P.onWriteToFile(h.path)}catch(q){console.log("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+q.message)}var O=x;if(0>O){var N=-1;break a}a+=O}N=a}return N}catch(q){return"undefined"!==typeof S&&q instanceof I||p(q),-q.rb}},j:function(a,b){T=b;try{var c=oc();switch(U()){case 0:var e=U();return 0>e?-22:ec(c.path,c.flags,0,e).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return e=U(),c.flags|=e,0;case 12:return e=
U(),Ja[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return sb(22),-1;default:return-22}}catch(f){return"undefined"!==typeof S&&f instanceof I||p(f),-f.rb}},Ha:function(a,b){T=b;try{var c=Da(U()),e=Q(c,{parent:!0}).node,f=pb(c),h=Db(e,f),k=Xb(e,f,!0);if(k)throw new I(k);if(!e.pb.rmdir)throw new I(1);if(h.Cb)throw new I(16);try{P.willDeletePath&&P.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}e.pb.rmdir(e,
f);Rb(h);try{if(P.onDeletePath)P.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof S&&m instanceof I||p(m),-m.rb}},Ga:function(a,b){T=b;try{var c=Da(U()),e=U(),f=U();return ec(c,e,f).fd}catch(h){return"undefined"!==typeof S&&h instanceof I||p(h),-h.rb}},D:function(a,b){T=b;try{var c=oc(),e=U();switch(e){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-25;case 21519:if(!c.tty)return-25;var f=U();return y[f>>2]=0;case 21520:return c.tty?-22:-25;case 21531:a=f=U();if(!c.qb.ec)throw new I(25);return c.qb.ec(c,e,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:p("bad ioctl syscall "+e)}}catch(h){return"undefined"!==typeof S&&h instanceof I||p(h),-h.rb}},C:function(a,b){T=b;try{var c=oc();if(null===c.fd)throw new I(9);c.Kb&&(c.Kb=null);try{c.qb.close&&c.qb.close(c)}catch(e){throw e;}finally{Kb[c.fd]=null}c.fd=null;return 0}catch(e){return"undefined"!==
typeof S&&e instanceof I||p(e),-e.rb}},m:function(){},Fa:function(a,b,c,e,f){var h=pc(c);b=V(b);X(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var e=w;else if(2===c)e=Ja;else if(4===c)e=y;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>h])},zb:null})},Ea:function(a,b){b=V(b);X(a,{name:b,fromWireType:function(a){var b=Y[a].value;Bc(a);return b},toWireType:function(a,
b){return Cc(b)},argPackAdvance:8,readValueFromPointer:Dc,zb:null})},B:function(a,b,c){c=pc(c);b=V(b);X(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ec(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Fc(b,c),zb:null})},A:function(a,b,c,e,f,h){var k=Kc(b,c);a=V(a);f=Lc(e,f);Jc(a,function(){Pc("Cannot call "+a+" due to unbound types",k)},b-1);zc(k,function(c){var e=[c[0],
null].concat(c.slice(1)),k=c=a,m=f,x=e.length;2>x&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var O=null!==e[1]&&!1,N=!1,q=1;q<e.length;++q)if(null!==e[q]&&void 0===e[q].zb){N=!0;break}var ka="void"!==e[0].name,da="",la="";for(q=0;q<x-2;++q)da+=(0!==q?", ":"")+"arg"+q,la+=(0!==q?", ":"")+"arg"+q+"Wired";k="return function "+uc(k)+"("+da+") {\nif (arguments.length !== "+(x-2)+") {\nthrowBindingError('function "+k+" called with ' + arguments.length + ' arguments, expected "+
(x-2)+" args!');\n}\n";N&&(k+="var destructors = [];\n");var jc=N?"destructors":"null";da="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[W,m,h,Hc,e[0],e[1]];O&&(k+="var thisWired = classParam.toWireType("+jc+", this);\n");for(q=0;q<x-2;++q)k+="var arg"+q+"Wired = argType"+q+".toWireType("+jc+", arg"+q+"); // "+e[q+2].name+"\n",da.push("argType"+q),m.push(e[q+2]);O&&(la="thisWired"+(0<la.length?", ":"")+la);k+=(ka?"var rv = ":"")+"invoker(fn"+(0<la.length?", ":"")+la+
");\n";if(N)k+="runDestructors(destructors);\n";else for(q=O?1:2;q<e.length;++q)x=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==e[q].zb&&(k+=x+"_dtor("+x+"); // "+e[q].name+"\n",da.push(x+"_dtor"),m.push(e[q].zb));ka&&(k+="var ret = retType.fromWireType(rv);\nreturn ret;\n");da.push(k+"}\n");e=Gc(da).apply(null,m);q=b-1;if(!d.hasOwnProperty(c))throw new yc("Replacing nonexistant public symbol");void 0!==d[c].xb&&void 0!==q?d[c].xb[q]=e:(d[c]=e,d[c].ac=q);return[]})},e:function(a,b,c,e,f){function h(a){return a}
b=V(b);-1===f&&(f=4294967295);var k=pc(c);if(0===e){var m=32-8*c;h=function(a){return a<<m>>>m}}var A=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:h,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Ec(c)+'" to '+this.name);if(c<e||c>f)throw new TypeError('Passing a number "'+Ec(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return A?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Qc(b,
k,0!==e),zb:null})},d:function(a,b,c){function e(a){a>>=2;var b=z;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);X(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{dc:!0})},z:function(a,b){b=V(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(a){var b=z[a>>2];if(c){var e=u[a+4+b],k=0;0!=e&&(k=e,u[a+4+b]=0);var m=a+4;for(e=0;e<=b;++e){var A=a+4+e;if(0==u[A]){m=Da(m);if(void 0===
v)var v=m;else v+=String.fromCharCode(0),v+=m;m=A+1}}0!=k&&(u[a+4+b]=k)}else{v=Array(b);for(e=0;e<b;++e)v[e]=String.fromCharCode(u[a+4+e]);v=v.join("")}Z(a);return v},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var e="string"===typeof b;e||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||W("Cannot pass non-string to std::string");var f=(c&&e?function(){return Ga(b)}:function(){return b.length})(),m=Eb(4+f+1);z[m>>2]=f;if(c&&e)Fa(b,m+4,f+
1);else if(e)for(e=0;e<f;++e){var A=b.charCodeAt(e);255<A&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));u[m+4+e]=A}else for(e=0;e<f;++e)u[m+4+e]=b[e];null!==a&&a.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Dc,zb:function(a){Z(a)}})},Ca:function(a,b,c){c=V(c);if(2===b){var e=function(){return Ka};var f=1}else 4===b&&(e=function(){return z},f=2);X(a,{name:c,fromWireType:function(a){for(var b=e(),c=z[a>>2],h=Array(c),v=a+4>>f,G=0;G<c;++G)h[G]=String.fromCharCode(b[v+
G]);Z(a);return h.join("")},toWireType:function(a,c){var h=e(),k=c.length,v=Eb(4+k*b);z[v>>2]=k;for(var G=v+4>>f,x=0;x<k;++x)h[G+x]=c.charCodeAt(x);null!==a&&a.push(Z,v);return v},argPackAdvance:8,readValueFromPointer:Dc,zb:function(a){Z(a)}})},Ba:function(a,b){b=V(b);X(a,{Je:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Aa:Bc,za:function(a){4<a&&(Y[a].Ob+=1)},ya:function(a,b){var c=sc[a];void 0===c&&W("_emval_take_value has unknown type "+Nc(a));a=c.readValueFromPointer(b);
return Cc(a)},y:function(){d.abort()},wa:function(){r("missing function: av_buffersink_get_frame");p(-1)},va:function(){r("missing function: av_buffersrc_add_frame_flags");p(-1)},x:function(){r("missing function: av_dump_format");p(-1)},l:function(){r("missing function: av_frame_alloc");p(-1)},f:function(){r("missing function: av_frame_free");p(-1)},w:function(){r("missing function: av_free");p(-1)},I:function(){r("missing function: av_get_channel_layout_nb_channels");p(-1)},G:function(){r("missing function: av_get_default_channel_layout");
p(-1)},ua:function(){r("missing function: av_get_sample_fmt_name");p(-1)},ta:function(){r("missing function: av_guess_frame_rate");p(-1)},sa:function(){r("missing function: av_init_packet");p(-1)},v:function(){r("missing function: av_interleaved_write_frame");p(-1)},c:function(){r("missing function: av_log");p(-1)},qa:function(){r("missing function: av_malloc_array");p(-1)},pa:function(){r("missing function: av_mallocz_array");p(-1)},i:function(){r("missing function: av_opt_set_bin");p(-1)},k:function(){r("missing function: av_packet_rescale_ts");
p(-1)},u:function(){r("missing function: av_packet_unref");p(-1)},t:function(){r("missing function: av_read_frame");p(-1)},s:function(){r("missing function: av_strdup");p(-1)},oa:function(){r("missing function: av_strerror");p(-1)},na:function(){r("missing function: av_write_trailer");p(-1)},r:function(){r("missing function: avcodec_alloc_context3");p(-1)},la:function(){r("missing function: avcodec_decode_audio4");p(-1)},ka:function(){r("missing function: avcodec_decode_video2");p(-1)},ja:function(){r("missing function: avcodec_encode_audio2");
p(-1)},ia:function(){r("missing function: avcodec_encode_video2");p(-1)},ha:function(){r("missing function: avcodec_find_decoder");p(-1)},ga:function(){r("missing function: avcodec_find_encoder");p(-1)},q:function(){r("missing function: avcodec_free_context");p(-1)},p:function(){r("missing function: avcodec_open2");p(-1)},fa:function(){r("missing function: avcodec_parameters_copy");p(-1)},da:function(){r("missing function: avcodec_parameters_from_context");p(-1)},ca:function(){r("missing function: avcodec_parameters_to_context");
p(-1)},h:function(){r("missing function: avfilter_get_by_name");p(-1)},ba:function(){r("missing function: avfilter_graph_alloc");p(-1)},aa:function(){r("missing function: avfilter_graph_config");p(-1)},g:function(){r("missing function: avfilter_graph_create_filter");p(-1)},$:function(){r("missing function: avfilter_graph_free");p(-1)},_:function(){r("missing function: avfilter_graph_parse_ptr");p(-1)},o:function(){r("missing function: avfilter_inout_alloc");p(-1)},n:function(){r("missing function: avfilter_inout_free");
p(-1)},Y:function(){r("missing function: avformat_alloc_output_context2");p(-1)},X:function(){r("missing function: avformat_close_input");p(-1)},W:function(){r("missing function: avformat_find_stream_info");p(-1)},V:function(){r("missing function: avformat_free_context");p(-1)},U:function(){r("missing function: avformat_new_stream");p(-1)},T:function(){r("missing function: avformat_open_input");p(-1)},S:function(){r("missing function: avformat_write_header");p(-1)},R:function(){r("missing function: avio_closep");
p(-1)},Q:function(){r("missing function: avio_open");p(-1)},P:Rc,N:function(a,b,c){u.set(u.subarray(b,b+c),a)},M:function(a){var b=Rc();assert(a>b);if(2147418112<a)return r("Cannot enlarge memory, asked to go up to "+a+" bytes, but the limit is 2147418112 bytes!"),!1;for(var c=Math.max(b,16777216);c<a;)536870912>=c?c=Ia(2*c):c=Math.min(Ia((3*c+2147483648)/4),2147418112),c===b&&ua("Cannot ask for more memory since we reached the practical limit in browsers (which is just below 2GB), so the request would have failed. Requesting only "+
w.length);a:{a=c;try{t.grow(a-buffer.byteLength+65535>>16);Na(t.buffer);var e=1;break a}catch(f){console.error("emscripten_realloc_buffer: Attempted to grow heap from "+buffer.byteLength+" bytes to "+a+" bytes, but got error: "+f)}e=void 0}return e?!0:(r("Failed to grow the heap from "+b+" bytes to "+c+" bytes, not enough memory!"),!1)},L:function(){p("trap!")},K:function(a){p("Cannot enlarge memory arrays to size "+a+" bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+
w.length+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},a:18992},buffer);d.asm=Uc;
d.___embind_register_native_and_builtin_types=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Sa.apply(null,arguments)};
d.___errno_location=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Ta.apply(null,arguments)};
var Oc=d.___getTypeName=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Ua.apply(null,arguments)};d._fflush=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Va.apply(null,arguments)};
var Z=d._free=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Wa.apply(null,arguments)};d._main=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Xa.apply(null,arguments)};
var Eb=d._malloc=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Ya.apply(null,arguments)};
d.establishStackSpace=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.jb.apply(null,arguments)};
var jb=d.globalCtors=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.kb.apply(null,arguments)},ta=d.stackAlloc=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.lb.apply(null,arguments)};
d.stackRestore=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.mb.apply(null,arguments)};var sa=d.stackSave=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.nb.apply(null,arguments)};
d.dynCall_ii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.Za.apply(null,arguments)};d.dynCall_iidiiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._a.apply(null,arguments)};
d.dynCall_iii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.$a.apply(null,arguments)};d.dynCall_iiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.ab.apply(null,arguments)};
d.dynCall_iiiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.bb.apply(null,arguments)};d.dynCall_jiji=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.cb.apply(null,arguments)};
d.dynCall_v=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.db.apply(null,arguments)};d.dynCall_vi=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.eb.apply(null,arguments)};
d.dynCall_vii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.fb.apply(null,arguments)};d.dynCall_viiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.gb.apply(null,arguments)};
d.dynCall_viiiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.hb.apply(null,arguments)};d.dynCall_viiiiii=function(){assert(C,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!D,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.ib.apply(null,arguments)};
d.asm=Uc;Object.getOwnPropertyDescriptor(d,"intArrayFromString")||(d.intArrayFromString=function(){p("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"intArrayToString")||(d.intArrayToString=function(){p("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"ccall")||(d.ccall=function(){p("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"cwrap")||(d.cwrap=function(){p("'cwrap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"setValue")||(d.setValue=function(){p("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getValue")||(d.getValue=function(){p("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"allocate")||(d.allocate=function(){p("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getMemory")||(d.getMemory=function(){p("'getMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"AsciiToString")||(d.AsciiToString=function(){p("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"stringToAscii")||(d.stringToAscii=function(){p("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"UTF8ArrayToString")||(d.UTF8ArrayToString=function(){p("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"UTF8ToString")||(d.UTF8ToString=function(){p("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"stringToUTF8Array")||(d.stringToUTF8Array=function(){p("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stringToUTF8")||(d.stringToUTF8=function(){p("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"lengthBytesUTF8")||(d.lengthBytesUTF8=function(){p("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"UTF16ToString")||(d.UTF16ToString=function(){p("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stringToUTF16")||(d.stringToUTF16=function(){p("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"lengthBytesUTF16")||(d.lengthBytesUTF16=function(){p("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"UTF32ToString")||(d.UTF32ToString=function(){p("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stringToUTF32")||(d.stringToUTF32=function(){p("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"lengthBytesUTF32")||(d.lengthBytesUTF32=function(){p("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"allocateUTF8")||(d.allocateUTF8=function(){p("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stackTrace")||(d.stackTrace=function(){p("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"addOnPreRun")||(d.addOnPreRun=function(){p("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"addOnInit")||(d.addOnInit=function(){p("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"addOnPreMain")||(d.addOnPreMain=function(){p("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"addOnExit")||(d.addOnExit=function(){p("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"addOnPostRun")||(d.addOnPostRun=function(){p("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"writeStringToMemory")||(d.writeStringToMemory=function(){p("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"writeArrayToMemory")||(d.writeArrayToMemory=function(){p("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"writeAsciiToMemory")||(d.writeAsciiToMemory=function(){p("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"addRunDependency")||(d.addRunDependency=function(){p("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(d,"removeRunDependency")||(d.removeRunDependency=function(){p("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"ENV")||(d.ENV=function(){p("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"FS")||(d.FS=function(){p("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"FS_createFolder")||(d.FS_createFolder=function(){p("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"FS_createPath")||(d.FS_createPath=function(){p("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(d,"FS_createDataFile")||(d.FS_createDataFile=function(){p("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"FS_createPreloadedFile")||(d.FS_createPreloadedFile=function(){p("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(d,"FS_createLazyFile")||(d.FS_createLazyFile=function(){p("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"FS_createLink")||(d.FS_createLink=function(){p("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(d,"FS_createDevice")||(d.FS_createDevice=function(){p("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(d,"FS_unlink")||(d.FS_unlink=function(){p("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(d,"GL")||(d.GL=function(){p("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"dynamicAlloc")||(d.dynamicAlloc=function(){p("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"loadDynamicLibrary")||(d.loadDynamicLibrary=function(){p("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"loadWebAssemblyModule")||(d.loadWebAssemblyModule=function(){p("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getLEB")||(d.getLEB=function(){p("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getFunctionTables")||(d.getFunctionTables=function(){p("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"alignFunctionTables")||(d.alignFunctionTables=function(){p("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"registerFunctions")||(d.registerFunctions=function(){p("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"addFunction")||(d.addFunction=function(){p("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"removeFunction")||(d.removeFunction=function(){p("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getFuncWrapper")||(d.getFuncWrapper=function(){p("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"prettyPrint")||(d.prettyPrint=function(){p("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"makeBigInt")||(d.makeBigInt=function(){p("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"dynCall")||(d.dynCall=function(){p("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"getCompilerSetting")||(d.getCompilerSetting=function(){p("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"stackSave")||(d.stackSave=function(){p("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stackRestore")||(d.stackRestore=function(){p("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"stackAlloc")||(d.stackAlloc=function(){p("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"establishStackSpace")||(d.establishStackSpace=function(){p("'establishStackSpace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"print")||(d.print=function(){p("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"printErr")||(d.printErr=function(){p("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"getTempRet0")||(d.getTempRet0=function(){p("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"setTempRet0")||(d.setTempRet0=function(){p("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"callMain")||(d.callMain=function(){p("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"Pointer_stringify")||(d.Pointer_stringify=function(){p("'Pointer_stringify' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"warnOnce")||(d.warnOnce=function(){p("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"writeStackCookie")||(d.writeStackCookie=function(){p("'writeStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(d,"checkStackCookie")||(d.checkStackCookie=function(){p("'checkStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"abortStackOverflow")||(d.abortStackOverflow=function(){p("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(d,"ALLOC_NORMAL")||Object.defineProperty(d,"ALLOC_NORMAL",{get:function(){p("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
Object.getOwnPropertyDescriptor(d,"ALLOC_STACK")||Object.defineProperty(d,"ALLOC_STACK",{get:function(){p("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(d,"ALLOC_DYNAMIC")||Object.defineProperty(d,"ALLOC_DYNAMIC",{get:function(){p("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(d,"ALLOC_NONE")||Object.defineProperty(d,"ALLOC_NONE",{get:function(){p("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
Object.getOwnPropertyDescriptor(d,"calledRun")||Object.defineProperty(d,"calledRun",{get:function(){p("'calledRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")}});var Vc;d.then=function(a){if(Vc)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};
function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}$a=function Wc(){Vc||Xc();Vc||($a=Wc)};
function Xc(a){function b(){if(!Vc&&(Vc=!0,!Aa)){Pa();assert(!C);C=!0;if(!d.noFSInit&&!kc){assert(!kc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");kc=!0;ic();d.stdin=d.stdin;d.stdout=d.stdout;d.stderr=d.stderr;d.stdin?mc("stdin",d.stdin):dc("/dev/tty","/dev/stdin");d.stdout?mc("stdout",null,d.stdout):dc("/dev/tty","/dev/stdout");d.stderr?mc("stderr",null,d.stderr):dc("/dev/tty1",
"/dev/stderr");var b=ec("/dev/stdin","r"),e=ec("/dev/stdout","w"),f=ec("/dev/stderr","w");assert(0===b.fd,"invalid handle for stdin ("+b.fd+")");assert(1===e.fd,"invalid handle for stdout ("+e.fd+")");assert(2===f.fd,"invalid handle for stderr ("+f.fd+")")}Qa(Sa);Pa();Mb=!1;Qa(Ta);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Yc){b=a;assert(0==E,'cannot call main when async dependencies remain! (listen on Module["onRuntimeInitialized"])');assert(0==Ra.length,"cannot call main when preRun functions remain to be called");
b=b||[];e=b.length+1;f=ta(4*(e+1));y[f>>2]=Ha(ca);for(var h=1;h<e;h++)y[(f>>2)+h]=Ha(b[h-1]);y[(f>>2)+e]=0;try{var k=d._main(e,f);Zc();if(!za||0!==k){if(!za&&(Aa=!0,Pa(),D=!0,d.onExit))d.onExit(k);ea(k,new qa(k))}}catch(m){m instanceof qa||("SimulateInfiniteLoop"==m?za=!0:((k=m)&&"object"===typeof m&&m.stack&&(k=[m,m.stack]),r("exception thrown: "+k),ea(1,m)))}finally{}}Pa();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)k=d.postRun.shift(),Ua.unshift(k);
Qa(Ua)}}a=a||ba;if(!(0<E)){assert(!0);z[1315475]=34821223;z[1315474]=2310721022;if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Va();Qa(Ra);0<E||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b(),Pa())}}d.run=Xc;
function Zc(){var a=ra,b=r,c=!1;ra=r=function(){c=!0};try{var e=d._fflush;e&&e(0);["stdout","stderr"].forEach(function(a){a="/dev/"+a;try{var b=Q(a,{Hb:!0});a=b.path}catch(m){}var e={fc:!1,exists:!1,error:0,name:null,path:null,object:null,ic:!1,kc:null,jc:null};try{b=Q(a,{parent:!0}),e.ic=!0,e.kc=b.path,e.jc=b.node,e.name=pb(a),b=Q(a,{Hb:!0}),e.exists=!0,e.path=b.path,e.object=b.node,e.name=b.node.name,e.fc="/"===b.path}catch(m){e.error=m.rb}e&&(b=ub[e.object.rdev])&&b.output&&b.output.length&&(c=
!0)})}catch(f){}ra=a;r=b;c&&ua("stdio streams had content in them that was not flushed. you should set EXIT_RUNTIME to 1 (see the FAQ), or make sure to emit a newline when you printf etc.")}var $c=[];function p(a){if(d.onAbort)d.onAbort(a);ra(a);r(a);Aa=!0;var b="abort("+a+") at "+lb();$c&&$c.forEach(function(c){b=c(b,a)});throw b;}d.abort=p;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Yc=!1;d.noInitialRun&&(Yc=!1);za=!0;Xc();


  return ffmpeg
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ffmpeg;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ffmpeg; });
    else if (typeof exports === 'object')
      exports["ffmpeg"] = ffmpeg;
    